nextcloud/integration_openproject

bootstrap.php
composer.json
composer.lock
lib/AppInfo/Application.php
lib/Controller/ConfigController.php
lib/Controller/OpenProjectAPIController.php
lib/Service/OpenProjectAPIService.php
makefile
phpunit.xml
tests/lib/Service/OpenProjectAPIServiceTest.php

followup to c4d6540aa3bf8f8fbd8748a08281207ba6fb7189
the validation has also to be fixed in the backend code 
instead of using a regex I propose to use the PHP build-in `filter_var` function and a simple regex to make sure the URI starts with http(s) as protocol
added unit tests to make sure it works correctly
fixes #9

improve backend OpenProject URL validation

---

lib/Controller/ConfigController.php

do the same as for the userconfig in https://github.com/eneiluj/integration_openproject/blob/master/lib/Controller/ConfigController.php#L72
mainly to ensure there are no accidental spaces at the end of the client ID and the client secret

trim admin settings before saving them

---

README.md
src/components/AdminSettings.vue

- rename labels be to consistent with OpenProject
to reduce confusion use the same term as OpenProject 
- improve OAuth documentation
more details about how to set it up

improve OAuth documentation

---

.github/workflows/ci.yml
bootstrap.php
composer.json
composer.lock
jest.config.js
phpunit.xml
tests/lib/Service/OpenProjectAPIServiceTest.php

using the framework of pact.io to mock the OAuth requests of OpenProject and testing the `request` function
I'm open for discussion if that is the framework we want to use to mock the requests. The advantage is that, we can simulate real requests and responses without having to spin up a complete NC or OpenProject server.
The framework writes the requests and response into a JSON file and in future we can use that to verify that what we expect from OpenProject is really what they send.
here a short intro in how it works: https://docs.pact.io/getting_started/how_pact_works#consumer-testing

test OAuth requests using pact.io as mock server OP#40804

---

src/components/tab/EmptyContent.vue
src/views/ProjectsTab.vue
tests/jest/__mocks__/@nextcloud/router.js
tests/jest/components/tab/EmptyContent.spec.js
tests/jest/views/ProjectsTab.spec.js

In case there is no connection to OpenProject or workpackages could not be fetched, the user should see that information in the files tab and be able to navigate to the connection settings from there.
Currently this will always show "Error" as fetching workpackages is not implemented yet

show 'no connection' message in files tab OP#4068

---

bootstrap.php
tests/lib/Controller/OpenProjectAPIControllerTest.php

some basic unit tests for OpenProjectAPIController::getNotifications()
just checking responses in cases of an error, success and no token

unit tests for OpenProjectAPIController::getNotifications()

---

lib/Controller/ConfigController.php
tests/lib/Controller/ConfigControllerTest.php

- basic unit tests for `ConfigController::oauthRedirect()`
- improve checks and error reporting in that function, so that missing data does not cause undefined index errors

unit tests for ConfigController::oauthRedirect

---

tests/lib/Service/OpenProjectAPIServiceTest.php

some basic unit tests for OpenProjectAPIService::searchWorkPackage
checking if array from two searches are merged correctly

unit tests for OpenProjectAPIService::searchWorkPackage()

---

css/tab.css
lib/Listener/LoadSidebarScript.php
src/components/tab/EmptyContent.vue
src/views/ProjectsTab.vue

- For now, static padding was used
- From now, empty content will be center-aligned with the tab content

Center align empty content

---

css/tab.css
src/components/tab/EmptyContent.vue

`.fill-height` is only present in `<EmptyContent>` so it might be cleaner to define its style there.
`.center-content` style is already set in `<ProjectsTab>` and this affects the child components. No need to define it in `tab.css`.
In general I would say it's best to define the style in the components and only use `tab.css` when it's the only way.
What do you think?

Small style adjustments

---

.github/workflows/ci.yml
jest.config.js
package.json
phpunit.xml

run coverage analysis after test runs, report it in github comment and fail CI if the coverage is below current percentage

code-coverage OP#40949

---

css/dashboard.css
lib/Dashboard/OpenProjectWidget.php

The filter was causing the whole `label` background to be black.
With this PR pseudo-elements are used to show OP icons in the dashboard.
A separate CSS selector is introduced for the dashboard widget icon.
- Fixes OP#40947
nshots
190.png)
bf3dc4.p
ng)

Used pseudo elements for dashboard widget app icons

---

.gitignore

Every time we run `vue` unit tests, coverage is generated.
this coverage is not necessary for vcs tracking
this pr adds the `coverage` folder to the ignore list  so that we do not commit is even accidentally

Added coverage to git ignore list

---

.gitignore

**Resources:**
- PHPUnit caches
- `example` dir
- `log` dir
- `vendor` dir
These are the resources generated or modified during development. Sometimes these can get accidentally added to git and instantly we may get `3000+` changes in a PR. So, all of the mentioned resources are added to the `gitignore` list.

Added test caches, vendor, example and log files to the gitignore list

---

.github/workflows/ci.yml
.php-cs-fixer.dist.php
bootstrap.php
composer.json
composer.lock
lib/AppInfo/Application.php
lib/BackgroundJob/CheckNotifications.php
lib/Controller/ConfigController.php
lib/Controller/OpenProjectAPIController.php
lib/Listener/LoadSidebarScript.php
lib/Search/OpenProjectSearchProvider.php
lib/Service/OpenProjectAPIService.php
makefile
phpstan.neon
tests/lib/Controller/ConfigControllerTest.php
tests/lib/Controller/OpenProjectAPIControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

- run PHPstan in CI
- fix issues phpstan complained about
- run tests with NC 23 and NC dev version (master branch)

implement phpstan

---

css/tab.css

with NC server version: 23, the sidebar tab icon was completely grey.
this pr fixes the issue
OP#41083

set background image size to fit into the element background

---

lib/Controller/OpenProjectAPIController.php
lib/Service/OpenProjectAPIService.php
tests/lib/Controller/OpenProjectAPIControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

the codepath in the fist part of the if statement could not be reached because `getOpenProjectAvatar` never returns an array with `error` as key
so I've deleted that code and covered the codepath with some basic unit tests

[#40968] fix getOpenProjectAvatar error handling

---

lib/Service/OpenProjectAPIService.php

this will make it simpler to extend the filter, e.g. when we want also to filter by `file_link_origin_id` to list all workpackages associated to the file

construct filters from array

---

.github/workflows/ci.yml

Sometimes we may push more frequently so that there may be a running workflow for previous pushes in a PR. These in-progress runs will be canceled leaving only the latest run.
GH Action Used: https://github.com/styfle/cancel-workflow-action#advanced-all-but-latest

[CI] cancel running workflows for the PR except the latest one

---

.github/workflows/ci.yml

- run ci with php versions:
- 7.4
- 8.0
OP#41126

[CI] run CI with multiple versions of PHP (7.4, 8.0)

---

lib/Controller/ConfigController.php
lib/Controller/OpenProjectAPIController.php
lib/Search/OpenProjectSearchProvider.php
lib/Service/OpenProjectAPIService.php
tests/lib/Controller/ConfigControllerTest.php
tests/lib/Controller/OpenProjectAPIControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

delete all code that has to do with api key based auth

OP#40534 delete anything to do with API tokens

---

appinfo/routes.php
src/components/tab/SearchInput.vue

Refactor route name `work_packages` to `work-packages`
OP#41125
https://community.openproject.org/projects/nextcloud-integration/work_packages/41125

refactor route name 'work_packages' to 'work-packages'

---

src/components/tab/SearchInput.vue
tests/jest/components/tab/SearchInput.spec.js
tests/jest/fixtures/workPackageSearchReqResponse.json

part of OP#41124: This PR adds a loading icon when fetching work packages
It looks something like this:

[OP#41124] Display loading icon while fetching workpackages

---

composer.json
composer.lock

> I updated my local system to the latest `composer` 2.2.6. When I do `composer update` it now asks me if I trust the composer plugins that we use. After answering "yes" it adds that "trust" to `composer.json`
> https://getcomposer.org/doc/06-config.md#allow-plugins
"As of Composer 2.2.0, the allow-plugins option adds a layer of security allowing you to restrict which Composer plugins are able to execute code during a Composer run."
originally posted by @phil-davis in https://github.com/owncloud/QA/issues/723

Add composer allow plugins

---

lib/Controller/ConfigController.php
tests/jest/components/OAuthConnectButton.spec.js
tests/lib/Controller/ConfigControllerTest.php

getting it from user config is obsolete since #35 best just generate it here

generate redirect_uri and don't take it from user config

---

README.md

we can use GitHub provided emoji tokens rather than the emoji char itself in our readme file.

used github emojis in readme

---

lib/Controller/OpenProjectAPIController.php
lib/Service/OpenProjectAPIService.php
src/components/tab/EmptyContent.vue
src/views/ProjectsTab.vue
tests/jest/components/tab/EmptyContent.spec.js
tests/jest/views/ProjectsTab.spec.js
tests/lib/Controller/OpenProjectAPIControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

This turned into a bit of refactoring for passing around error messages.
Now we have these options that can happen:
When OpenProject server is not reachable
OpenProject does not support the filter (what is currently always the case, because its not implemented yet)
No OAuth connection to OpenProject, because the connection was not established yet

[#40969] show correct error message in files tab

---

README.md

- add missing `cd` step after cloning
- state `node`, `npm`, `docker` version requirements

[docs] update developer documentation

---

.gitignore
bootstrap.php
lib/Controller/OpenProjectAPIController.php
lib/Exception/OpenprojectErrorException.php
lib/Exception/OpenprojectResponseException.php
lib/Service/OpenProjectAPIService.php
phpunit.xml
src/components/tab/SearchInput.vue
tests/jest/components/tab/SearchInput.spec.js
tests/lib/Controller/OpenProjectAPIControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

ability to link files to packages, backend for #64 
manually tested with https://github.com/opf/openproject/tree/feature/file-links

[OP#41102] link workpackage backend

---

lib/Dashboard/OpenProjectWidget.php
lib/Listener/LoadSidebarScript.php
lib/Service/OpenProjectAPIService.php
lib/Settings/Personal.php
src/components/AdminSettings.vue
src/components/OAuthConnectButton.vue
src/components/PersonalSettings.vue
src/components/tab/EmptyContent.vue
src/views/Dashboard.vue
src/views/ProjectsTab.vue
tests/jest/components/OAuthConnectButton.spec.js
tests/jest/components/PersonalSettings.spec.js
tests/jest/components/__snapshots__/OAuthConnectButton.spec.js.snap
tests/jest/components/tab/EmptyContent.spec.js
tests/lib/Service/OpenProjectAPIServiceTest.php

For dashboard widget, sidebar tab, and personal setting:
- check if the admin config is ok (if all values are set and OAuth instance URL is valid)
- show connect button if ok
- show message `Failed to establish the connection. Please contact your administrator.` if not ok
https://community.openproject.org/projects/nextcloud-integration/work_packages/41211

Do not show the connect button if admin config is not ok

---

src/components/OAuthConnectButton.vue
tests/jest/components/__snapshots__/OAuthConnectButton.spec.js.snap

_Reported by a translator from Transifex._
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

l10n: Correct instance name

---

src/components/tab/SearchInput.vue
src/utils/workpackageHelper.js
src/views/ProjectsTab.vue
tests/jest/components/tab/SearchInput.spec.js
tests/jest/views/ProjectsTab.spec.js
tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap

fetches and shows all existing links between file and work-package
tested with https://github.com/opf/openproject/pull/10052
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/41289
https://user-images.githubusercontent.com/2425577/158364893-21afed40-5991-41a7-a2c0-86772ee3b04d.mp4

[OP#41289] list all linked workpackages 

---

lib/Dashboard/OpenProjectWidget.php
lib/Listener/LoadSidebarScript.php
lib/Service/OpenProjectAPIService.php
lib/Settings/Personal.php
makefile
package.json
src/components/OAuthConnectButton.vue
src/components/PersonalSettings.vue
src/components/tab/EmptyContent.vue
src/views/Dashboard.vue
src/views/ProjectsTab.vue
tests/jest/components/OAuthConnectButton.spec.js
tests/jest/components/PersonalSettings.spec.js
tests/jest/components/__snapshots__/OAuthConnectButton.spec.js.snap
tests/jest/components/tab/EmptyContent.spec.js
tests/jest/views/ProjectsTab.spec.js
tests/lib/Service/OpenProjectAPIServiceTest.php

- throw exception from `getOpenProjectOauthURL` if request url is not valid
- show admin settings invalid message if request URL is not valid in dashboard widget, sidebar, and personal settings components
- show/hide search input in the sidebar tab according to the request URL
- error icon when request URL is invalid for dashboard widget and empty content in the sidebar
OP#41211 > 3rd todo item
https://community.openproject.org/projects/nextcloud-integration/work_packages/41211

refactor `getOpenProjectOauthURL` so that it throws an exception if any needed value is not set

---

src/components/tab/WorkPackage.vue

currently, we're using a static width for work package status in the search result.
work package status text may have variable length, so the static width may lead to UI inconsistency like:
`very-long-status-te`~~xt~~ is missed because it does not fit inside specified static width
`bug................`  a long gap for short status
This PR makes use of dynamic width for the work package status indicator.

use fit-content for workpackage status

---

src/components/tab/WorkPackage.vue
tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap
tests/jest/components/tab/__snapshots__/WorkPackage.spec.js.snap
tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap

- center align work package id and project information
- right margin for work package status and type title

Css enhancements for the workpackage component

---

lib/Controller/ConfigController.php
lib/Controller/OpenProjectAPIController.php
lib/Search/OpenProjectSearchProvider.php
lib/Service/OpenProjectAPIService.php
tests/lib/Controller/ConfigControllerTest.php
tests/lib/Controller/OpenProjectAPIControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

get configuration like token, url, etc. in the function that needs it `request` and don't pass this data through multiple levels
I think the code is more readable that way.
Thoughts?

get OAuth config in request function and don't pass the data through the different layers

---

lib/Service/OpenProjectAPIService.php

Closes #83
Signed-off-by: q-wertz <clemens.sonnleitner@web.de>

Lower error message level to debug to not clutter log

---

src/components/tab/SearchInput.vue
tests/jest/components/tab/SearchInput.spec.js

Reset search input state if the `fileInfo` prop changes
[OP#41470](https://community.openproject.org/projects/nextcloud-integration/work_packages/41470)

[op#41470] reset search input state if fileInfo prop has changed

---

bootstrap.php
tests/lib/Service/OpenProjectAPIServiceTest.php
tests/lib/Settings/PersonalTest.php

- add data provider for `testGetOpenProjectOauthURLWithInvalidAdminConfig`
- add unit tests for `Settins\Personal -> getForm` function
https://community.openproject.org/projects/nextcloud-integration/work_packages/41211

add unit tests for lib\Settings\Personal 

---

src/components/tab/SearchInput.vue
tests/jest/components/tab/SearchInput.spec.js
tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap

Previously, the new search results were pushed to the existing list which leads us to show not related work packages in the multi-select options.
With this PR, every time a new request is being made, the search results list is cleared beforehand.
https://community.openproject.org/projects/nextcloud-integration/work_packages/41495
OP#41495

Use options from the latest search response

---

lib/Controller/OpenProjectAPIController.php
lib/Service/OpenProjectAPIService.php
tests/lib/Service/OpenProjectAPIServiceTest.php

when searching by query (to link a wp to file):
- don't filter by a magic status id, but by the meta-status "open" 
- additionally filter out packages that cannot be linked to the current storage
CC @Kharonus

[OP#41127] filter work packages by storage and sort by status

---

css/dashboard.css

after some recent CSS modifications, openproject icon color in the sidebar tab is black for dark theme
this pr should fix this case
**Before**
**After**

Fix tab icon color in dark mode

---

src/components/tab/WorkPackage.vue
src/views/ProjectsTab.vue
tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap

OP#41675: https://community.openproject.org/projects/nextcloud-integration/work_packages/41675/activity
This PR adds a separator between the work packages

[OP#41675] Add a separator between workpackages in project tab

---

package-lock.json
package.json
src/components/tab/SearchInput.vue
src/utils/workpackageHelper.js
tests/jest/components/tab/SearchInput.spec.js
tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap

With this PR: `makeSearchRequest` function is debounced 500 ms to make a new search request.
- OP#41514
- https://community.openproject.org/projects/nextcloud-integration/work_packages/41514

Use debounced function to make new search request

---

appinfo/routes.php
lib/Controller/OpenProjectAPIController.php
lib/Service/OpenProjectAPIService.php
src/utils/workpackageHelper.js
src/views/ProjectsTab.vue
tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap
tests/jest/fixtures/workPackagesSearchResponse.json
tests/jest/fixtures/workPackagesSearchResponseNoAssignee.json
tests/jest/views/ProjectsTab.spec.js
tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap
tests/lib/Controller/OpenProjectAPIControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

https://community.openproject.org/wp/41290
This PR adds:
- Implementation of navigation to open project work package while clicking on the linked wp in the project tab
- Implementation of unlinking of the work package and file upon clicking a unlink button that appears on hover 
- Unit tests and pact tests

[OP #41290] Implementation of navigation and link deletion

---

src/components/tab/SearchInput.vue
tests/jest/components/tab/SearchInput.spec.js

Reset the search input state after a work package is linked successfully
OP#42140
https://community.openproject.org/projects/nextcloud-integration/work_packages/42140/github

[Bug/42140] the search result isnt cleared when a work package is selected

---

src/components/tab/SearchInput.vue
src/components/tab/WorkPackage.vue
src/views/ProjectsTab.vue
tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap

OP#42172 Add a separator between work packages in the search list

[OP#42172] Add a seperator between worpackages search list

---

src/components/tab/EmptyContent.vue
stylelint.config.js

Noticed in some pr that we may push the css styles with random spaces and new lines.
this will make our css more consistent for spaces and new lines involved.

add rules related to stylelint spaces and newlines

---

src/components/tab/EmptyContent.vue
src/views/Dashboard.vue
src/views/ProjectsTab.vue
tests/jest/components/tab/EmptyContent.spec.js
tests/jest/views/ProjectsTab.spec.js
tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap

OP#42097,
- do not fetch work packages if the admin config is not ok
- do not fetch notifications if the admin config is not ok
https://community.openproject.org/projects/nextcloud-integration/work_packages/42097

[Bug/42097] relations/notifications even when the oauth information is not complete

---

lib/Service/OpenProjectAPIService.php
tests/lib/Service/OpenProjectAPIServiceTest.php

part of https://community.openproject.org/projects/nextcloud-integration/work_packages/41271
when refreshing the oauth token, open project not only sends back a new token but also a new refresh-token, that also needs to be remembered, otherwise the second refresh would fail.
CC @Kharonus

OP#41271 remember new refresh_token after refreshing oauth token

---

lib/Controller/OpenProjectAPIController.php
lib/Service/OpenProjectAPIService.php
tests/lib/Controller/OpenProjectAPIControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

the search and the link function could be used without or a wrong storageUrl, this is actually not needed, I'm suggesting in this PR to send the storageURL in every link and search request to OpenProject
should fix https://community.openproject.org/work_packages/41949 
In the search for listing existing  links we did not send the storageUrl as filter so also links from other storages would show up

OP#41949 allways send storageUrl

---

appinfo/routes.php

The endpoint for `deleting` a link should be inside `routes` but PR https://github.com/nextcloud/integration_openproject/pull/67/files#diff-6301937af1cc1575e9e18ecd27c4a51f0d3cf9ce12e59a14709f626dfa3ef952 misplaced it 
This PR fixes that. This fixes the unlinking of the work package which wasn't working before.

Fix the misplaced route

---

lib/Controller/ConfigController.php
lib/Settings/Admin.php
src/components/AdminSettings.vue
tests/jest/components/AdminSettings.spec.js
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
tests/lib/Controller/ConfigControllerTest.php

- implement confirm dialog to update admin credentials
- delete user prefs. if updated admin config is not ok
- added button to submit the form
- [OP#42273] part of https://community.openproject.org/projects/nextcloud-integration/work_packages/42273

add confirm dialog for admin config update action

---

src/components/tab/SearchInput.vue
tests/jest/components/tab/SearchInput.spec.js

fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/42140
when a link gets created the state switches from `loading` to `ok` and the list of workpackages in the search gets cleaned, but if some requests were outstanding workpackages would be kept on added to the list and it would not be cleaned correctly.
This PR makes sure workpackages are not processed and the searchlist is not extended while the state is anything else than `loading`

OP#42140 only addd to searchlist when in loading state

---

src/views/ProjectsTab.vue
tests/jest/views/ProjectsTab.spec.js

We check for the request-url, before showing the search input the users. If it is not valid, it is kept hidden, but if the url is valid, the input is shown early even if the projects tab is still loading fetching for the linked work packages.
With this PR, the search input is shown only if the the request URL is valid and the projects tab state is not loading.
https://community.openproject.org/projects/nextcloud-integration/work_packages/41496

Do not show search input unless the projects tab is completely loaded

---

src/components/tab/SearchInput.vue
src/utils/workpackageHelper.js
src/views/ProjectsTab.vue
tests/jest/components/tab/SearchInput.spec.js
tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap
tests/jest/fixtures/workPackageObjectsInSearchResults.json
tests/jest/fixtures/workPackagesSearchResponse.json
tests/jest/views/ProjectsTab.spec.js
tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap

switching between files while the list is still loading might add data from an other file to the current view, see https://community.openproject.org/projects/nextcloud-integration/work_packages/41503
To protect from that this PR:
1. checks is a WP already exists in the list (by comparing the fileId and the WPid)
2. filters the workpackages to show by the fileId of the file currently in view
manual test-cases
| test | expected outcome  | result |
| --- | --- | --- |
| 1. link file1 to WP-A, WP-B, WP-C 2. link file2 to WP-D, WP-E 3. quickly switch between the files | WP list is correct, no extra WP listed | :heavy_check_mark: |
| 1. link file1 to WP-A, WP-B, WP-C 2. link file2 to WP-C, WP-D 3. quickly switch between the files | WP list is correct, no extra WP listed, WP-C is shown in both …

OP#41503 only show WP belonging to this file (async cases)

---

lib/Controller/OpenProjectAPIController.php
lib/Notification/Notifier.php
lib/Service/OpenProjectAPIService.php
src/views/Dashboard.vue
tests/lib/Service/OpenProjectAPIServiceCheckNotificationsTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

use the notification API to fetch notifications from OpenProject (for dashboard and for the NC notifications)
please note for the notifications to work you need to install and enable the notifications NC app https://github.com/nextcloud/notifications and also enable `Enable notifications for activity in my work packages` in the openproject_integration personal settings
dashboard view
notifications view
The count of notifications in the notifications view is the count of NEW notifications since the last check. Dismissing notifications on NC side will NOT have any effect on the OP notifications
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/41678

[OP#41678] use notifications API to fetch OP notifications

---

tests/lib/Controller/ConfigControllerTest.php
tests/lib/Service/OpenProjectAPIServiceCheckNotificationsTest.php

1. phpstan tests started to fail with PHP 8, complaining about missing return of `callForAllUsers` callback
2. more mocks needed for the notification tests, that must have happened with merging multiple PRs where each would pass CI by itself but together not

fix php tests

---

css/dashboard.css
lib/Dashboard/OpenProjectWidget.php
src/components/AdminSettings.vue
src/components/OAuthConnectButton.vue
src/components/settings/SettingsTitle.vue
src/components/tab/EmptyContent.vue
src/views/ProjectsTab.vue

Recently there has been some design, theme related updates in the NC server. `body.theme--dark` has been dropped to now use `body[data-theme-dark]`
this PR should fix:
- placement and colors of the op logo in the dashboard widget
- the color of the op logo in the sidebar tab
- the color and size of the op logo in the settings title
- the color of the label icons for the admin settings page
- the text colors for empty content view
- [OP#42270] should fix https://community.openproject.org/projects/nextcloud-integration/work_packages/42270
- [OP#42475] should fix https://community.openproject.org/projects/nextcloud-integration/work_packages/42475

Fix icon placements and colors for different themes

---

appinfo/routes.php
lib/Controller/OpenProjectAPIController.php
lib/Service/OpenProjectAPIService.php
src/components/AdminSettings.vue
tests/jest/components/AdminSettings.spec.js
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
tests/lib/Controller/OpenProjectAPIControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

before accepting an OpenProject instance URL, check if there is an OpenProject server actually listening on that URL
checks are done similar to https://github.com/opf/openproject-revit-add-in/blob/master/src/OpenProject.Browser/WebViewIntegration/OpenProjectInstanceValidator.cs#L19 
- `_type` must `Root` or `Error`
- in case of `Root` (public instance) -> `instanceName` has to be set
- in case of `Error` (private instance) -> `errorIdentifier` has to be set
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/42614

[OP#42614] check if an OpenProject server replies on the URL given in the admin settings

---

src/views/ProjectsTab.vue
tests/jest/views/ProjectsTab.spec.js
tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap

This PR changes(replaces) the unlink work package button (used div previously) with the help of action button (nexcloud component). 
OP#42134 https://community.openproject.org/projects/nextcloud-integration/work_packages/42134/activity

Replace the unlink button to actions component

---

src/views/Dashboard.vue

- do not use the speaker icon at all for the notification items in the dashboard widget
in the widget item component, there is a check for the icon URL if it's truthy. Ref: https://github.com/nextcloud/nextcloud-vue-dashboard/blob/fd9246f2e3102dd0b33ac1e90975a42f518354b6/src/DashboardWidgetItem.vue#L39
we set is as `false` so that it is never rendered on the browser
- https://community.openproject.org/work_packages/42634

[#42634] do not use speaker icon for the notification items in the dashboard widget

---

.github/workflows/ci.yml

manly to fix CI errors like
`Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_4ee0518e-3de3-46ec-ba57-e6f2f1e0c587/8e211d25-6f5d-46fc-82eb-2d3937132f46.tar.gz. return code: 2.`
which I believe come from the v2 of the cache package

update github action packages

---

tests/jest/components/AdminSettings.spec.js

that gets rid of error output like `TypeError: Cannot read properties of undefined (reading 'data')` while running that test

mock request to the OP validation

---

src/components/AdminSettings.vue
tests/jest/components/AdminSettings.spec.js

if the openproject URL is not valid the input field gets marked red and receives the focus
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/42727

highlight & focus the OP instance input on invalid input

---

lib/Controller/OpenProjectAPIController.php
src/components/tab/EmptyContent.vue
src/views/Dashboard.vue
src/views/ProjectsTab.vue
tests/jest/components/tab/EmptyContent.spec.js
tests/jest/views/ProjectsTab.spec.js
tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap

`OP#42728` : https://community.openproject.org/projects/nextcloud-integration/work_packages/42728/activity
This PR make changes so that the connect button is not shown when the server is correctly set-up but offline.

[OP#42728]Don't show connect button if the server is correctly set-up but offline

---

lib/Service/OpenProjectAPIService.php
tests/lib/Service/OpenProjectAPIServiceCheckNotificationsTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

needs memory caching to be configured in NC, see https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
In case local or distributed cache is available the code will cache the responses for the status & type requests for 1h
@eneiluj I would need your suggestion here. Is that the way the caching should be implemented? I tried with APCu, memcached and Redis in those cases it seems to work

OP#42613 cache colors of statuses and types

---

src/utils/workpackageHelper.js
tests/jest/views/ProjectsTab.spec.js
tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap

additionally to #129 this caches the colors also in JS, so that if a color was already used it even does not need to be requested from the caching server
the cache will be invalidated on page reload, but not when moving into an other folder

OP#42613 cache colors of types and statuses in the frontedn

---

src/components/AdminSettings.vue

state variable should be used rather than the edit variable for the `saveOptions` fn.
was accidentally changed while admin settings refactoring

Use state variable for the save options request payload

---

appinfo/routes.php
lib/Controller/OpenProjectAPIController.php
src/components/OAuthConnectButton.vue
tests/jest/components/OAuthConnectButton.spec.js
tests/lib/Controller/OpenProjectAPIControllerTest.php

creating the PKCE code verifier and challenge in the frontend does not work reliable because the `crypto.subtle` only works in secure context see https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle
So in this PR I moved generating the state and the PKCE values into the backend that returns the complete URL to the frontend
should fix https://community.openproject.org/projects/nextcloud-integration/work_packages/details/42915

move generating OP OAuth URI to the backend

---

src/components/admin/TextInput.vue

copy to clipboard is only possible in secure context, see https://developer.mozilla.org/en-US/docs/Web/API/Clipboard
so in not secure contexts the user will have to copy manually
fixes, or avoids the problem of https://community.openproject.org/projects/nextcloud-integration/work_packages/42922

[OP#42922] only show copy button when copy to clipboard is possible

---

lib/Controller/ConfigController.php
lib/Dashboard/OpenProjectWidget.php
lib/Listener/LoadSidebarScript.php
lib/Settings/Personal.php
src/components/OAuthConnectButton.vue
src/components/PersonalSettings.vue
src/components/tab/EmptyContent.vue
src/utils.js
src/views/Dashboard.vue
src/views/ProjectsTab.vue
tests/jest/components/OAuthConnectButton.spec.js
tests/lib/Controller/ConfigControllerTest.php
tests/lib/Settings/PersonalTest.php

The journey to connect to OpenProject can be started from Dashboar, FilesPage or the personal settings, this PR brings the user back to where the journey was started.
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/42855

[OP#42855] redirect user back to where oauth journey was started

---

src/components/admin/TextInput.vue
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
tests/jest/components/admin/TextInput.spec.js
tests/jest/components/admin/__snapshots__/TextInput.spec.js.snap

**Description:** use a grey border for the input when set to `read-only` mode
**Related:** Should fix https://community.openproject.org/work_packages/42911
**Screenshots:**

[#42911] UI/UX improvements: use grey color for readonly input fields

---

lib/Dashboard/OpenProjectWidget.php
lib/Listener/LoadSidebarScript.php
lib/Settings/Personal.php
src/components/OAuthConnectButton.vue
src/components/PersonalSettings.vue
src/components/tab/EmptyContent.vue
src/views/Dashboard.vue
src/views/ProjectsTab.vue
tests/jest/components/OAuthConnectButton.spec.js
tests/jest/components/PersonalSettings.spec.js
tests/jest/components/__snapshots__/OAuthConnectButton.spec.js.snap
tests/jest/components/tab/EmptyContent.spec.js
tests/jest/components/tab/__snapshots__/EmptyContent.spec.js.snap
tests/jest/views/ProjectsTab.spec.js
tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap
tests/lib/Settings/PersonalTest.php

after https://github.com/nextcloud/integration_openproject/pull/146 there is no need anymore to have the requestUrl  in the front end. This PR removes the `requestUrl` from the front end that we used, to determine if we should show the connect button to the user or not. Now instead of `requestUrl` we rely on `adminConfigStatus`
[#OP42916]  : https://community.openproject.org/projects/nextcloud-integration/work_packages/42916/activity

[#OP42916] Remove requestUrl from front-end

---

appinfo/routes.php
lib/Controller/ConfigController.php
src/components/DirectDownload.vue
src/directDownload.js
templates/directDownload.php
tests/lib/Controller/ConfigControllerTest.php
webpack.js

OpenProject generates Nextcloud [direct download](https://docs.nextcloud.com/server/22/developer_manual/client_apis/OCS/ocs-api-overview.html#direct-download) links to let users get files linked with a work package.
There is an issue with this direct download endpoint in Nextcloud. It messes with cookies and refuses to be accessed when put in a link in OpenProject.
This is a workaround. This public page takes the download token and an arbitrary file name and shows a link to the direct download endpoint. For some reason it works fine.

Public direct download page

---

src/views/ProjectsTab.vue

If the user has selected an other file, stop processing the workpackages metadata

stop processing metadata on file change

---

src/views/Dashboard.vue

follow up of #122
usigng `false` generated this log output in the browser console:
```
[Vue warn]: Invalid prop: type check failed for prop "overlayIconUrl". Expected String, got Boolean with value false.
found in
---> <DashboardWidgetItem>
<DashboardWidget>
<Root>
```
according to the documentation https://github.com/nextcloud/nextcloud-vue-dashboard#all-props-1 it is optional, so delete it completely

delete overlayIconUrl property from Dashboard

---

lib/Service/OpenProjectAPIService.php
tests/lib/Service/OpenProjectAPIServiceTest.php

If we have saved the `oauth_instance_url` as `https://some-domain/` (with a trailing slash), the oauth URL constructed is like:
```js
return $oauthUrl .
'/oauth/authorize' .
'?client_id=' . $clientID .
'&redirect_uri=' . urlencode($redirectUri) .
'&response_type=code';
```
this results in URLs like this:
```
https://some-domain//oauth/authorize?...
```
The occurrence of double slash `//` after instance URL does not show the page error message on navigation. But it would be better to avoid such inconsistencies.

Remove trailing slash from OpenProject instance URL before constructing OAuth URL

---

lib/Service/OpenProjectAPIService.php
src/components/tab/SearchInput.vue
tests/jest/components/tab/SearchInput.spec.js
tests/lib/Service/OpenProjectAPIServiceTest.php

using the `typeahead` filter for the search has several advantages
1. we need only one request and not multiple
2. it also searches for WP ids (fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/43173/)
To make it possible to search also for short ids, the min input is one character
P.S. the global search also now searches for WP ids, but that still has a minimum input of 2 characters

[#43173] use 'typeahead' filter to search for WP

---

src/components/AdminSettings.vue
src/components/admin/TextInput.vue

There was a double sanitation from t() and dompurify.
This removes the t() one and tells dompurify to allow `target="_blank"`
fixes: https://community.openproject.org/projects/nextcloud-integration/work_packages/43168/github?query_id=3407

Fix link sanitation, allow target="_blank"

---

src/components/AdminSettings.vue
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap

- repharase reset button text to `Replace`
- use double arrow icon https://materialdesignicons.com/icon/autorenew

[Task/43200] update the `Reset`  button text to `Replace`

---

src/components/AdminSettings.vue
tests/jest/components/AdminSettings.spec.js

when the host was checked if it served an open project instance but the input was changed the data of the check also needs to be invalidated
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/43211

[#43211] reset OP host validity check

---

.gitignore
README.md
docker-compose.yml

using the host network resulted in port 80 being blocked on the docker host
the issue is that the NextCloud UI (from the users browser, most likely on the docker host) needs to reach OpenProject using the same URL as the NextCloud backend (fron inside the docker service)
this is now achieved by using `host.docker.internal`

[#43199] use host.docker.internal instead of network_mode: "host"

---

.github/workflows/ci.yml
lib/Controller/FilesController.php
tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
tests/acceptance/features/api/getFilesinfoByFileIDsAPI.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/lib/Controller/FilesControllerTest.php

use the activity app to get the latest modifier.
Only content changes of a file will be regarded as modifications, move, rename etc. not.
fields that are returned: `modifier_id` and `modifier_name`
In case the modifier could not be found (e.g. activity app is not installed, last modifier is deleted, public modified last, ...) `null` is returned
for details see API tests
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/43302

[#43302] show last modifier in files API

---

src/views/ProjectsTab.vue

There was an invert css leftover. Without this, the dark/light mode color should be ok.
Resolves: https://community.openproject.org/work_packages/43418

[#43418] Unlink icon button is dark in the dark mode

---

appinfo/routes.php
lib/Controller/ConfigController.php

Observed behaviour:
* when using basic auth with invalid credentials, the request does not reach the app controller and we get a 401 response with `{"message":""}` in the body
* successful basic auth: `{"user_id":"USER_ID","authorization_header":"Basic anVsaWVuOk9yYW4nZV9jbG91sA=="}`
* passing an invalid bearer token with `Authorization: Bearer INVALID_TOKEN`: we get `{"user_id":"","authorization_header":"Bearer INVALID_TOKEN"}`
* passing a valid token, we get `{"user_id":"USER_ID","authorization_header":"Bearer VALID_TOKEN"}`
https://community.openproject.org/wp/43473

New public endpoint returning the user id and the authorization header

---

src/components/tab/WorkPackage.vue
tests/jest/components/tab/__snapshots__/WorkPackage.spec.js.snap
tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap

check the contrast between the wp-type color and the background and set `-webkit-text-stroke` if the contrast is too little
1. if the workpackage is not listed yet, get the background color from the whole tab
2. if the workpackage is listed and an hover event happens, recalculate again
part of https://community.openproject.org/projects/nextcloud-integration/work_packages/43206
test-cases:
1. light theme and type color=white/light gray
before:
now:
3. dark theme and type color=black
before:
now:
4. high contrast mode and color=same as hover color of wp
before:
now:

calculate contrast for wp type and show border if low

---

tests/lib/Service/DirectDownloadServiceTest.php

the signature of DirectController has changed, see https://github.com/nextcloud/server/pull/32482
so need to adjust the tests

adjust tests to changes in DirectController in NC>=24

---

lib/Controller/ConfigController.php
lib/Service/OpenProjectAPIService.php
tests/lib/Service/OpenProjectAPIServiceTest.php

NC needs always to send index.php  in the redirect url, even if it runs currently without, because OP always expects the URLs to include index.php
this depends on https://github.com/opf/openproject/pull/11086

[#43473] add index.php always to the redirect URL

---

lib/Controller/FilesController.php
tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
tests/lib/Controller/FilesControllerTest.php

the default folder mimetype of NC is `httpd/unix-directory` see https://github.com/nextcloud/server/blob/8af40542379df1338a07ec1628147bb79a92be4f/lib/public/Files/FileInfo.php#L67 but in https://github.com/opf/openproject/pull/11109 OpenProject expects `application/x-op-directory`, so change the replace the mimetype

[#43550] rewrite folder mimetype to what OP expects

---

lib/Controller/FilesController.php
tests/lib/Controller/FilesControllerTest.php

alternative for #198
the code now loops though all mounts and tries to identify the mount of the owner, because we want to get the file name in the context of the owner
if for some reason that is not possible it falls back to return the file name in the context of the requester

harden getting mounts and fall back to requester context

---

README.md

I had issues with the integration as the host name configured on my instance was `localhost:3000` and did not match the host name `host.docker.internal:3000` configured on the Nextcloud side.
I added the instructions to use `host.docker.internal:3000` instead of `localhost:3000`.
Signed-off-by: Christophe Bliard <c.bliard@openproject.com>

Add information about OpenProject hostname setting

---

README.md

document a "simple" way to serve NC from a subfolder (`/html`) with the existing docker containers

[#43529] document serving NC from subfolder via docker

---

README.md

document how to release the app
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/42808

document release process

---

lib/Settings/Personal.php
lib/Settings/PersonalSection.php

Description: moved OpenProject personal settings to a dedicated category
Related issue: https://community.openproject.org/work_packages/43667
---

[#43667] move OP personal settings to own category

---

lib/Notification/Notifier.php

`app.svg` is white in the light mode and dark in the dark-mode, so its basically invisible in the notifications dropdown
`app-dark.svg` does the opposite
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/43843

OP#43843 fix app icon for notifications

---

src/components/PersonalSettings.vue
src/components/settings/CheckBox.vue
tests/jest/components/PersonalSettings.spec.js

- Enhance HTML/CSS for the personal settings section, more similar with other personal sections
- Use a component for the Checkbox Input so that can be reused inside admin settings for default personal configs
- Grouped the form items together
- Refactor unit tests
Part of https://community.openproject.org/projects/nextcloud-integration/work_packages/43669
###
Before:
After:
---

[OP#43669] Enhance html/css for the personal settings section

---

lib/Controller/OpenProjectAPIController.php
tests/lib/Controller/OpenProjectAPIControllerTest.php

when setting up the connection the first time, the app checks if there is an OpenProject instance listening on that URL.
If no OpenProject could be detected it would be helpful for the admin to know some details.
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/44143
Possible log outputs are:
<details><summary>1. server does not reply at all</summary>
```json
{
"reqId": "MewHTUNISn1qLuQTJqjd",
"level": 3,
"time": "2022-09-14T10:37:33+00:00",
"remoteAddr": "127.0.0.1",
"user": "admin",
"app": "integration_openproject",
"method": "POST",
"url": "/nextcloud-server/index.php/apps/integration_openproject/is-valid-op-instance",
"message": "Could not connect to the OpenProject URL 'http://localhost:3000'",
"userAgent": "Mozilla/5.0 (X11; Linux x86_64; …
```

[OP#44143] log errors when checking validity of OP URL

---

lib/Controller/FilesController.php
tests/lib/Controller/FilesControllerTest.php

Only use the trash manager if the files_trashbin app is enabled for the user.
Catch any exception when getting the trashManager, just in case.
https://community.openproject.org/wp/43936

Fix trashManager not found

---

.github/workflows/release.yml

Once this is merged, we can delete the "release" branch.
:warning: This commit needs to be in the branch which is then pushed in "auto-release", otherwise the action won't be triggered. Be careful because once merged, even if it's in master, it's not in any other branch.
If needed we can make other PRs bringing this change in other branches.

Use auto-release branch for automatic releases, drop the 'release' one

---

.github/workflows/ci.yml

the master branch on NC got bumped to version 26, the activity app does not support that. For now we should run the tests with the stable25 branch

run CI with stable25 branch of NC

---

css/dashboard.css
lib/Dashboard/OpenProjectWidget.php

Icon style was wrong for NC 25.
Here is a way to avoid the conditional class for the dashboard/files-app icon.
It works in NC 24 and 25 with darkmode enabled or disabled.
`.option-open-project > .icon-openproject,` fixes the right click menu style.

Simplify css and fix icon style for NC 25

---

src/components/AdminSettings.vue
src/components/admin/FieldValue.vue

OAuth ID and secret are technical terms that should be the same in all languages. Do not translate them.
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/44145

[OP#44145] do not translate oauth technical terms

---

.github/workflows/ci.yml
appinfo/info.xml

We can already bump the max NC version to let CI catch incompatibility issues ASAP.

Bump max NC version to 26, adjust CI action

---

tests/lib/Controller/FilesControllerTest.php

If  its not possible to get the filename in the context of the owner, the code falls back to return the filename in the context of the requester.
This case was untested so far, see #199 
So this PR adds a test for it

[OP#43671] test for when filename could not be found

---

lib/Controller/OpenProjectAPIController.php
lib/Service/OpenProjectAPIService.php
src/components/AdminSettings.vue
tests/jest/components/AdminSettings.spec.js
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
tests/lib/Controller/OpenProjectAPIControllerTest.php

In the setup phase URLs that are redirected should not be used. If an URL is redirected the admin should use the real URL
But if a sys-admin sets up a redirect after the configuration is done (e.g. for maintenance purposes) that redirect should be used and followed.
fixes https://community.openproject.org/work_packages/44493

[OP#44493] don't allow URLs that are redirected in the setup phase

---

lib/Service/OpenProjectAPIService.php
tests/lib/Service/OpenProjectAPIServiceTest.php

To make it easier for the user to find workpackages sort them only by date, showing those that have been changed recently on the top.
fixes https://community.openproject.org/work_packages/44504

[OP#44504] sort workpackages only by date

---

lib/Listener/LoadSidebarScript.php
src/views/ProjectsTab.vue
tests/jest/views/ProjectsTab.spec.js

I don't see a reason why we should query the backend to find out the OpenProject URL, it does not change for different files or workpackage connections. It is much cheaper to pass it in by a state and using it.
Also it solves the problem with Firefox blocking the `window.open()` request as popup. Because the `window.open()` call now comes directly after the user interaction, Firefox does not block it.
For more details of how Firefox handles popups see: https://support.mozilla.org/en-US/kb/pop-blocker-settings-exceptions-troubleshooting?redirectslug=Pop-up+blocker&redirectlocale=en-US
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/44482

 [OP#44482] pass in the OpenProject URL as state to the ProjectsTab

---

.github/workflows/ci.yml

**Description:** Started using `xdebug` for coverage analysis. The same is used for me in my local machine. Only `xdebug` or `pcov` is supported by https://github.com/shivammathur/setup-php#signal_strength-coverage-support. So after using the `xdebug` tool, the php code coverage are back.
**Related:** https://community.openproject.org/projects/nextcloud-integration/work_packages/44746
---

[ci] add `xdebug` for the phpunit tests coverage

---

lib/Controller/OpenProjectAPIController.php

without this change only admins are allowed to use the endpoint, this does not make sense and lead to https://github.com/nextcloud/integration_openproject/pull/256#issuecomment-1298094150

allow non admin user to mark notifications as read

---

src/components/tab/SearchInput.vue

There was a white _bg_ in the search bar while I was on the dark mode which I noticed while testing some other PR.
With this PR, the _hardcoded_ color values are cleaned so that the default NC _bg_ system will work in our search component.
Before:
After:
---

[css] remove the hard-coded color values or the search bar component

---

tests/lib/Service/OpenProjectAPIServiceTest.php

The local address checker was changed in https://github.com/nextcloud/server/pull/34852
This should not effect how we use it, because we only catch the exception, but the unit tests needed to be adjusted
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/44822

[OP#44822] fix unit tests failing because of changes in NC 26

---

.github/workflows/ci.yml

backport of https://github.com/nextcloud/integration_openproject/pull/264 to the release 2.1 branch

[backport][ci] add `xdebug` for the phpunit tests coverage

---

tests/lib/Service/OpenProjectAPIServiceTest.php

backport of #268 to `release/2.1` branch

[2.1] fix unit tests failing because of changes in NC 26

---

src/components/AdminSettings.vue
tests/jest/components/AdminSettings.spec.js

During `Oauth` configuration between 2 apps, even when admin has not configured any setting the `reset` button is enabled. This PR disable it until any of the configuration is set.
https://community.openproject.org/projects/nextcloud-integration/work_packages/44485/activity?query_id=3513
UI Before changes: When no setting is set by admin
UI After changes: When a setting is set by admin

[OP#44485]Enable Reset Button only when any integration setting is set by admin

---

lib/Listener/LoadSidebarScript.php

`provideInitialState` does not like it when the value is `null` and shows a log entry in that case. The fix is very simply, just initialize the variables with an empty string, that is anyway a good programming practice.

[OP#44934] initialize variables

---

docker-compose.yml

The compose setup was failing due the following dB issue:
```console
integration_openproject-db-1         | 2022-11-22 06:22:18.959 UTC [156] ERROR:  permission denied for schema public at character 14
integration_openproject-db-1         | 2022-11-22 06:22:18.959 UTC [156] STATEMENT:  CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))
```
The latest psql docker image has this bug and is well described in the nextcloud issue https://github.com/nextcloud/docker/issues/1845
As a solution we can pin v14 for the docker image and use the sound service.
Related Reddit thread: https://www.reddit.com/r/selfhosted/comments/y4klsz/help_with_a_new_install_of_nextcloud_on_docker/
---
Signed-off-by: Kiran Parajuli …

Use pgsql of version 14 to avoid permission errors in the compose setup

---

README.md

We also need the notifications app to use the integration app with all of the features.
This PR will add the informations about the notifications app installation and enabling.
---

Add informations about the notifications app on the NC server during dev. installation

---

src/components/admin/TextInput.vue
tests/jest/components/AdminSettings.spec.js
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
tests/jest/components/admin/__snapshots__/TextInput.spec.js.snap

This pr removes the `id` attribute from the input field, which will make it easier for the e2e tests https://github.com/nextcloud/integration_openproject/pull/265 to get better selectors

Remove the id attribute from the Text input for assistance in e2e tests

---

lib/Controller/ConfigController.php
lib/Service/OauthService.php
tests/lib/Controller/ConfigControllerTest.php

The current code does the oauth client deletion the same way as it is done in the NC code
compare https://github.com/nextcloud/integration_openproject/blob/master/lib/Service/OauthService.php#L113-L119 with https://github.com/nextcloud/server/blob/master/apps/oauth2/lib/Controller/SettingsController.php#L93-L96
This PR lets the NC code handle the deleting and together with https://github.com/nextcloud/server/pull/35094 it is an alternative to #261 and will fix https://community.openproject.org/projects/nextcloud-integration/work_packages/44727

[OP#44727] let NC delete the OAuth client

---

css/dashboard.css

In version 24 of the nextcloud, the spacing was missing  between the OpenProject and bell icon so this PR fixes that
The bell icon doesn't have spacing in current master either so it's fixed there too 
Related work package: https://community.openproject.org/projects/nextcloud-integration/work_packages/44889/activity

[OP#44889] Add spacing in bell icon in dashboard

---

src/views/Dashboard.vue
tests/jest/fixtures/notificationsResponse.json
tests/jest/views/__snapshots__/Dashboard.spec.js.snap

from the version 12.4 OpenProject sends out notifications based on the dates set in the WP. This PR supports those notifications now. Before date notifications broke the dashboard and would display wrongly in the notifications app, because they don't have a actor.
For now the dashboard shows a `?` if there is no actor, after #254 we can use a calendar icon for that
To test date based notifications this command can be used to generate them :
`rails runner 'Notification.create(recipient: User.find_by(lastname: "[LASTNAME OF USER TO CREATE NOTIFICATION FOR]"), reason: :[REASON], resource: WorkPackage.find([SOME ID]), project: WorkPackage.find([SOME SAME ID]).project)'`
valid values for `reason` are: `date_alert_start_date`, `date_alert_due_date` and `date_alert_date`

[OP#42323] support dateAlert notifications from OP

---

lib/Service/OpenProjectAPIService.php
tests/lib/Service/OpenProjectAPIServiceTest.php

Without setting anything in the request URL the pageSize will be whatever is set in Administration=>System Settings=>General as	`Objects per page options`
Setting it to `-1` should solve the problem described in https://community.openproject.org/work_packages/42323/activity#activity-40

[OP#42323] set pageSize for notifications to 'unlimited'

---

src/components/AdminSettings.vue

Related work-package: [OP#44486](https://community.openproject.org/projects/nextcloud-integration/work_packages/44486/activity?query_id=3513)
In firefox when the browser was in a dark theme the text in the button were not readable
This PR removes the hard-coded color so that the nextcloud default color is used which works across all the browsers and themes

[OP#44486] Remove the hard coded color from button text

---

src/views/Dashboard.vue
tests/jest/views/__snapshots__/Dashboard.spec.js.snap

The strings for the reasons of notifications have been different in NC and OP because for most cases NC just showed what the API delivered. This PR changes the known strings and rewrites them to be the same as in OP
fixes https://community.openproject.org/notifications/details/45409

[OP#45409] rewrite the reason strings to be the same as in OP

---

lib/Controller/ConfigController.php
tests/lib/Controller/ConfigControllerTest.php

Revocation of the OAuth credentials on openProject side was triggered whenever the admin changed the default settings, This PR fixes that issue.
OP#45462 Related work package https://community.openproject.org/projects/nextcloud-integration/work_packages/45462/github?query_id=3513

[OP#45462]Fix revocation while the default settings changed

---

README.md
appinfo/info.xml
appinfo/routes.php
lib/Controller/DirectUploadController.php
lib/Migration/Version2002Date20221219170111.php
lib/Migration/Version2300Date20221219170111.php
lib/Service/DirectUploadService.php
tests/acceptance/features/api/directUploadPrepare.feature

Related work-package: [OP#45465] https://community.openproject.org/projects/nextcloud-integration/work_packages/45465/activity?query_id=3504
This PR adds a new endpoint `/direct-upload` that tests the parameter `folder_id`, for the preparation of the direct upload.
The added endpoint will return the `token` that can be used for direct upload and `expires_on` which is the expiration time of the token.
The end-point can be tested with:
```console
curl -u USER:PASSWD http://<nextcloud_host>/index.php/apps/integration_openproject/direct-upload?folder_id=<folder_id>
```

[OP#45465] Feature/prepare direct upload api

---

.github/workflows/ci.yml

We were having a `Segmentation fault  (core dumped)` error in CI upon using the `2.23.0` tag of `setup-php` instead of `v2` the problem doesn't occur. `2.23.0` is the latest version now. 
Related work package : [OP#45551] https://community.openproject.org/projects/nextcloud-integration/work_packages/45551

[OP#45551] use `shivammathur/setup-php@2.23.0` instead of `shivammathur/setup-php@v2`

---

src/views/Dashboard.vue

All possible strings need to be mentioned so that transifex picks them up correctly and translates them.
This should finally fix https://community.openproject.org/projects/nextcloud-integration/work_packages/45399

mention all notification reasons

---

lib/Controller/OpenProjectAPIController.php
lib/Service/OpenProjectAPIService.php
tests/lib/Service/OpenProjectAPIServiceTest.php

This PR fixes the fetching of avatars from openproject.
The problem was that we had the wrong userId in `getOpenProjectAvatar`, the id given was the openproject id, but we tried to use it to read the token from the NC database.
Now we passing also in the NC userId to read the token and the openproject userId is used to generate the openproject URL to get the avatars from there as before.

[OP#45596] fix fetching avatars from openproject

---

lib/Dashboard/OpenProjectWidget.php
lib/Listener/LoadSidebarScript.php
lib/Settings/Personal.php

Set the defaults to an empty string to avoid ugly log outputs.
Fixes https://community.openproject.org/work_packages/45596

[OP##45596] set defaults for oauth connection message&result

---

integration_setup.sh

- use OP username&pwd in check-state request - this request might also be password protected
- use  to determine the status of NC - it's saver to use status.php URL, as cron.php might be disabled and status.php is there for this purpose

hardening and improve of integration script

---

appinfo/info.xml
lib/Migration/Version2300Date20221219170111.php
lib/Migration/Version2310Date20230116153411.php
lib/Service/DatabaseService.php

We made a table `directUpload` for the `direct-upload` API which worked for the current nextcloud master i.e `nextcloud-26` as it's stored as `oc_directUpload` in the database. But in nextcloud 25 and probably below the table is stored as `oc_directupload` without camelcase in the database so the request for `direct-upload` threw exceptions as the code is searching for `directUpload` to perform the operations. This PR renames the table to `direct_upload` so that the aforementioned problem doesn't occur and also bumps the version of the app from `2.3.0` to `2.3.1` for this change to take place.
In case the system went through the migration step `2.3.0` and created the database `directUpolad` or `directupload` depending upon the version of the nextcloud , the pre-existing table will be …

Rename the direct upload table

---

README.md
lib/Controller/DirectUploadController.php
lib/Service/DatabaseService.php
tests/acceptance/features/api/directUpload.feature
tests/lib/Controller/DirectUploadControllerTest.php

related work package [OP#45464] : https://community.openproject.org/projects/nextcloud-integration/work_packages/45464
**Direct upload with overwrite parameter**:
The overwrite parameter can be either set to `true` or `false`.
1. **overwrite set to false**: 
If the parameter is set to `false` and a file with the name already exists, a new file will be uploaded with existing name having a number suffix.
```console
curl-X POST 'http://<nextcloud_host>/index.php/apps/integration_openproject/direct-upload/<token>' \
--form 'file=@"<path-of-file>"' --form 'overwrite="false"' -H'Content-Type: multipart/form-data' 
```
The response from the above curl request will be
```json
{
"file_name": "<file_name>(some-number)",
"file_id": <file_id>
}  
```
2. **overwrite set to true**:
If the parameter is …

[OP#45464] Feature/direct upload api overwrite

---

lib/Controller/DirectUploadController.php
tests/acceptance/features/api/directUpload.feature
tests/acceptance/features/bootstrap/DirectUploadContext.php
tests/acceptance/features/bootstrap/FeatureContext.php
tests/lib/Controller/DirectUploadControllerTest.php

Check for free quota on that particular folder before writing a file.
There is still the chance of a race-condition. e.g. while we are writing data an other client also writes and together we run out of quota, no idea how we could avoid that.
part of https://community.openproject.org/projects/nextcloud-integration/work_packages/45849

[OP#45849] check quota before writing file

---

lib/Controller/DirectUploadController.php
lib/Exception/OpenprojectFileNotUploadedException.php
tests/lib/Controller/DirectUploadControllerTest.php

~~on top of #325~~
This case happens when the uploaded file is bigger than upload_max_filesize.
In that case return a 413 HTTP code and show what the max upload size is.

[OP#45849] report error when file was not uploaded

---

lib/Controller/DirectUploadController.php
tests/acceptance/features/api/directUpload.feature
tests/acceptance/features/bootstrap/SharingContext.php

When the there is no permission to create anything in the folder, return the correct error. But in the case of an overwrite the update permissions are enough.

[OP#45849] when uploading the file check permissions correctly

---

lib/Controller/DirectUploadController.php
tests/lib/Controller/DirectUploadControllerTest.php

The InvalidContentException is thrown by the files_antivirus app. So catch it and return the same error code that the DAV endpoint would return if a virus is detected.

[OP#45897] check for exception that is thrown by files_antivirus

---

docker-compose.yml

Having the apache config in a volume has the advantage that when the configuration is changed it will not be reset on `docker compose down/up`

put apache config into a volume

---

lib/Controller/DirectUploadController.php
tests/lib/Controller/DirectUploadControllerTest.php

~~On top of #334~~
When returning a 500 error, we want to catch all possible exceptions, not only the DB exceptions.
Whatever bad thing happens, it should be caught and properly reported.

[OP#45897] catch \Exception not OCP\DB\Exception

---

appinfo/info.xml

bump version to 2.2.1 because the build of 2.2.0 failed see https://github.com/nextcloud/integration_openproject/actions/runs/4015405945

bump version to 2.2.1

---

lib/Controller/DirectUploadController.php

Check early if `$directUploadFile` is an array or not. Effectively this is also checked in `scanForInvalidCharacters` but after trying to access the array and that produces a log output like: `"message": "Trying to access array offset on value of type null at /home/artur/www/nextcloud-server/custom_apps/integration_openproject/lib/Controller/DirectUploadController.php#150",`
How to test:
1. set log-level to at least "error"
2. run API test `directUpload.feature:66`
3. check the log file (the mentioned message appears before the fix but not after)

check empty filename

---

.github/workflows/ci.yml
tests/acceptance/features/bootstrap/FeatureContext.php

The bug that made #320 necessary was not discovered by the tests, because the tests never run with pqsql.
This PR runs the API tests in a separate job and uses real (mysql,pgsql) databases for that.
~~currently blocked by https://github.com/juliushaertl/nextcloud-docker-dev/issues/142~~

seperate API tests and run them on different DB

---

lib/Controller/DirectUploadController.php
tests/acceptance/features/api/directUpload.feature
tests/lib/Controller/DirectUploadControllerTest.php

related work package OP#45941 : https://community.openproject.org/projects/nextcloud-integration/work_packages/45941/activity
This PR
1. Adds API test
2. moves the `getTokenInfo` function call at the beginning as the token is deleted when this function is called. Previously, the token was usable if the request failed before it reached this function and we don't want that since the token is one-time only.

[OP#45941] Add more api tests for direct upload feature

---

css/dashboard.css

1. Download and enable `talks` app of nextcloud while the integration app is also enabled
Whenever our app and another app that uses the Dashboard widget are enabled, the dashboard items were placed outside for other apps because of the CSS removed in this PR. As the CSS is doing changes to the dashboard widget element it'll be applied for all the apps with dashboard widgets that are enabled along with this app.
This PR fixes that problem. 
[OP#45952] - https://community.openproject.org/projects/nextcloud-integration/work_packages/45952/activity

[OP#45952] Fix the dashboard item not aligning properly

---

lib/Listener/LoadSidebarScript.php

If the administrator limits the app to specific groups, don't show the OpenProject tab in the files details sidebar.
The limitation seems to work out of the box for all other places:
- user settings
- dashboard
- search
- navigation link
- APIs
fixes https://community.openproject.org/work_packages/45928

[OP#45928] hide the tab if the app is limited to specific groups

---

.github/workflows/ci.yml
appinfo/info.xml

Nextcloud master branch got renamed to version 27 https://github.com/nextcloud/server/commit/87f103dc6c4cf86e0e128ed9379f77f373034342
So we need to test against stable26 branch and enable support for NC 27

support NC 27

---

src/components/AdminSettings.vue

fixes: https://github.com/nextcloud/integration_openproject/issues/362
Related workpackage [OP#46668]: https://community.openproject.org/projects/nextcloud-integration/work_packages/46668
The first half of this string is available but the second half is not available in the Transifex 
https://github.com/nextcloud/integration_openproject/blob/216d6ca4d9d513392b0dd2e5c2d1f155fbff3b7a/l10n/de.json#L46
Here it's mentioned https://docs.nextcloud.com/server/stable/developer_manual/basics/front-end/l10n.html#improving-your-translations
> You shall never split sentences and never concatenate two translations (e.g. “Enable” and “dark mode” can not be combined to “Enable dark mode”, because languages might have to use different cases)! Translators lose the context and they have no chance to …

[OP#46668] Make the translation string inline

---

lib/Controller/DirectUploadController.php
tests/acceptance/features/api/directUpload.feature

In the case when the max_post_size of PHP is exceeded the `$directUploadFile` variable is empty, because no data is actually forwarded to the code, so return HTTP 413 for that.
The same happens when a completely empty file-name is send, sadly we cannot distinguish both cases :-(
For the code actually even to get there and to be able to throw this exception and catch it later `display_errors` need to be set to `Off` in the php.ini

[OP#46349] return HTTP 413 if max_post_size is exceeded

---

.github/workflows/ci.yml
lib/AppInfo/Application.php
lib/Controller/ConfigController.php
lib/Exception/OpenprojectGroupfolderSetupConflictException.php
lib/Listener/BeforeNodeInsideOpenProjectGroupfilderChangedListener.php
lib/Service/OpenProjectAPIService.php
tests/acceptance/config/behat.yml
tests/acceptance/features/api/setup.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/GroupfoldersContext.php
tests/lib/Controller/ConfigControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

Related workpackage OP#46179: https://community.openproject.org/projects/nextcloud-integration/work_packages/46179/activity

[OP#46179] create openproject group folder

---

lib/Search/OpenProjectSearchProvider.php

This Pr sanitizes the `openproject_instance_url` so that  the links don't have extra `/`
Related work package: https://community.openproject.org/projects/nextcloud-integration/work_packages/47205/activity

[OP#47205] Sanitize the openproject instance url for global search

---

lib/Controller/FilesController.php
tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
tests/acceptance/features/api/getFilesinfoByFileIDsAPI.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/lib/Controller/FilesControllerTest.php

Related workpackages:
- [OP#47266] - https://community.openproject.org/projects/nextcloud-integration/work_packages/47266/activity
- [OP#47260] - https://community.openproject.org/projects/nextcloud-integration/work_packages/47260

Make files-info endpoint return path and permissions of the file

---

lib/Controller/DirectUploadController.php
lib/Exception/OpenprojectUnauthorizedUserException.php
lib/Service/DirectUploadService.php
tests/lib/Controller/DirectUploadControllerTest.php

Currently we're checking quota like this
```php
$freeSpace = $folderNode->getFreeSpace();
// this is also true if we try to overwrite
// to overwrite a file we need enough free quota for the new data
// otherwise `putContent()` fails
if ($directUploadFile['size'] > $freeSpace) {
throw new NotEnoughSpaceException('insufficient quota');
}
```
But since there's a possibility that the function getFreeSpace might return a negative
https://github.com/nextcloud/server/blob/b1abc57c07a61b5a0557395d86c3e31486a96c23/lib/public/Files/FileInfo.php#L52
https://github.com/nextcloud/server/blob/b1abc57c07a61b5a0557395d86c3e31486a96c23/lib/public/Files/FileInfo.php#L57
https://github.com/nextcloud/server/blob/b1abc57c07a61b5a0557395d86c3e31486a96c23/lib/public/Files/FileInfo.php#L62
So treat a negative …

[OP#47630] Check if free space is a positive value

---

tests/lib/Service/OpenProjectAPIServiceTest.php

Related workpackage: [OP#47849] https://community.openproject.org/projects/nextcloud-integration/work_packages/47849/github?query_id=3714
There was some refactoring done in the nextcloud server[master branch] by PR https://github.com/nextcloud/server/pull/37596 that changed some of the function calls so we needed to mock them in the order that they are called to make tests pass. Since these changes were added only to the master (nc-27), other versions need to work with the previous setup. So this PR
1. Mocks the functions needed for the master
2. separates the mocks according to versions

[OP#47849]Fix unit test failing on CI

---

.github/workflows/ci.yml
.github/workflows/release.yml

This PR 
1. updates GitHub actions packages.
2. According to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/  `save-state` and `set-output` are deprecated so update to write to the new `GITHUB_STATE` and `GITHUB_OUTPUT` environment files
3. Use the `concurrency` step provided by GitHub to cancel the concurrent workflow on the same PR
https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
Related workpackage [OP#47509]: https://community.openproject.org/projects/nextcloud-integration/work_packages/47509

[OP#47509]Update github actions packages

---

.github/workflows/ci.yml
.github/workflows/release.yml

This PR
1. updates GitHub actions packages.
2. According to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ save-state and set-output are deprecated so update to write to the new GITHUB_STATE and GITHUB_OUTPUT environment files
3. Use the concurrency step provided by GitHub to cancel the concurrent workflow on the same PR
https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
4. `actions/create-release` and `actions/upload-release-asset` repos are no longer maintained https://github.com/actions/create-release/issues/119 https://github.com/actions/upload-release-asset/issues/78 so shift to https://github.com/softprops/action-gh-release for release process …

[OP#47869]Update github actions packages 

---

.github/workflows/release.yml

In the recent release we got an error https://github.com/nextcloud/integration_openproject/actions/runs/4871023942/jobs/8687484590
Since we recently updated the github packages in https://github.com/nextcloud/integration_openproject/pull/395 , these changes were not tested against the release workflow. This PR hopefully fixes that

Add tag name in the upload artifacts

---

lib/Service/OpenProjectAPIService.php
tests/lib/Service/OpenProjectAPIServiceTest.php

The API tests were failing in CI and locally with 
```
"Too few arguments to function OCA\\GroupFolders\\Folder\\FolderManager::__construct(), 1 passed in /home/swikriti/www/nextcloud/master/apps/integration_openproject/lib/Service/OpenProjectAPIService.php on line 963 and exactly 4 expected in file '/home/swikriti/www/nextcloud/master/apps/groupfolders/lib/Folder/FolderManager.php' line 50",
```
There was a new beta release of the group folders app https://github.com/nextcloud/groupfolders/releases/tag/v15.0.0-beta1 
Seems like there were certain updates in FolderManager class in the latest version that added new values in the constructor. As these changes were made in the latest version of the app, they should only be supported by the latest master. This PR adds the new required …

[op#48127]Add new params as required by the constructor of FolderManager class

---

tests/acceptance/features/api/directUpload.feature
tests/acceptance/features/api/directUploadPrepare.feature
tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
tests/acceptance/features/api/getFilesinfoByFileIDsAPI.feature
tests/acceptance/features/api/setup.feature
tests/acceptance/features/bootstrap/FeatureContext.php

In test we clear user before we make them but we don't clear it in the after scenario.
In this PR we remove the user's in the after scenario as well. 
We have noticed some of the flaky tests in the CI https://github.com/nextcloud/integration_openproject/actions/runs/4911413323/jobs/8770565064
User `alice`  is created by default when the docker container is started https://github.com/juliushaertl/nextcloud-docker-dev/blob/d63dd0b14516e531714844c33421c7be24689b09/docker/bin/bootstrap.sh#L296
And since we're also creating user with the same name maybe the tests are getting confused. This PR changes all the occurrences of user `Alice` to user `Carol`. I think it's better to not use `Alice` user in tests
Related workpackage [OP#48128]: …

[OP#48128] Don't use user Alice in tests and delete user in after scenario

---

.github/workflows/ci.yml
src/views/ProjectsTab.vue

This PR https://github.com/juliushaertl/nextcloud-docker-dev/pull/189 made the auto retry of app installation default to 0 so we add the environment variable to `120`.

Add environment variable for retrying auto installation

---

.github/workflows/ci.yml
appinfo/info.xml

The Nextcloud server is now `28` https://github.com/nextcloud/server/blob/master/version.php
so we add support for `28` 
needs https://github.com/nextcloud/groupfolders/pull/2393 to be merged first

Add support for nextcloud master

---

lib/Search/OpenProjectSearchProvider.php
lib/Service/OpenProjectAPIService.php
tests/lib/Service/OpenProjectAPIServiceTest.php

Related work package [OP#48255] : https://community.openproject.org/projects/nextcloud-integration/work_packages/48255
Currently, the global search of the nextcloud search only searches for the work packages that are linkable by the user. This PR fixes it to return all the work packages that are available to the user
needs https://github.com/nextcloud/integration_openproject/pull/410 to be merged first

[OP#48255]Fix global search to display all the work packages available to the user

---

lib/Listener/BeforeNodeInsideOpenProjectGroupfilderChangedListener.php
lib/Service/OpenProjectAPIService.php
tests/lib/Service/OpenProjectAPIServiceTest.php

Using the storage and the userfolder to check the groupfolder configuration seems to be bridle, because the user called OpenProject might not be completely finalized (first login not done) when we call this check. We didn't manage to finalize the login programmatically in a way, so that the groupfolders app would create the mounts etc, sometimes we are getting lock exceptions.
But luckily we don't need to rely on the userfolder, all the checks that we want, we can do through the `groupFolderManager`
This PR changes the code so that we have one function that checks:
- if the group names OpenProject is managing a folder called OpenProject
- if the permissions are set correctly
- if the ACL is enabled and can be managed by the user OpenProject
It also renames the function to make clear what …

improve check if the groupfolder is setup correctly

---

lib/Controller/ConfigController.php
lib/Listener/BeforeNodeInsideOpenProjectGroupfilderChangedListener.php
lib/Service/OpenProjectAPIService.php
tests/acceptance/features/api/setup.feature
tests/lib/Controller/ConfigControllerTest.php

Relying on the fileID might be problematic because the admin might have deleted the OpenProject groupfolder and recreated it, in that case the fileID would have changed, but we would not know about it

rely on foldername not fileID for delete protection of project folders

---

lib/Search/OpenProjectSearchProvider.php
lib/Service/OpenProjectAPIService.php
tests/lib/Service/OpenProjectAPIServiceTest.php

Related work package [OP#48255] : https://community.openproject.org/projects/nextcloud-integration/work_packages/48255
Currently, the global search of the nextcloud search only searches for the work packages that are linkable by the user. This PR fixes it to return all the work packages that are available to the user
Backport: https://github.com/nextcloud/integration_openproject/pull/411

[OP#48255][Backport]Fix global search to display all the work packages available to the user 

---

.github/workflows/ci.yml

1.The php gd extension is required for the CI and also extension sqlite3 is need in order to install nextcloud in sqlite to run unit tests. This PR adds those modules. Other wise CI gives error like below:
```
PHP module GD not installed.
Please ask your server administrator to install the module.
An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /home/runner/actions-
```
2. Also this PR authenticates to docker in the CI to increase the limit of the image pull for different services in the github actions workflow. Other wise CI gives error like below:
```
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Error: …
```

Installed additional module, authenticated docker hub for more image pull

---

.github/workflows/ci.yml
README.md
appinfo/info.xml
appinfo/routes.php
integration_setup.sh
lib/Controller/ConfigController.php
lib/Controller/OpenProjectAPIController.php
lib/Migration/Version2400Date20230504144300.php
lib/Service/OpenProjectAPIService.php
lib/Settings/Admin.php
src/components/AdminSettings.vue
src/components/admin/FieldValue.vue
src/components/admin/FormHeading.vue
src/components/admin/GroupFolderError.vue
src/components/admin/ProjectFolderError.vue
src/utils.js
tests/acceptance/features/api/setup.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/jest/components/AdminSettings.spec.js
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
tests/lib/Controller/ConfigControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

This PR implements:
- Group folders setup form (UI and API)
- App password form (UI and API)
- Adds UI unit tests
- Adds API tests
- Adjust `/setup` endpoint to setup whole integration
Related WorkPackage:
https://community.openproject.org/projects/nextcloud-integration/work_packages/46179/activity?query_id=3787
https://community.openproject.org/projects/nextcloud-integration/work_packages/46178/activity?query_id=3787

[OP#46179 & OP#46178]Implement project folders and app password (UI and API)

---

src/components/AdminSettings.vue

Fixed the related bug when `app password` and `NC oauth` filed is in edit mode that enables the project folder to edit mode.
https://community.openproject.org/projects/nextcloud-integration/work_packages/48460/activity?query_id=3714

[OP#48460]Do not show project folder when app password is in Edit mode

---

src/components/OAuthConnectButton.vue
tests/jest/components/OAuthConnectButton.spec.js
tests/jest/components/__snapshots__/OAuthConnectButton.spec.js.snap
tests/jest/views/ProjectsTab.spec.js
tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap

Related workpackage[OP#48397] : https://community.openproject.org/projects/nextcloud-integration/work_packages/48397
In the personal section of a user, if the user is an admin, show them navigation to the admin settings if the setup seems to be not complete. For the normal user the message is not changed.

[OP#48397]Show navigation link to admin if integration setup is not done

---

.php-cs-fixer.dist.php
lib/AppInfo/Application.php
lib/Listener/OpenProjectReferenceListener.php
lib/Reference/WorkPackageReferenceProvider.php
lib/Search/OpenProjectSearchProvider.php
lib/Service/OpenProjectAPIService.php
phpstan.neon
src/reference.js
src/views/WorkPackageReferenceWidget.vue
webpack.js

This is just the structure, the provider and the widget do nothing at the moment.
This requires https://github.com/nextcloud/integration_openproject/pull/380 as the widget registration function appeared recently in `@nextcloud/vue` and the latest `@nextcloud/webpack-vue-config` is required.
The registration of the reference provider and of the widget only happen on NC >= 26.
The reference system is documented there: https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/reference.html
The reference provider has 2 goals:
* Add a smart picker provider so users can get work package links
* Resolve and render work package link previews
There are 2 ways to implement a smart picker provider. This PR implements the first one.
1. Just use a unified search provider and let the …

[OP#48106] Add a reference provider and a reference widget for work packages

---

.github/workflows/ci.yml
composer.json
composer.lock
lib/Controller/ConfigController.php
lib/Controller/FilesController.php
lib/Listener/BeforeGroupDeletedListener.php
lib/Listener/BeforeNodeInsideOpenProjectGroupfilderChangedListener.php
lib/Listener/BeforeUserDeletedListener.php
lib/Listener/LoadSidebarScript.php
lib/Listener/OpenProjectReferenceListener.php
lib/Listener/UserChangedListener.php
lib/Reference/WorkPackageReferenceProvider.php
makefile
psalm.xml
tests/acceptance/features/bootstrap/DirectUploadContext.php
tests/acceptance/features/bootstrap/FeatureContext.php
tests/lib/Controller/OpenProjectAPIControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

Related work packages:
1. https://community.openproject.org/projects/nextcloud-integration/work_packages/48849
2. https://community.openproject.org/projects/nextcloud-integration/work_packages/48842
3. https://community.openproject.org/projects/nextcloud-integration/work_packages/48861
**1.** The type of `data`  that we pass to `DataResponse()` was changed to `psalm-type` `DataResponseType` recently
https://github.com/nextcloud/server/blob/5d9d37e2c5d928288220d17160e9b6e29f064eb8/lib/public/AppFramework/Http/DataResponse.php#L34
The `phpstan` was complaining because it doesn't understand this type and is treating it as `class` which it can't find. In order to fix this issue this PR uses `pslam` as static code analysis tool for `master` branch of `nextcloud` 
> Note that this change was …

[OP#48849] Use psalm as static code analysis tool for nextcloud master / fix phpunit tests / fix op user can be disabled

---

src/components/tab/EmptyContent.vue
src/views/Dashboard.vue
src/views/ProjectsTab.vue

[OP#48744] : https://community.openproject.org/projects/nextcloud-integration/work_packages/48744

[OP#48744] Show proper error message when the openproject server is not reachable

---

README.md
package.json
src/components/AdminSettings.vue
src/components/OAuthConnectButton.vue
src/components/settings/SettingsTitle.vue
testplan.md
tests/jest/components/AdminSettings.spec.js
tests/jest/components/__snapshots__/OAuthConnectButton.spec.js.snap
tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap

Part of: https://community.openproject.org/projects/nextcloud-integration/work_packages/49038
As `OpenProject Integration` is the name of the app co it should start with upper case. There were places where this naming pattern wasn't followed so this PR fixes that.

[OP#49038] Refactor the name of the project to follow upper camel case

---

lib/Reference/WorkPackageReferenceProvider.php
lib/Service/OpenProjectAPIService.php
src/components/PersonalSettings.vue
src/utils/workpackageHelper.js
src/views/ProjectsTab.vue
src/views/WorkPackageReferenceWidget.vue

Related workpackage: https://community.openproject.org/projects/nextcloud-integration/work_packages/48106/activity
The smart picker
The link previews are as so
1. Setup openproject to work with `https` https://www.openproject.org/docs/development/localhost-ssl/
2. Enable nextcloud talk app or text app
3. Enable global search for workpackages
4. the smart picker can be triggered by `/` command in talk chat or text editor
> Note: you might need to import the self signed certificate to nextcloud which can be done using 
```
sudo -u www-data ./occ security:certificates:import <path-to-certificate>
```

[OP#48106] link previews UI implementation

---

lib/Reference/WorkPackageReferenceProvider.php
lib/Search/OpenProjectSearchProvider.php

Related workpackage: https://community.openproject.org/projects/nextcloud-integration/work_packages/48106/activity
Previously, the link previews were only displayed when the user `enables the global search for workpackages` settings. We decided that the links previews should be enabled by default so this PR removes that codependency.
https://github.com/nextcloud/integration_openproject/assets/41103328/62f2dc36-7b14-4ecc-ab3f-527bbd116d67

[OP#48106] Enable links preview even when the global search for workpackages is not enabled

---

src/components/AdminSettings.vue
src/components/admin/FormHeading.vue

This PR fixes the form heading index coloring in the dark theme which was a more not visible in the UI.
https://community.openproject.org/projects/nextcloud-integration/work_packages/49182/activity

[OP#49182]Change the form heading index for dark theme

---

lib/Controller/OpenProjectAPIController.php
src/components/tab/EmptyContent.vue
src/views/Dashboard.vue
tests/lib/Controller/OpenProjectAPIControllerTest.php

Related work package [OP#48843] - https://community.openproject.org/projects/nextcloud-integration/work_packages/48843
We have our own `EmptyContent` component but in the dashboard, we were using Nextcloud's one. So in this PR, I made the necessary changes to use our `EmptyContent` component everywhere.  
We were also throwing `400` for when the user didn't have the `access token` to OpenProject but that's not the right status code in this case so this PR changes the status code to `401`

[OP#48843] Use the empty content component of this repo 

---

integration_setup.sh

This PR updates the integration script to be able to save the user application password to open project.
Now with this update in script, we can integration either with project folders or without project folders.
https://community.openproject.org/projects/nextcloud-integration/work_packages/48445/activity?query_id=3787

[OP#48445]Update integration script to save user app password

---

.github/workflows/ci.yml
README.md
appinfo/info.xml

Related work package: https://community.openproject.org/projects/nextcloud-integration/work_packages/49381
As a general rule, Nextcloud Enterprise always supports the last three major releases. That might be longer than the non-entprise releases. As nextcloud 26 is released we can drop support for nextcloud 23

[OP#49381] drop support for nc 23

---

.github/workflows/ci.yml
appinfo/info.xml
lib/Service/OauthService.php
src/components/AdminSettings.vue
tests/acceptance/features/api/setup.feature
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap

The server implemented the feature to encrypt the oauth client secret in https://github.com/nextcloud/server/pull/38398 
but these changes were not adapted to our app so the OAuth connection wasn't successful from the open project side.
As this feature is only available from the nextcloud `25.0.8` there's a check to ensure the version of the server.
OP#49416 - https://community.openproject.org/projects/nextcloud-integration/work_packages/49416

Encrypt the oauth client secrets

---

lib/Listener/BeforeGroupDeletedListener.php
lib/Listener/BeforeUserDeletedListener.php
lib/Listener/UserChangedListener.php

Related workpackage[OP#49133]: https://community.openproject.org/work_packages/49133
We are protecting user/group Openproject from being deleted/disabled but the error message displayed is `An error occurred during the request. Unable to proceed` which is vague. So show proper error messages so that it's known that this user is protected.
In this PR, we let the user know that the OP user/group is protected and redirect them towards open project troubleshooting docs for further information
The error message displayed now is

[#49133] throw better error message when admin tries to delete/disable OP user/group

---

.github/workflows/ci.yml
lib/Service/OauthService.php
src/components/AdminSettings.vue
tests/acceptance/features/api/setup.feature
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap

The server implemented the feature to encrypt the oauth client secret in https://github.com/nextcloud/server/pull/38398 
but these changes were not adapted to our app so the OAuth connection wasn't successful from the open project side.
As this feature is only available from the nextcloud 
- `>= 25.0.8`
- `>= 26.0.4`
- `>= 27.0.1`
So the necessary check to ensure the version of the server is made.
Also the client secret is displayed only once now, right after it's created. 
OP#49416 - https://community.openproject.org/projects/nextcloud-integration/work_packages/49416

[OP#49416] Encrypt the OAuth2 client secrets

---

jest.config.js
src/components/tab/SearchInput.vue
tests/jest/components/tab/SearchInput.spec.js
tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap

This PR replaces the deprecated version of `NcMultiSelect` to `NcSelect` nextcloud-vue component.
https://community.openproject.org/projects/nextcloud-integration/work_packages/49295/activity?query_id=3787

[OP#49295]Change NCMultiselect to NcSelect

---

lib/Controller/OpenProjectAPIController.php
lib/Listener/OpenProjectReferenceListener.php
lib/Reference/WorkPackageReferenceProvider.php
lib/Search/OpenProjectSearchProvider.php
lib/Service/OpenProjectAPIService.php
src/components/icons/OpenProjectIcon.vue
src/components/tab/EmptyContent.vue
src/components/tab/SearchInput.vue
src/reference.js
src/views/WorkPackagePickerElement.vue
tests/jest/components/tab/SearchInput.spec.js

Previously we used the default search provider for the smart picker but we this PR we define the custom smart picker so that the search is similar to the one we have implemented in the project tab.
https://github.com/nextcloud/integration_openproject/assets/41103328/b8e2a927-1728-4b45-a84d-fcee513501f0

[OP#48106] use same component as project tab for searching in smart picker

---

testplan.md

Update the manual test plan to include `project folder` feature

Update manual test plan

---

src/components/AdminSettings.vue
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap

Part of: https://community.openproject.org/projects/nextcloud-integration/work_packages/46179
The label was "Automatic managed folders" but it should be "Automatically managed folder" so this PR fixes that

[OP#46179] Fix managed project folders label

---

tests/lib/Service/OpenProjectAPIServiceTest.php

fixes [OP#49613]: https://community.openproject.org/projects/nextcloud-integration/work_packages/details/49613
Php unit test started failing in stable27 because the constructor of `Client` required 5 parameters,
https://github.com/nextcloud/server/blob/231cec61ef4892889b4291f80fb76a1483bef6b2/lib/private/Http/Client/Client.php#L63
this is same as stable28 so this PR makes the check for nextcloud `>=stable27` to have same configuration
```bash
OCA\OpenProject\Service\OpenProjectAPIServiceTest::testValidateOpenProjectURL with data set #0 ('http://127.0.0.1', true)
39ArgumentCountError: Too few arguments to function OC\Http\Client\Client::__construct(), 4 passed in /home/runner/work/integration_openproject/integration_openproject/server/apps/integration_openproject/tests/lib/Service/OpenProje …
```

[OP#49613] failing php unit tests in ci

---

src/components/AdminSettings.vue
src/components/admin/FormHeading.vue
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
tests/jest/components/admin/__snapshots__/FormHeading.spec.js.snap

Related workpackage[OP#49182]: https://community.openproject.org/projects/nextcloud-integration/work_packages/49182
Our previous fix for fixing the colours of labels in different themes didn't work if the nextcloud theme was selected to be system default theme and the system theme was dark theme. This PR fixes that.

[OP#49182] Fix the form heading index colour in different themes

---

tests/lib/Service/OpenProjectAPIServiceTest.php

Forward port: https://github.com/nextcloud/integration_openproject/pull/454 
[OP#49613]: https://community.openproject.org/projects/nextcloud-integration/work_packages/details/49613
Php unit test started failing in stable27 because the constructor of `Client` required 5 parameters,
https://github.com/nextcloud/server/blob/231cec61ef4892889b4291f80fb76a1483bef6b2/lib/private/Http/Client/Client.php#L63
this is same as stable28 so this PR makes the check for nextcloud `>=stable27` to have same configuration
```bash
OCA\OpenProject\Service\OpenProjectAPIServiceTest::testValidateOpenProjectURL with data set #0 ('http://127.0.0.1', true)
39ArgumentCountError: Too few arguments to function OC\Http\Client\Client::__construct(), 4 passed in …
```

fix failing phpunit tests in stable27

---

lib/Service/OpenProjectAPIService.php
tests/acceptance/features/api/setup.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/lib/Service/OpenProjectAPIServiceTest.php

Fixes: https://community.openproject.org/projects/nextcloud-integration/work_packages/49621/
Our previous check for `hasAppPassword` expects the user "OpenProject" to have only one app password. But in cases where the user "OpenProject" has multiple app passwords for instance if the user is logged in somewhere it will create a session app password, this check will return `false` which will result in the project folder section in the administrative form being disabled.
```php
return sizeof($this->tokenProvider->getTokenByUser(Application::OPEN_PROJECT_ENTITIES_NAME)) === 1;
```
So in this PR we loop through all the tokens and only return true if the token with the name "OpenProject" exists and also while deleting, delete all the tokens with the name "OpenProject". This fixes the issue we …

[OP#49621] fix app password form becomes inactive

---

src/components/AdminSettings.vue
tests/jest/components/AdminSettings.spec.js
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap

[OP#49435] https://community.openproject.org/work_packages/49435
- Login as the administrator in nextcloud
- setup integration `Administration settings->Administration->OpenProject
- Go to Administration settings->Administration->security
- Delete the OpenProject client
- Go back to `Administration->OpenProject
The Nextcloud OAuth Client section is disabled and the only way to recreate it is by resetting the integration

[OP#49435] Nextcloud oauth section should not be disabled when the user deletes the oauth credentials

---

lib/Controller/ConfigController.php
lib/Controller/OpenProjectAPIController.php
lib/Listener/OpenProjectReferenceListener.php
lib/Reference/WorkPackageReferenceProvider.php
lib/Search/OpenProjectSearchProvider.php
lib/Service/OpenProjectAPIService.php
phpstan.neon
src/components/AdminSettings.vue
src/components/admin/FormHeading.vue
src/components/icons/OpenProjectIcon.vue
src/components/tab/EmptyContent.vue
src/components/tab/SearchInput.vue
src/reference.js
src/views/WorkPackagePickerElement.vue
tests/acceptance/features/api/setup.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/jest/components/AdminSettings.spec.js
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
tests/jest/components/admin/__snapshots__/FormHeading.spec.js.snap
tests/jest/components/tab/SearchInput.spec.js
tests/lib/Reference/WorkPackageReferenceProviderTest.php
tests/lib/Refrence/WorkPackageReferenceProviderTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

This PR merges the changes/bug fixes done in `release/2.4` branch to master

Merge release2.4 to master

---

appinfo/info.xml

The release of `2.4.0` didn't go through to the app store because of a network error. https://github.com/nextcloud/integration_openproject/actions/runs/5921730212/job/16054677003
```
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
```
Increase the version of the app to `2.4.1`

Increase the version of the app to 2.4.1

---

src/components/tab/SearchInput.vue
src/views/WorkPackagePickerElement.vue

Search input from `smartpicker` was not focused when it was displayed instead the closed button was displayed. This PR makes sure that the search input is focused when user opens the search for the workpackages from any where i.e from `smart-picker`, `tab` or `multiple-files-link-modal`.
https://community.openproject.org/work_packages/49755/activity

[WP#49755]Focus search input for workpackage when displayed

---

lib/Controller/FilesController.php
tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
tests/acceptance/features/api/getFilesinfoByFileIDsAPI.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/GroupfoldersContext.php
tests/lib/Controller/FilesControllerTest.php

[OP#49754] - https://community.openproject.org/work_packages/49754
For groupfolders if the fileId's are sent as string then the request returned `404` and also for group folders the internal path is `__groupfolders/<group-folder-id>` so `getInternalPath()` function returns empty string which resulted into the filename being empty so this PR fixes that as well.

[OP#49754] fix File(s)info endpoint does not return fileID for group folders

---

src/components/tab/SearchInput.vue

The PR merged https://github.com/nextcloud/integration_openproject/pull/466 removes the non used function `emptySearchInput()`. This function was missed to clean up in the function for linking work package which introduced bug.
The test may have passed because it was success and failure at the same time and this function was called after the api request was successfull.
https://community.openproject.org/projects/nextcloud-integration/work_packages/49787/activity?query_id=3787

[WP#49787]Remove the function for emptying search input

---

README.md
integration_setup.sh
src/components/AdminSettings.vue

The driect link for troubleshooting was not updated after the project folder setup was implemented. This PR updates the link that navigates directly to the troubleshooting link when there is any issue or error while using the integration application.
https://community.openproject.org/projects/nextcloud-integration/work_packages/49793/activity?query_id=3787

[WP#49793]Update the troubleshooting link

---

lib/Controller/FilesController.php
tests/lib/Controller/FilesControllerTest.php

Related work package [OP#49775] https://community.openproject.org/projects/nextcloud-integration/work_packages/49775
Since we dropped the support for nextcloud-24 we can use the server's `getDavPermissions` and can remove the copy of it from our app

[OP#49775] Use the server's getDavPermissions function

---

.github/workflows/ci.yml
appinfo/info.xml
lib/Controller/FilesController.php
tests/lib/Controller/FilesControllerTest.php
tests/lib/Service/DirectDownloadServiceTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

As discussed we want to drop support for stable 24 as a part of patch release so backporting 
- https://github.com/nextcloud/integration_openproject/pull/469
- https://github.com/nextcloud/integration_openproject/pull/480
Fixes: https://community.openproject.org/projects/nextcloud-integration/work_packages/49775

[OP#49775] Drop support for Nextcloud 24

---

src/components/tab/WorkPackage.vue

The earlier multi select did not had a border line when navigating with keyboard. But the new `NcSelect` has it own border when navigating with keyboard which made the inconsistency in the UI.
With Keyboard-navigation:
https://community.openproject.org/projects/nextcloud-integration/work_packages/49786/activity?query_id=3787

[WP#49786]Remove border and check for consistency in `WorkPackages`

---

lib/Controller/FilesController.php
tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
tests/acceptance/features/api/getFilesinfoByFileIDsAPI.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/GroupfoldersContext.php
tests/lib/Controller/FilesControllerTest.php

Backport- https://github.com/nextcloud/integration_openproject/pull/468
[OP#49754] - https://community.openproject.org/work_packages/49754
For groupfolders if the fileId's are sent as string then the request returned `404` and also for group folders the internal path is `__groupfolders/<group-folder-id>` so `getInternalPath()` function returns empty string which resulted into the filename being empty so this PR fixes that as well.

[Backport/468] [OP#49754] fix File(s)info endpoint does not return fileID for group folders

---

tests/lib/Controller/FilesControllerTest.php

php test `testGetFilesInfoSendStringIds` was failing in the CI with 
```console
There was 1 error:
1) OCA\OpenProject\Controller\FilesControllerTest::testGetFilesInfoSendStringIds
PHPUnit\Framework\MockObject\BadMethodCallException: Static method "getDavPermissions" cannot be invoked on mock object
/home/runner/work/integration_openproject/integration_openproject/server/apps/integration_openproject/lib/Controller/FilesController.php:3[39](https://github.com/nextcloud/integration_openproject/actions/runs/6071884336/job/16470815100#step:15:40)
/home/runner/work/integration_openproject/integration_openproject/server/apps/integration_openproject/lib/Controller/FilesController.php:247
/home/runner/work/integration_openproject/integration_openproject/server/apps/integration_openproject/lib/Contr …
```

Fix php test failing in the CI

---

.github/workflows/release.yml

Use node 18 for release workflow as the node version we have been using is outdated

Use node 18 for release

---

.github/workflows/ci.yml

the ci is failing on master due to some groupfolders issue there is a PR that fixes the issue in groupfolders but if that PR doesn't get merged soon maybe we should disable tests in master so that we won't block aby PR's from getting merged

Disable running tests on master

---

lib/AppInfo/Application.php
lib/Listener/AddContentSecurityPolicyListener.php

While implementing the creating workpackage through the nextcloud we will use the `iframe` from open project so allow open project host through content security policy
Related Workpackage[OP#49944] : https://community.openproject.org/work_packages/49944

[OP#49859] Allow openproject host through CSP

---

.github/workflows/ci.yml

Previously the CI was failing in master of the next cloud due to some issue with the group folders app and the CI was disabled for nextcloud master in https://github.com/nextcloud/integration_openproject/pull/490 but the issue with groupsfolder has been fixed so enable the CI for master again. 
Related workpackage[OP#49928] : https://community.openproject.org/projects/nextcloud-integration/work_packages/49928

[OP#49928] Enable CI in nextcloud master

---

src/components/tab/SearchInput.vue
src/components/tab/WorkPackage.vue
src/views/WorkPackagePickerElement.vue
src/views/WorkPackageReferenceWidget.vue
tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap

Fixes [OP#49871] : https://community.openproject.org/projects/nextcloud-integration/work_packages/49871

[OP#49871] fix White (or light) colored work package type not visible with light theme on work package picker (Talk)

---

README.md

This PR adds the documentation regarding getting the information of the file with `fileid(s)`.
https://community.openproject.org/work_packages/48988/activity

[WP#48988]Write Document for getting file information from file id

---

.github/workflows/ci.yml

We have a pslam error in nextcloud master, on running locally the error is something like 
```console
PHP Fatal error:  Declaration of Doctrine\Common\Cache\Psr6\CacheItem::get() must be compatible with Psr\Cache\CacheItemInterface::get(): mixed in nextcloud/master/3rdparty/doctrine/cache/lib/Doctrine/Common/Cache/Psr6/CacheItem.php on line 51
```
The psalm for some reason is looking into the 3rdparty app and I couldn't find the way to suppress , I'll make a PR to 3rdparty to fix the errors if possible but till then maybe it's better to not run psalm in nextcloud master

disable psalm for nextcloud master

---

lib/Controller/FilesController.php
tests/lib/Controller/FilesControllerTest.php

Fix incompatible constructor arguments for the activity classes by using the dependency injection container get method to automatically construct it.
Relevant upstream change https://github.com/nextcloud/activity/pull/1309 but the adjustment here makes it less error prone for further changes.
This PR fixes: https://community.openproject.org/projects/nextcloud-integration/work_packages/50507/activity

fix: Use DI for getting 3rdparty app classes

---

lib/Service/OpenProjectAPIService.php

Fixes: https://community.openproject.org/work_packages/50431
As the password that we generated for project folders didn't contain the special characters in case the nextcloud instance has a password policy setup enforcing special characters, an error is shown while setting up the project folders. This PR adds special characters in the password to prevent that from happening

[#50431] Project folders setup: add special characters to generated passwords

---

lib/Controller/FilesController.php
tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
tests/acceptance/features/api/getFilesinfoByFileIDsAPI.feature
tests/lib/Controller/FilesControllerTest.php

This PR adds the trailing slash for the folder path in the response for the file(s)info endopint.
https://community.openproject.org/projects/nextcloud-integration/work_packages/50326/activity

[WP#50326]Added trailing slash for folder for files info endpoint

---

lib/Service/OpenProjectAPIService.php
tests/lib/Service/OpenProjectAPIServiceTest.php

We have some functions that require the classes of other nextcloud apps like groupfolders and as we are supporting 3 major versions of the nextcloud server, the parameters to the class constructors may change according to the server's version. Currently, we are determining the version of the nextcloud and providing parameters based on that but in this PR we use dependency injection like in PR https://github.com/nextcloud/integration_openproject/pull/502
Related work package: https://community.openproject.org/projects/nextcloud-integration/work_packages/50617

[OP#50617] Use dependecy Injection to get classes from other apps

---

.github/workflows/ci.yml

Since our CI doesn't run unless there's some new push or new PR sometimes we might not know about certain regressions due to the releases of the next cloud servers until it's too late. So, maybe we can run the nightly which will be more reliable in catching such errors.
I have put the time to be `10` PM UTC which should be 4 am in Nepal but it can be changed to 12am 
For time format and more info https://crontab.guru/
https://community.openproject.org/projects/nextcloud-integration/work_packages/50542

[OP#50542]Schedule nightly CI runs

---

src/components/tab/SearchInput.vue
src/utils/workpackageHelper.js
src/views/LinkMultipleFilesModal.vue
tests/jest/components/tab/SearchInput.spec.js
tests/jest/views/LinkMultipleFilesModal.spec.js

The `OpenProject` server only supports the multiple selected up to only `20` files at once to link to a workpackage. So this PR makes changes in the request to make it support to link the multiple selected files more than `20` in chunks to link to a single workpackage.
https://community.openproject.org/projects/nextcloud-integration/work_packages/40971/activity

[WP#40971]Link the multiple selected files in chunks

---

.github/workflows/ci.yml

The nightly run was merged on released bracnch `2.4`. https://github.com/nextcloud/integration_openproject/pull/510. But it did not got triggered. So forward porting it to master if it is triggered in master and can be adjusted accordingly to released branch.
https://community.openproject.org/projects/nextcloud-integration/work_packages/50542/activity

[OP#50542]Forward port schedule nightly builds

---

.github/workflows/ci.yml

Previously the scheduled cron did not trigger the `release/2.4` branch. This PR makes the release branch trigger for the scheduled time. The `workflow` can only be triggered from the default master branch. 
https://community.openproject.org/projects/nextcloud-integration/work_packages/50542/activity

Scheduled trigger for the release/2.4 branch

---

.github/workflows/ci.yml
.github/workflows/release.yml

Nextcloud checked out a stable-28 branch https://github.com/nextcloud/server/tree/stable28 so now the master is version-29 , since apps like `groupfolders` aren't yet compatible with nextcloud version-29 we are getting CI failures like
```console
Run git clone --depth 1 https://github.com/nextcloud/groupfolders.git -b master server/apps/groupfolders
Cloning into 'server/apps/groupfolders'...
App "Group folders" cannot be installed because it is not compatible with this version of the server.
Error: Process completed with exit code 1.
```
This will unblock the CI.
OP#51218 - https://community.openproject.org/projects/nextcloud-integration/work_packages/51218

Make CI run with stable28

---

.github/workflows/ci-workflow.yml
.github/workflows/nighlty-ci-release-branch.yml
.github/workflows/shared_workflow.yml

This PR creates a nightly separate workflow for release/2.4 with reusable workflow to schedule a nightly for both master and release/2.4 branch.
https://community.openproject.org/projects/nextcloud-integration/work_packages/50542/activity

[WP#50814]Added schedudled yml for release branch

---

.github/workflows/ci-workflow.yml
.github/workflows/shared_workflow.yml

This PR:
1. Uses the old version of nextcloud image for CI since the new one hangs up the whole api tests.
2. Updates the CI for nightly checkout for `master`, `release/2.4` and `pr_branch` dynamically.
https://community.openproject.org/projects/nextcloud-integration/work_packages/51315

Check for failed CI in API

---

.github/workflows/shared_workflow.yml

The previous PR only checkout for `pull_request` event which did not run when for merge event.So this PR fixes it.

Checkout code for not scheduled

---

.github/workflows/shared_workflow.yml

According to the discussion made in the image of nextcloud repo. The php blackfire was enabled in the latest image for nextcloud instance which caused the never ending loop. But now it is reverted to disabled. So we can use the latest image like previously.
https://github.com/juliushaertl/nextcloud-docker-dev/discussions/254#discussioncomment-7720537

Revert to latest image of nextcloud in CI

---

.github/workflows/shared_workflow.yml

Something changed with the new latest image yesterday again. They have released a tag for every image with date name so that we do not need to apply condition for image in CI. For now the CI is green. We can debug the change in latest in other PR.

Downgrade the image of nextcloud service

---

lib/Listener/BeforeNodeInsideOpenProjectGroupfilderChangedListener.php

Fordwardport: https://github.com/nextcloud/integration_openproject/pull/527
We have a hook to protect the deletion of the folders inside the `OpenProject` groupfolder and to do so we intercept each deletion request to check if the node is inside  of `OpenProject` groupfolder. We expect the user to have a user session but in case of background jobs doing some cleanup jobs there's no user session. In the case where the files antivirus is trying to scan the files and remove any virus infected file our app didn't allow the deletion of such files.
In this PR we check if the user is `null` and the user is returned `null` we assume that it's a background job and return without performing further operation
Related Issues:
- https://community.openproject.org/work_packages/51321
- …

[OP#51321][forwardport]fix: Virus infected File is not removed by background job when integration app is enabled

---

appinfo/routes.php
lib/Controller/ConfigController.php
lib/Controller/OpenProjectAPIController.php
lib/Service/OpenProjectAPIService.php
src/components/OAuthConnectButton.vue
src/components/tab/EmptyContent.vue
src/components/tab/SearchInput.vue
src/views/WorkPackagePickerElement.vue

https://community.openproject.org/work_packages/50658
> Note: that the redirection does take back to the talk chat but it doesn't open the smart picker itself, as there was no easy of opening the smart picker programmatically, we decided that it's okay that the redirection doesn't open the smart picker. The user would have to open the smart picker to know if the OAuth connection was successful. Similar, is the reason for the lack of success/failure message, as we'll have to mount the smart picker component to display success/failure message for the connection, there was no easy way to mount it during the OAuth redirection so we decided that we'll leave it as it is in this PR

[#50658] Connect to OpenProject Button in Smart Picker

---

src/components/tab/WorkPackage.vue

Previously on the text app  the work package id in link previews was at top instead of center this PR brings it to center
Related work package: https://community.openproject.org/work_packages/49327

[#49327] Fix the workpackage id placement of link previews in text app

---

src/views/CreateWorkPackageModal.vue

Backport : https://github.com/nextcloud/integration_openproject/pull/541

[backport] fix(i18n): Changed spelling of product name "Nextcloud"

---

lib/Controller/FilesController.php
tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
tests/acceptance/features/api/getFilesinfoByFileIDsAPI.feature
tests/lib/Controller/FilesControllerTest.php

Related workpackage: https://community.openproject.org/projects/nextcloud-integration/work_packages/52045

Remove the trashed state from fileId endpoint

---

README.md

Now that we have to show the change log in each release. We need to be sure that we add each change log during each release. So this PR adds documentation to add those change log during release. And also Adds documentation to generate change logs in github as well and not only in app store.
https://community.openproject.org/projects/nextcloud-integration/work_packages/52241/activity

[WP#52241]update doc for release preparation and also after release

---

CHANGELOG.md
lib/Reference/WorkPackageReferenceProvider.php
lib/Service/OpenProjectAPIService.php
tests/lib/Reference/WorkPackageReferenceProviderTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

Through the talk app we can search for the work package and we send the link of the work package in the chat where there is minimal UI of the workpackage displayed in the chat section. But when the url have the `work package-id` for eg. `https://openproject.local/wp/<non-existent-workpackage-id>` it throws the error since we did not check the error when doing a search request for the work packge with the id `non-existent-workpackage-id` which seems to be the main cause of this error.
Now when we do the send the url `https://openproject.local/wp/<non-existent-workpackage-id>` some thing like this in the chat we get only warning logs as:
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/52658/activity

[WP#52658]Fix undefined array title in error log

---

CHANGELOG.md
lib/Reference/WorkPackageReferenceProvider.php
lib/Service/OpenProjectAPIService.php
tests/lib/Reference/WorkPackageReferenceProviderTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

Backport of PR: https://github.com/nextcloud/integration_openproject/pull/573

Backport undefined key 'title' error

---

src/components/AdminSettings.vue

In this PR, The `Group folders` app store link has been added to the error message regarding missing `Group folders` apps.
- Related to https://community.openproject.org/work_packages/52987/activity
The red line that follows has been added as shown in figure.

[WP #52987] Link to groupfolders app in app store

---

CHANGELOG.md
src/components/AdminSettings.vue

Previously in [PR-579](https://github.com/nextcloud/integration_openproject/pull/579) the group folder url was https://apps.nextcloud.com/apps/groupfolders 
and Now in this PR the group folder URL is change which redirect to settings/apps/groupfolder
https://community.openproject.org/projects/nextcloud-integration/work_packages/52987/activity

change url for groupfolder apps on admin tab

---

CHANGELOG.md
css/dashboard.css

In this PR there is working for the panel content to adjust the color consistent with the `nextcloud` panel
- https://community.openproject.org/projects/nextcloud-integration/work_packages/52979/activity
After adjusting the UI look like this

adjust the panel content color

---

CHANGELOG.md
src/components/tab/WorkPackage.vue

There is a gap which is denoted by a horizontal red arrow line. In this PR, the left align is removed between the the row-task-status and row-assigned.
- Fixes [issue_link](https://community.openproject.org/projects/nextcloud-integration/work_packages/52957/activity)
After adjusting the UI looks like this

adjust the left align between the row-task-status and row-assigned

---

lib/Controller/ConfigController.php

The full reset of the integration means resetting all the values that has been set already default null. Some how the `runningFullReset` was resulting `false` even when we were resetting the whole integration. It was because of `$oldClientSecret` `$oldClientId` which made it `false`. These 2 checks has been removed since it seems to be non relevant to resetting the integration.
- Fixes

Refactor the runningFullReset varaible

---

lib/Controller/ConfigController.php

Backport of PR: https://github.com/nextcloud/integration_openproject/pull/588

Refactor the runningFullReset varaible (#588)

---

src/components/AdminSettings.vue
tests/jest/components/AdminSettings.spec.js

The admin setting test was not fully running because of a test with  `.only` tests which was merged accidentally with it in PR https://github.com/nextcloud/integration_openproject/pull/552/files#diff-437209b827b3b0af71027912f456e4ef6a3b7340eb524e754ac53b12e9b4f72dR1792.
- This PR removes the .only and rerun other tests
- This PR adjust the failed tests due to new changes
- This PR adjust the terms of services sign flag in a `data` rather than directly passing from the `loaded state` into the template.

Remove only from admin setting tests

---

CHANGELOG.md
src/components/tab/SearchInput.vue
src/utils.js
tests/jest/components/tab/SearchInput.spec.js

This PR fixes the the display of the text when there is search query typed already while searching the workpackes but still gives the wrong text as `Start typing to search`.
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/52956

Fix workpackage not found when searching workpackage

---

src/components/tab/SearchInput.vue

This PR Replaces `NcButton` instead of `NcActionsButton` and cover all the text within button which is also left-aligned.
- Fixes [workpackage-link>](https://community.openproject.org/projects/nextcloud-integration/work_packages/52961)

[WP#52961]Used the NcButton for create Workpackage

---

tests/jest/components/tab/SearchInput.spec.js

Remove `.only` from search input test as well

Remove only from tests

---

CHANGELOG.md
jest.config.js
src/views/CreateWorkPackageModal.vue
tests/jest/fixtures/workpackageFormValidationProjectSelectedResponse.json
tests/jest/global.mock.js
tests/jest/views/CreateWorkpackageModal.spec.js

This PR refactors the form validation for creating workpackage from nextcloud.
- Fixes the wrong template shown which does not match according to the selected project types. Previously it might been have been occurred because the all the values passed in the form might have not been reset properly.
- Also makes the form validation functionality same as that of openproject as it was missing in the form validation which includes do not show type and status when those are not available when selecting or switching between projects
- Also not to change the description template once they have been edited by the workpackage creator.
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/53002/activity
- potentially fixes this …

[WP#53002]Fix/wrong template and refactor validation for workpackage created from NC

---

CHANGELOG.md
src/components/AdminSettings.vue
src/components/PersonalSettings.vue
src/components/settings/SettingsTitle.vue
tests/jest/components/AdminSettings.spec.js
tests/jest/components/PersonalSettings.spec.js

This PR adds an new UI providing the link to documentation on setting up integration in admin setting and provides a user guide link in the personal setting when integration with openproject
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/52955/activity

[WP#52955]Added link to documentation and user guide for integration setup

---

CHANGELOG.md
jest.config.js
src/views/CreateWorkPackageModal.vue
tests/jest/fixtures/workpackageFormValidationProjectSelectedResponse.json
tests/jest/global.mock.js
tests/jest/views/CreateWorkpackageModal.spec.js

Backport of PR: https://github.com/nextcloud/integration_openproject/pull/580

[backport] workpackage creation failed and fix wrong template

---

src/components/tab/SearchInput.vue

Remove border and resize the plus icon in create work package button according to this comment: https://community.openproject.org/work_packages/52961/activity
- Fixes https://community.openproject.org/work_packages/52961/activity

Change plus icon size and remove button border

---

appinfo/info.xml
src/components/AdminSettings.vue
src/components/PersonalSettings.vue
src/components/settings/SettingsTitle.vue
src/components/tab/SearchInput.vue
src/utils.js
tests/jest/components/AdminSettings.spec.js
tests/jest/components/PersonalSettings.spec.js
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
tests/jest/components/__snapshots__/PersonalSettings.spec.js.snap
tests/jest/components/tab/SearchInput.spec.js

Forward all not ported PRs in `master` from `release/2.6`. 
https://github.com/nextcloud/integration_openproject/pull/613
https://github.com/nextcloud/integration_openproject/pull/611
https://github.com/nextcloud/integration_openproject/pull/610
https://github.com/nextcloud/integration_openproject/pull/609
https://github.com/nextcloud/integration_openproject/pull/608
https://github.com/nextcloud/integration_openproject/pull/607

Forwardport p rs not ported

---

.github/workflows/shared_workflow.yml
CHANGELOG.md
css/dashboard.css
lib/Dashboard/OpenProjectWidget.php
tests/lib/Service/OpenProjectAPIServiceTest.php

This PR drops support `NC25` from the integration application code.
https://community.openproject.org/projects/nextcloud-integration/work_packages/53958/activity

[WP#53958]Drop support for `NC25` from application code

---

src/components/settings/SettingsTitle.vue
tests/jest/components/AdminSettings.spec.js
tests/jest/components/PersonalSettings.spec.js

This PR fix the font size which was a bit same(inconsistent) in the personal section of the integration setting.
- Fixes (https://community.openproject.org/projects/nextcloud-integration/work_packages/54451)

[WP#54451]Fix the font size for setting documentation

---

.github/workflows/shared_workflow.yml

Currently, only one PHP version 8.2, is running in the CI. When we include the other versions, 8.0, 8.1, and 8.3, the CI build will take a longer time. Therefore, add them only to the nightly build.
- https://community.openproject.org/work_packages/54185/activity

[WP #54185] Add php version 8.0,8.2,8.3 for nightly build only

---

.github/scripts/notify-to-element.sh

The main reason behind the nightly ci bot giving the false status was that the api call to get the jobs information gave only details for 30 jobs. But in nightly we have now 40+ < 50 jobs now (recently). So the script fails to check the details of other jobs (after 30 jobs). This Script increase the job details to 50 which would be enough for getting details of our jobs in the CI.
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/54507

[WP#54507]fix CI false status failure

---

lib/Service/OauthService.php
tests/acceptance/features/api/setup.feature

The integration script failed when we had the `project folder` already setup on `nextcloud` and we try to configure the integration config. It was because when the `project folder` is already set  up on the nextcloud, we use `PATCH` method to setup as using `POST` is not suitable since the `project folder` set up is already done in the nextcloud. Previously the script used to work fine but with this PR https://github.com/nextcloud/integration_openproject/pull/445 the client secret in the `PATCH` response was removed which was the main reason for the failure.

Refactor integration script when `project folder` is already setup

---

.github/workflows/shared_workflow.yml
lib/AppInfo/Application.php
lib/Listener/LoadAdditionalScriptsListener.php
lib/Service/OpenProjectAPIService.php
psalm.xml
tests/acceptance/features/bootstrap/FeatureContext.php
tests/lib/Controller/ConfigControllerTest.php
tests/stub.phpstub

This PR following activities are performed: 
- fixes the error while running psalm 
```console
PHP Fatal error:  Declaration of Doctrine\Common\Cache\Psr6\CacheItem::get() must be compatible with Psr\Cache\CacheItemInterface::get(): mixed in nextcloud/master/3rdparty/doctrine/cache/lib/Doctrine/Common/Cache/Psr6/CacheItem.php on line 51
```
- Removing the phpstan from the CI
- https://community.openproject.org/projects/nextcloud-integration/work_packages/50516/activity

run psalm with all NC versions

---

.github/workflows/shared_workflow.yml

We changed the CI to run our API tests with PHP version `8.3` in PR https://github.com/nextcloud/integration_openproject/pull/644. But because only NC-28 and NC-29 support PHP 8.3 CI would run only these versions.
Our app also supports NC-26 and NC-27. In this PR API tests for NC 26 & NC-27 are enabled to run with PHP 8.2
The goal is to run API tests in PRs for each NC version.

Make API test run for stable 26 and 27 run in php8.2

---

.github/workflows/shared_workflow.yml
CHANGELOG.md
appinfo/info.xml
lib/Controller/ConfigController.php
lib/Service/OpenProjectAPIService.php
tests/lib/Controller/DirectUploadControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

In this PR, following task is done:
- Make integration app support for nextcloud master
- Make integration app support for nextcloud master in CI as well
- removed the `safe` functions since NextCloud has removed `theCodingmachine/safe` https://github.com/nextcloud/3rdparty/pull/1799#issuecomment-2049152497
- https://community.openproject.org/projects/nextcloud-integration/work_packages/55364/activity

Add support for integration_app in nextcloud master

---

.github/workflows/shared_workflow.yml
CHANGELOG.md
appinfo/info.xml
lib/Controller/ConfigController.php
lib/Service/OpenProjectAPIService.php
tests/lib/Controller/DirectUploadControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

This PR is backport from master PR 
https://github.com/nextcloud/integration_openproject/pull/649

[Backport] support nextcloud30 and remove safe

---

CHANGELOG.md
lib/Controller/ConfigController.php
lib/Controller/OpenProjectAPIController.php
lib/Service/OpenProjectAPIService.php
psalm.xml
tests/lib/Controller/OpenProjectAPIControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

This PR:
- Adds a way to log every activities regarding the admin integration configuration to log them in `audit.log` file in the Nextcloud data.
> Note: This PR does not implement the info warning in the UI. Since it is dependent to this bump PR: https://github.com/nextcloud/integration_openproject/pull/654.
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/55110

Added admin audit log for admin config integration setup

---

.github/workflows/nighlty-ci-release-branch.yml

Our nightly Ci is failing because we have reached the limit for pulling docker image from the docker hub. There is no problem in docker pull while we make PRs. But in nightly CI, the reason might be that we are pulling images consecutively from both nightly trigger (master CI as well as release CI).
So this PR:
- Separates the Nightly `cron` time for master and the release branch.
- Might Fix https://community.openproject.org/projects/nextcloud-integration/work_packages/56155

[WP#56155]Separate cron time for nightly (master and release)

---

.github/workflows/shared_workflow.yml

This PR removes the `pgsql` jobs from the CI to reduce the docker images pull in CI as the pull rate for the authenticated user is limit to 200 pulls in 6 hours and our CI is failing because of that in nightly as well as in PRs. This is a temporary solution for the CI fix. But the further fix would need to be permanent one (either using caching concepts or using premium version for the docker)
- Fixes (https://community.openproject.org/projects/nextcloud-integration/work_packages/56155)

Remove `PGSQL` jobs from CI to reduce docker image pull 

---

lib/Controller/DirectUploadController.php
tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/lib/Controller/DirectUploadControllerTest.php

This PR
- Adds a timestamp as creation date for a file uploaded through the direct upload endpoint.
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/56592/activity?query_id=5464

[WP#5464]Ctime adjustment

---

src/components/AdminSettings.vue

The Check icon for the button in admin setting after the version bump (nextcloud/vue) to `8.12.0` seems to be black in dark mode. But it should be white in both light and dark theme.
This PR fix the check icon to make it white in both dark and light mode.
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/56056

[WP#56056]Fix icon color dark mode

---

CHANGELOG.md
lib/Migration/Version2640Date20240628114300.php
lib/Migration/Version2640Date20240628114301.php
lib/Service/OpenProjectAPIService.php
tests/lib/Service/OpenProjectAPIServiceTest.php

The main reason for the random deactivation of the Automatically managed project folder seems to be happening because the special user "OpenProject" was logged in and the password for that user was changed which deleted the application password for that user. In addition to that, as of now we generate temporary application password for user "OpenProject" which also gets deleted when the user "OpenProject" password is changed.
This PR fixes the random deactivation of the Automatically managed project folder.
- Adds changes that makes the application password Permanent (does not get deleted after user password is changed)
-  Adds a migration step in order to make the temporary application password for the "OpenProject" to permanent for all the user already having application password.
> …

[WP#]Fix random deactivation of automatically managed folders

---

lib/Settings/Admin.php
src/components/AdminSettings.vue
tests/jest/components/AdminSettings.spec.js

This PR adds:
- An info in the UI when admin audit configuration is not set up correctly for logging integration setup activities in `audit.log` file. Also it will not appear in the UI when admin audit configuration is correct.
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/55110/activity

Add info for admin audit in the UI

---

CHANGELOG.md
lib/Controller/OpenProjectAPIController.php
lib/Service/OpenProjectAPIService.php
src/views/CreateWorkPackageModal.vue
tests/jest/fixtures/openprojectAvailableProjectResponseAfterSearch.json
tests/jest/views/CreateWorkpackageModal.spec.js
tests/lib/Service/OpenProjectAPIServiceTest.php

Previously we used to fetch all the projects (linked to `Nextcloud` host) to create WorkPackages from Nextcloud. But now based on the `pageSize` parameter set on `OpenProject`, they provides the the available projects response. 
So this PR
- Make the default `pageSize` for the available OpenProject response to `100` or can be decided
- Make search request to the OpenPtoject when the available project is not in the initially fetched OpenProject available projects.
Also:
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/56588/activity?query_id=5464

[WP#5464]Apply `typeahead` with `debounce` while searching projects to create workpackage from Nextcloud

---

.github/workflows/shared_workflow.yml

The `master` branch of nextcloud seems to be change to some version `31.x.x` and in our CI our application depends on apps like groupfolders, activity  which does not support the `31.x.x` version of nextcloud yet. So this PR changes the master branch to stable30 so that the apps are compatible to the stable30 of nextcloud.

Change branch from master to stable30 in CI

---

.github/workflows/release.yml

In this PR, `gd` extensions is added on release CI since there cames following error:
```zsh
PHP module GD not installed.
{"reqId":"e4tmmptphQoRHQtytlAx","level":3,"time":"2024-08-15T09:46:49+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"fopen(/home/runner/html/nextcloud/config/config.php): Failed to open stream: No such file or directory at /home/runner/html/nextcloud/lib/private/Config.php#221","userAgent":"--","version":"","data":{"app":"PHP"}}
Please ask your server administrator to install the module.
```

add gd extension in release workflows

---

.github/workflows/shared_workflow.yml
CHANGELOG.md
appinfo/info.xml
tests/acceptance/features/api/setup.feature
tests/lib/Reference/WorkPackageReferenceProviderTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

This PR:
- Drops the support for Nextcloud-26 as Nextcloud-26 is not supported for enterprise anymore.
- Removes code dependent or related to Nextcloud-26 in `integration_app`
- Remove Nextcloud-26 support from CI as well (while running tests on CI)
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/57384

Drop support for nc 26

---

CHANGELOG.md
lib/Controller/DirectUploadController.php
tests/lib/Controller/DirectUploadControllerTest.php

When `Files access control` app is enabled in the Nextcloud and has some restriction to some file for access (read, write, upload and so on) from our application we seems to pass the status code `500` and it resulted as internal server error when we direct upload restricted files/folder from OpenProject.
This PR:
- Catch the exception with proper status code and error message (given by the Nextcloud server).
- Fixes (https://community.openproject.org/projects/nextcloud-integration/work_packages/56328)

[WP#56328]Fix error message when upload is restricted by file access control in `Nextcloud`

---

.github/workflows/shared_workflow.yml

On CI, there was a flaky error in the PHPUnit test related to the mock server port. So In this PR, there is code added for CI to re-run the phpunit test one time whenever there is an error araised. 
**Error:**
```console
There was 1 error:
1) OCA\OpenProject\Service\OpenProjectAPIServiceTest::testGetAvailableOpenProjectProjectsPact
PhpPact\Consumer\Exception\MockServerNotStartedException: The mock server could not be started
/home/runner/work/integration_openproject/integration_openproject/server/apps/integration_openproject/vendor/pact-foundation/pact-php/src/PhpPact/Consumer/Service/MockServer.php:35
/home/runner/work/integration_openproject/integration_openproject/server/apps/integration_openproject/vendor/pact-foundation/pact-php/src/PhpPact/Consumer/Driver/Interaction/InteractionDrive …
```

CI: Run phpunit test one times more on error

---

.github/workflows/shared_workflow.yml

The CI runs of this app are too heavy.
Please reduce the matrix to something suitable. The change in `name: unit tests and linting` looks quite "decent".
The `name: API tests` change was just to prevent this PR from swallowing another 1h55m of CI time.
A recommended matrix is:
- Test each PHP version (8.1, 8.2, 8.3) with 1 database (mysql) against 1 server (stable30)
- Test each additional database (postgres) against 1 PHP (8.1 installs fastest) the latest supported server (stable30)
- Test each older server (stable26, …, stable29) with 1 PHP version (8.1 installs fastest) against 1 database (mysql) only
---
Job | Before | After
---|---|---
unit tests and linting | 17 | 7
X | stable30 php8.1<br>stable30 php8.2<br>stable30 php8.3<br>stable29 php8.0<br>stable29 php8.1<br>stable29 …

ci: Reduce testing matrix

---

composer.json
composer.lock
lib/Controller/ConfigController.php
lib/Service/OpenProjectAPIService.php

There was a new release of cs-fixer https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.64.0 that our package `friendsofphp/php-cs-fixer` uses. Since we have been using old version of the package,
This PR:
- Bumpt the pacakge `friendsofphp/php-cs-fixer`
- updates the composer lock file
- Fixes CI failure https://github.com/nextcloud/integration_openproject/actions/runs/10648668410/job/29517977924

Bump `friendsofphp/php-cs-fixer` version and update composer

---

lib/Controller/ConfigController.php
lib/Service/OauthService.php
lib/Service/OpenProjectAPIService.php

A part of the code maintenance was missed for release `2.7` for the integration app. Since for release `2.7` it supports NC>=27,
This PR removes:
- Code for NC version check to encrypt the oauth client secret. It is available from stable NC-27. 
Part of: https://github.com/nextcloud/integration_openproject/pull/689
Part of this WP: https://community.openproject.org/projects/nextcloud-integration/work_packages/57384/activity?query_id=5464
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/57384/activity?query_id=5464

Remove version comparision for secret encryption

---

CHANGELOG.md
lib/Controller/DirectUploadController.php
tests/lib/Controller/DirectUploadControllerTest.php

This PR is backport of master PR https://github.com/nextcloud/integration_openproject/pull/688

Backport: fix misleading message error

---

CHANGELOG.md
lib/Service/OauthService.php
tests/acceptance/features/api/setup.feature
tests/lib/Service/OauthSeviceTest.php

In OAuth, now the client secret are hashed for greater security which is done in this PR https://github.com/nextcloud/server/pull/47635. Previously we just used to encrypt it.
This PR:
- Makes changes for the hash update for different NC versions for our APP
- Also remove `client_secret` when fetching the client info for the existing user.  
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/57654

[WP#57654]switch encryption for oauth secret

---

.github/workflows/shared_workflow.yml
CHANGELOG.md
appinfo/info.xml
lib/Service/OauthService.php
tests/acceptance/features/api/setup.feature
tests/lib/Reference/WorkPackageReferenceProviderTest.php
tests/lib/Service/OauthSeviceTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

Forward port PRs: https://github.com/nextcloud/integration_openproject/pull/689 , https://github.com/nextcloud/integration_openproject/pull/695, https://github.com/nextcloud/integration_openproject/pull/694
As a part of release preparation

Forwardport changes of  `2.7.0` to `master`

---

tests/acceptance/features/api/setup.feature
tests/acceptance/features/bootstrap/DirectUploadContext.php
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/FilesVersionsContext.php
tests/acceptance/features/bootstrap/GroupfoldersContext.php

This PR added code to the test to determine whether the file or folder existed before the folder's creation.
https://github.com/nextcloud/integration_openproject/blob/master/tests/acceptance/features/api/setup.feature#L545
Previously, when a folder was created and it already existed, the server would return a 405 status code. But, now it is returning a 500 status code.
https://github.com/nextcloud/integration_openproject/blob/master/tests/acceptance/features/api/setup.feature#L679
Similarly, in case of the PROFIND, it is also returning a 500 status code.
Due to this reasons, there raise CI failure
```feature
And user "OpenProject" has created folder "/OpenProject/project-abc"                                              # FeatureContext::userHasCreatedFolder()
HTTP status code was not 201 …
```

tests: check folder exist before creation

---

tests/acceptance/features/bootstrap/DirectUploadContext.php
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/FilesVersionsContext.php
tests/acceptance/features/bootstrap/GroupfoldersContext.php

This PR, forwardport the release2.7 PR  https://github.com/nextcloud/integration_openproject/pull/697

[forwardport] tests: check folder exist before creation (#697)

---

lib/Controller/FilesController.php
tests/lib/Controller/FilesControllerTest.php

This interface is deprecated and the logging will be removed with next release.

chore: Remove deprecated ILogger

---

CHANGELOG.md
integration_setup.sh

For creating file storage in `OpenProject`, it can either give a `MultipleErrors` or a  single `PropertyConstraintViolation` for the same error. Previously our script only used to check `MultipleErrors` but this PR updates the script to check and handle the `PropertyConstraintViolation` error as well.
>***NOTE:*** The main check is for `Nextcloud host name` and the `OpenProject file storage name` since we only provide this two property on the API request for the integration setup configuration
https://community.openproject.org/projects/nextcloud-integration/work_packages/57674/activity

Update script according to storage API response of openproject

---

src/components/AdminSettings.vue

The retry icon when setting up automatic project folder was inconsistent in the UI for dark theme. 
- https://community.openproject.org/projects/nextcloud-integration/work_packages/58278

Fix retry icon color in dark mode

---

.github/workflows/shared_workflow.yml

The `release/2.7` branch does not currently support Nextcloud 31 (master), as Nextcloud 31 has not been officially released.
So it will not be good to support the next cloud 31 on `release/2.7` for now. But we can later add support when there is officially released of nextcloud 31. 
Therefore, in this PR, Nextcloud 31 (master) is excluded for `release/2.7`.
There is a failure in the ci of `Nightly Release CI`, since it uses branch 2.7 which does not support nextcloud 31(master)
https://github.com/nextcloud/integration_openproject/actions/runs/11225470320

[CI] Exclude master nextcloud 31 in nightly release

---

integration_setup.sh

This PR:
- splits the configuration check function for both OpenProject and Nextcloud into separate functions.

Refactor integration script

---

.github/workflows/shared_workflow.yml

A syntax mistake was made in PR https://github.com/nextcloud/integration_openproject/pull/712 (could not check locally) to exclude NC-31 (msater) for nighlty CI `release/2.7` branch. This PR fix it.

Fix release branch failure for nightly CI

---

.github/workflows/shared_workflow.yml

This PR:
- excludes to run unit test for `master branch` for Nightly CI run for `release/2.7` branch
- Also include to run unit test for `master branch` for Nightly CI run for `master`   branch
1. When `isReleaseBranch` is `true`: https://github.com/nextcloud/integration_openproject/actions/runs/11339542033 (job is not running for `master` branch)
2. When `isReleaseBranch` is `false`: https://github.com/nextcloud/integration_openproject/actions/runs/11339559747 (job is running for `master` branch)
- Fixes https://github.com/nextcloud/integration_openproject/actions/runs/11336324103

check for true false in CI failure

---

.github/workflows/shared_workflow.yml

The API test for the `master` branch is failing because the `release/2.7` branch does not yet support Nextcloud master (NC-31). As a result, we need to skip running the API test for the `master` in the nightly release/2.7 CI as well.
The CI fails as: https://github.com/nextcloud/integration_openproject/pull/716
with error
```log
[capabilities.integration_openproject] The property integration_openproject is required
```
So This PR:
- excludes to run API test for `master` for Nightly CI run for `release/2.7` branch
- Also include to run API test for `master` for Nightly CI run for `master`   branch
1. When `isReleaseBranch` is `true`: https://github.com/nextcloud/integration_openproject/actions/runs/11340633426 (job is not running for `master` branch)
2. When `isReleaseBranch` is `false`: …

Exclude API test for master branch as well for Nightly CI release/2.7

---

CHANGELOG.md
lib/Listener/LoadAdditionalScriptsListener.php
lib/Service/OauthService.php

Backport changes of https://github.com/nextcloud/integration_openproject/pull/719 in `release/2.7` branch for patch release version `2.7.1`
- Fixes the issue described in the description of this PR https://github.com/nextcloud/integration_openproject/pull/719

Back port changes to get server version in `release/2.7` branch for server version compare

---

.github/workflows/shared_workflow.yml
composer.json
composer.lock

This PR resolves two CI failures:
**1. Docker Username Update:**
The CI failed due to a change in the username used for pulling Nextcloud Docker images. So in this PR,the username `juliushaertl` has been updated to `juliusknorr`.
**2. Gherkin Library Issue:**
A CI failure occurred due to an update of the `behat/gherkin` package to version `v4.10.0`. Gherkrin get updated to v4.10.0 when updating the composer file during PHP 8.0 in CI.
https://github.com/nextcloud/integration_openproject/blob/master/.github/workflows/shared_workflow.yml#L88
So, in this PR, there is add of the `"behat/gherkin": "v4.9.0"` in composer.json file to ensure v4.9.0 will be installed
and run the cmd `composer update behat/gherkin`
The Nextcloud Docker image pull failed due to the old username `juliushaertl` …

update the username of the nextcloud docker image for CI and add gherkin version on compose file

---

CHANGELOG.md
lib/Service/OpenProjectAPIService.php
lib/Settings/Admin.php
src/components/AdminSettings.vue
src/components/admin/FormHeading.vue
tests/jest/components/AdminSettings.spec.js
tests/lib/Service/OpenProjectAPIServiceTest.php

This PR:
- Adds a warning in projectfolder setup UI when server-side encryption is enabled, but not specifically activated for group folders.
- Adds php unit test
- Adds vue ui test for it 
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/57970/activity

[WP#57970]Add warning when encryption for group folders are not enabled explicitly

---

lib/Service/OauthService.php
tests/lib/Service/OauthSeviceTest.php

The method getVersion() returns with 4 digit array Example: [27,0,0,7] which fails on the line https://github.com/nextcloud/integration_openproject/blob/master/lib/Service/OauthService.php#L62
This error is seen on nextcloud 27 version (i.e when variable $nextcloudversion is 27.0.0)
So, this PR is for fixing such error
1. Clone the server of branch 27
```zsh
git clone git@github.com:nextcloud/server.git -b stable27
```
2. Go to path `\server` and Checkout to the `v27.0.0`
```zsh
git checkout v27.0.0
```
3. Set up nextcloud, enable integration_opneproject apps and openproject
4. When we try to do oauth connection then the app crashes
- https://community.openproject.org/projects/nextcloud-integration/work_packages/58464
While oauth configuration on stable27 branch we got following error: …

Fix version comparison

---

CHANGELOG.md

This PR is for resolving the conflict for branch `master` with branch `release 2.7`. That conflict was came due to this backport PR https://github.com/nextcloud/integration_openproject/pull/720. In that backport  [PR](https://github.com/nextcloud/integration_openproject/pull/720) only uses the `getversion` method instead of `getversionstring`, which was done is another file.

forwardport version compare for conflict resolve

---

tests/acceptance/features/bootstrap/GroupfoldersContext.php

Previously, a PR was merged in the groupfolder (master branch) where groupfolder's davpath was changed from the `index.php` endpoint to the `ocs` endpoint. As a result, we made changes in our app's test file (master branch) on [PR](https://github.com/nextcloud/integration_openproject/pull/704/files#diff-53b1b45fa06ccb60d0b9d87f29c6d01ac40b05ede1e764d7d08e16a104ab6006)
However, the groupfolder app has now reverted that [PR](https://github.com/nextcloud/groupfolders/pull/3407), which means the changes to the endpoint have been undone . So, in this PR, we are also reverting the changes we made accordingly.
- https://community.openproject.org/projects/nextcloud-integration/work_packages/59223

Revert api test file changes due to group folder update

---

lib/Controller/FilesController.php

The fatal error exists when we get information of the `groupfolders` every time we re request through files endpoint. And from the comment it self  https://github.com/nextcloud/integration_openproject/blob/276b637ae07861dd740d26c0f183cfb31ae749ac/lib/Controller/FilesController.php#L170 for group folders we  for group folders the internal path is `__groupfolders/<group-folder-id>` and `getInternalPath()` function returns empty string which seems to be fairly an information not an error as it does not break overall functionality.
A related PR was created and merge here: https://github.com/nextcloud/integration_openproject/pull/468
This PR:
- Changes the log level from `error` to `info` for it.
- Fixes [WP#58859](https://community.openproject.org/projects/openproject/work_packages/58859)

[WP#58859]Change the log for getting `groupfolders` through files endpoint to `info` instead of `error`

---

.github/workflows/shared_workflow.yml

The problem seems to be with the actions `shivammathur/setup-php@v2` that we are using in the CI. For the latest ubuntu the actions seems to be failing. The issue is reported here: https://github.com/shivammathur/setup-php/issues/880 https://github.com/shivammathur/setup-php/issues/880#issuecomment-2492932960
This PR:
- Downgrade the ubuntu version to 20.04
- Also change the tag for the github actions to `shivammathur/setup-php@v2`
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/59517

[WP#59517]change tag for the php setup in action

---

src/components/tab/WorkPackage.vue

As shown in the figure there is an following problem -
1. overlapping of text when the subject contains long text
2. another one is assignee name which padding not looks good
So, in this PR following works are done in order to covered above problem
1. fixed the overlapping of subject is fixed when there is long text contains on subject
2. fixes the padding of assignee
- https://community.openproject.org/projects/nextcloud-integration/work_packages/59821
**Before**
**After**

[UI/UX] Adjust height of the subject and padding of the assignee

---

.github/workflows/shared_workflow.yml
CHANGELOG.md
lib/Controller/ConfigController.php
lib/Controller/OpenProjectAPIController.php
lib/Dashboard/OpenProjectWidget.php
lib/ExchangedTokenRequestedEventHelper.php
lib/Listener/LoadAdditionalScriptsListener.php
lib/Listener/LoadSidebarScript.php
lib/Listener/OpenProjectReferenceListener.php
lib/Search/OpenProjectSearchProvider.php
lib/Service/OpenProjectAPIService.php
lib/Settings/Admin.php
lib/Settings/Personal.php
psalm.xml
src/components/AdminSettings.vue
src/components/PersonalSettings.vue
src/components/tab/EmptyContent.vue
src/utils.js
src/views/Dashboard.vue
src/views/LinkMultipleFilesModal.vue
src/views/ProjectsTab.vue
src/views/WorkPackagePickerElement.vue
tests/jest/components/AdminSettings.spec.js
tests/jest/components/PersonalSettings.spec.js
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
tests/jest/components/tab/EmptyContent.spec.js
tests/lib/Controller/ConfigControllerTest.php
tests/lib/Controller/OpenProjectAPIControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php
tests/lib/Settings/PersonalTest.php

This PR introduces the initial implementation for supporting OIDC-based connections to integrate with OpenProject for backend-to-backend requests.
Key updates in this PR include:
- Adding a UI option for OIDC-based authorization.
- Enabling automatic connection when OIDC authorization is selected, and the Keycloak configuration (with proper token-exchange setup) is properly set up.
- Partially hiding the OpenProject UI and displaying an error message for non-OIDC users when OIDC-based configuration is enabled.
- Also admin is allowed to switch between both oidc and ouath2 based authorization through UI
>NOTE: Error handling is not included in this iteration. Scenarios such as incorrect Keycloak setup, invalid tokens, or other issues will be addressed in a subsequent iteration.)
TODO …

Added authentication method selection in integration setup

---

dev/keycloak.yaml
dev/opnc-realm.json
docs/setup_nc_op__full.md

Setup keycloak test realm, clients, policies and demo users upon starting the keycloak service. This should reduce the efforts required to set up keycloak for the OIDC method.
Pre-configured in Keycloak:
- realm: `opnc`
- clients: `nextcloud` and `openproject`
- token-exchange policy between above clients has been added
- demo users: `alice` and `brian` (password: `1234` for both)

chore: setup new keycloak realm on startup

---

.github/workflows/shared_workflow.yml
bootstrap.php
composer.json
makefile

Added make targets for linting php and js code, and combined targets.
Also, added use of `SERVER_PATH` env to provide server root path. This is helpful when using integration_openproject repo outside of server apps directory.

chore: add linting make targets

---

.github/workflows/shared_workflow.yml
CHANGELOG.md
appinfo/info.xml

bump nextcloud version to 32 (required to run tests against the nextcloud master branch)
new CI jobs:
- [unit tests and linting (stable30, 8.2)](https://github.com/nextcloud/integration_openproject/actions/runs/12946925756/job/36112429152#logs)
- [API tests (stable30, 8, 2, mysql)](https://github.com/nextcloud/integration_openproject/actions/runs/12946925756/job/36112430402#logs)
- 3.0 matrixes replaced by current latest 3.1

ci: bump nextcloud version to 32

---

.github/workflows/nighlty-ci-release-branch.yml
.github/workflows/shared_workflow.yml
CHANGELOG.md
appinfo/info.xml
bootstrap.php
composer.json
dev/keycloak.yaml
dev/opnc-realm.json
docs/setup_nc_op__full.md
lib/Controller/FilesController.php
lib/Listener/LoadAdditionalScriptsListener.php
lib/ServerVersionHelper.php
lib/Service/OauthService.php
makefile
psalm.xml
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/GroupfoldersContext.php
tests/lib/Controller/FilesControllerTest.php

Backport
- #704 
- #705
- #712
- #714
- #715
- #717 
- #719 
- #738
- #755 
- #757
- #758
- #760

chore: backport nextcloud-31 bump commits

---

CHANGELOG.md
appinfo/routes.php
lib/Controller/OpenProjectAPIController.php
lib/Controller/OpenProjectController.php
lib/Service/OpenProjectAPIService.php
lib/Settings/Admin.php
src/components/AdminSettings.vue
src/components/tab/SearchInput.vue
src/utils/workpackageHelper.js
src/views/CreateWorkPackageModal.vue
src/views/Dashboard.vue
src/views/LinkMultipleFilesModal.vue
src/views/ProjectsTab.vue
src/views/WorkPackagePickerElement.vue
tests/jest/components/tab/SearchInput.spec.js
tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap
tests/jest/views/CreateWorkpackageModal.spec.js
tests/jest/views/Dashboard.spec.js
tests/jest/views/LinkMultipleFilesModal.spec.js
tests/jest/views/ProjectsTab.spec.js
tests/jest/views/__snapshots__/Dashboard.spec.js.snap
tests/lib/Controller/OpenProjectAPIControllerTest.php
tests/lib/Controller/OpenProjectControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php

Hey there!
Here is a change suggestion to make it possible to use this integration app from somewhere else than the web UI.
All the endpoints that communicate with OP are grouped in an OCS controller.
OCS endpoints can be reached without having a web session but with any supported authentication method (basic auth, app password etc...).
OCS endpoints always return an `ocs` object which contains a `meta` key and a `data` one. More info at https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-api-overview.html
The frontend has been adjusted but not tested IRL. This does not affect how the app works.
This would allow us, in [the agency feature](https://docs.nextcloud.com/server/latest/admin_manual/ai/app_context_agent.html), to make OP-related tools. In short, NC …

Group the API endpoints that contact OP in an OCS controller

---

CHANGELOG.md
lib/Service/OpenProjectAPIService.php
lib/Settings/Admin.php
src/components/AdminSettings.vue
src/constants/messages.js
tests/jest/components/AdminSettings.spec.js
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
tests/lib/Service/OpenProjectAPIServiceTest.php

In this PR, an error message is added which will display if the `user_OIDC` app is not supported with the integration OpenProject.
- https://community.openproject.org/projects/nextcloud-integration/work_packages/60683

[WP #60683]display error if oidc apps not supported

---

CHANGELOG.md
src/components/AdminSettings.vue
src/constants/messages.js
src/utils.js
tests/jest/components/AdminSettings.spec.js
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap

Renamed settings label:
- `Authorization` -> `Authentication`
- `OAuth2 two-way authorization code flow` -> `Two-way OAuth 2.0 authorization code flow`
- `OpenID identity provider` -> `Single-Sign-On through OpenID Connect Identity Provider`
- Fixes [WP#62248](https://community.openproject.org/wp/62248)

refactor: rename authorization to authentication

---

src/components/AdminSettings.vue
src/components/ErrorLabel.vue
tests/jest/components/AdminSettings.spec.js

Disable error message if the oidc app is not enabled or unsupported and incomplete auth settings.
- [WP#62209](https://community.openproject.org/wp/62209)
First setting | After completion of settings
--|--

fix: disbale error message if NC Hub option is not selectable

---

.github/workflows/shared_workflow.yml

The CI was failing due to the use of an invalid comparison operator `==` in a shell script condition. sh only supports the single equals sign `=` for string comparison inside `[ ]`. So in this PR, we're making that adjustment to fix the operator and ensure CI runs successfully.

CI: use single valid comparison operator in condition

---

tests/acceptance/features/api/directUpload.feature

The PR https://github.com/nextcloud/server/pull/51750 has been merged and backported to other release branches (29, 30, 31). This change doesn't allow creating a folder after setting an insufficient quota. To create a folder at least `3584 bytes` is required.
Therefore, rearranging the order of the test steps fixes the failing tests.
- [WP#62654](https://community.openproject.org/wp/62654)

test: fix quota test steps order

---

.github/workflows/shared_workflow.yml

Recently, nextcloud added a new feature that limits share rate ([PR link](https://github.com/nextcloud/server/pull/50905))  . This caused some API tests to fail on CI. To fix this, the PR  disables the share rate limit during API testing on CI.

CI: add occ command to disable the share rate limit

---

.github/workflows/shared_workflow.yml
lib/AppInfo/Application.php
lib/OIDCClientMapper.php
lib/Service/OpenProjectAPIService.php
lib/TokenEventFactory.php
psalm.xml
tests/lib/Service/OpenProjectAPIServiceTest.php

Send a token requested event with `api_v3` scope.
>With `ExternalTokenRequestedEvent` (login token), it is not possible to request extra scope. For `ExternalTokenRequestedEvent` to include extra scopes, **required extra scopes MUST be added beforehand in the provider configuration**
Open Task:
- [WP#62620](https://community.openproject.org/wp/62620)

feat: request token with scope

---

docs/setting_up_as_admin.md
lib/Service/OpenProjectAPIService.php
src/components/AdminSettings.vue
tests/acceptance/features/api/capabilities.feature
tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
tests/acceptance/features/api/getFilesinfoByFileIDsAPI.feature
tests/acceptance/features/api/setup.feature
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/GroupfoldersContext.php
tests/jest/components/AdminSettings.spec.js
tests/lib/Service/OpenProjectAPIServiceTest.php

There is a change in the Group Folders app: "Group folders" have been renamed to "Team folders".
PR link: https://github.com/nextcloud/groupfolders/pull/3536
In this PR, the "group folder" name is updated to "team folder".
- https://community.openproject.org/projects/nextcloud-integration/work_packages/63603

chore: Rename group folder app to team folders

---

CHANGELOG.md
lib/Controller/DirectUploadController.php

The deprecated `\OC_Helper::uploadLimit()` method, which simply wrapped `\OCP\Util::uploadLimit()`, has now been removed in nextcloud master ([PR link](https://github.com/nextcloud/server/pull/52912)).
Method `(\OCP\Util::uploadLimit())` is available in stable versions `28`, `29`, `30`, and `31`. It works the same way as `\OC_Helper::uploadLimit()` , so it won't affect any of the Nextcloud versions we currently support.
So, in this PR, directly using `\OCP\Util::uploadLimit()`

Chore: replace deprecated OC_Helper::uploadLimit() with Util::uploadLimit()

---

CHANGELOG.md
lib/Settings/Admin.php
tests/lib/Settings/AdminTest.php

If `authorization_method` is not set and there is oauth2 complete setup, then set `authorization_method` to `oauth2`.
- Fixes [#64314](https://community.openproject.org/wp/64314)

fix: set correct authentication-method if there is existing complete oauth2 setup

---

CHANGELOG.md
src/components/AdminSettings.vue
tests/jest/components/AdminSettings.spec.js

Persist the authentication settings form values after saving the form. The saved values are then displayed in the form view mode
- Fixes https://community.openproject.org/wp/64269
--|--

fix: persist authentication settings form values after save

---

CHANGELOG.md
src/components/AdminSettings.vue
tests/jest/components/AdminSettings.spec.js
tests/jest/components/__snapshots__/AdminSettings.spec.js.snap

Properly detect the auth-settings form completion state based on the sso type and other options.
- Fixes [#64520](https://community.openproject.org/wp/64520)

fix: set authentication form mode based on selected sso provider values

---

integration_oidc_setup.sh

Currently, on [integration_oidc_setup.sh](https://github.com/nextcloud/integration_openproject/compare/fixed/oidc-setup-script?expand=1#diff-7684bd1add12c1647b7d47d090752e0c90e4058e435c2028e45d8ce93f0eed06), there is an issue with the nextcloud version comparison when the version included characters such as `2.10.0-alpha1`.  Because of this, 2.10.0-alpha1 was seen as smaller than 2.9.0, which caused an error.
This PR fixes the issue by using a better way for comparing version numbers, which works correctly even when their include characters.

Chore: fix the nextcloud app version compare in oidc setup script file

---

CHANGELOG.md
lib/Listener/LoadSidebarScript.php
tests/lib/Listener/LoadSidebarScriptTest.php

We were calling `get-user-info` method meant to be for OIDC auth-method only, even for OAuth2 auth-method. This led to an unnecessary API call to OpenProject. 
- Fixes [64874](https://community.openproject.org/wp/64874)

fix: do not trigger user-info request for oauth2 auth-method

---

.github/workflows/shared_workflow.yml

Previously, we were using the `main` branch of the `user_oidc` app in CI.
This recently failed CI with an error due to a breaking change in the `psr/log` library:
```json
Declaration of Psr\\Log\\AbstractLogger::emergency($message, array $context = []) must be compatible with Psr\\Log\\LoggerInterface::emergency(Stringable|string $message, array $context = []): void at /home/nabin/www/stable31/apps/user_oidc/vendor/psr/log/Psr/Log/AbstractLogger.php#22
```
This error appeared during WebDAV requests and caused CI to fail.
So, in this PR, there sets the `user_oidc` app to a stable version (v7.2.0) in CI to fix compatibility issues.

CI: fix error by using user_oidc v7.2.0

---

CHANGELOG.md
lib/Migration/Version2900Date20250718065820.php
lib/Service/OpenProjectAPIService.php
tests/lib/Controller/ConfigControllerTest.php
tests/lib/Controller/OpenProjectControllerTest.php
tests/lib/Service/OpenProjectAPIServiceTest.php
tests/lib/Settings/AdminTest.php
tests/lib/Settings/PersonalTest.php

Added a migration to seed the `authorization_method` app-value if there is exisiting oauth2 setup while upgrading from `2.8` -> `2.9`
This way, wen can decide to set `authorization_method` when the upgrade happens preventing the need for setting it on other places.
- Fixes [65873](https://community.openproject.org/wp/65873)

fix: add migration file

---

.github/workflows/shared_workflow.yml
tests/acceptance/features/bootstrap/FeatureContext.php

do not run job steps inside a separate container. This prevents us from using an extra container, and we do not have to install git and docker separately for the steps as the github runner includes them.
Previously, the problem was that the image pull reached the limit because there were many jobs running simultaneously. But as of now, we have significantly reduce the jobs number.
Ref: #831, #796
- #675
- WP: [56511](https://community.openproject.org/wp/56511), [56155](https://community.openproject.org/wp/56155), [48443](https://community.openproject.org/wp/48443)

ci: do not use separate container for steps 

---

CHANGELOG.md
lib/Service/OpenProjectAPIService.php
lib/Settings/Admin.php
src/components/AdminSettings.vue
src/components/admin/FormAuthMethod.vue
src/components/settings/ErrorNote.vue
src/constants/links.js
tests/jest/components/AdminSettings.spec.js
tests/jest/components/admin/FormAuthMethod.spec.js
tests/jest/components/admin/__snapshots__/FormAuthMethod.spec.js.snap

Show form errors on the respective section if the dependent app is not enabled or not supported.
- Resolves https://community.openproject.org/wp/64267

feat: show error card if required apps are not enabled or supported

---

src/components/AdminSettings.vue
tests/jest/components/AdminSettings.spec.js

This fixes an issue where the `Save button` in the `Authentication settings` section was not appeared.
- https://community.openproject.org/projects/nextcloud-integration/work_packages/65067

fix: Save button not working in Authentication settings section

---

CHANGELOG.md
src/components/admin/FormAuthMethod.vue

Refactored the authentication switch confirmation message to use proper translation placeholders and fixed grammar for better translation.
_Taken a references from [link](https://docs.nextcloud.com/server/latest/developer_manual/basics/translations.html#javascript-typescript-vue)_
- https://community.openproject.org/projects/nextcloud-integration/work_packages/65931/

fix: Improve grammar and use placeholders

---

CHANGELOG.md
lib/Controller/FilesController.php
tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
tests/acceptance/features/api/getFilesinfoByFileIDsAPI.feature
tests/lib/Controller/FilesControllerTest.php

Return owner as the modifier for the first upload.
1. Enable [activity](https://github.com/nextcloud/activity) app
2. Setup the integration_openproject app
3. Upload a file (note the file id)
4. Check file info for modifier (uploader should be as the modifier)
```
curl https://nextcloud.local/ocs/v1.php/apps/integration_openproject/fileinfo/{file_id} \
-H "Accept: application/json" -H "OCS-APIRequest: true" -u admin:admin
```
- Fixes [56323](https://community.openproject.org/wp/56323)

fix: return owner as a modifier for uploaded files

---

CHANGELOG.md
lib/AppInfo/Application.php
lib/Service/OpenProjectAPIService.php
tests/lib/Service/OpenProjectAPIServiceTest.php

Provide a default app name if the app is not available.
- Fixes [67366](https://community.openproject.org/wp/67366)

fix: provide a default app name if the app is not available

---

CHANGELOG.md
docs/release.md
src/constants/OpenProjectVersion.js
src/constants/messages.js
tests/jest/components/admin/__snapshots__/FormAuthMethod.spec.js.snap

Updated the latest stable OpenProject version and added a global config to update the OpenProject version in the future.
>[!IMPORTANT]
> On every **MAJOR** or **MINOR** OpenProject release, the version MUST be updated in this config file.
> `src/constants/OpenProjectVersion.js`
- Fixes [67272](https://community.openproject.org/wp/67272)

fix: show current latest stable OpenProject version

---

integration_oidc_setup.sh

Added new env `NC_INTEGRATION_OP_CLIENT_SECRET`.
When running the setup for `nextcloud_hub` auth method, envs `NC_INTEGRATION_OP_CLIENT_ID` and `NC_INTEGRATION_OP_CLIENT_SECRET` can be provided to create the OIDC client with that id and secret.
>[!IMPORTANT]
>When setting up with `nextcloud_hub`, the client id and secret MUST have 32-64 alphanumeric characters
```diff
NC_INTEGRATION_PROVIDER_TYPE=nextcloud_hub \
NC_ADMIN_USERNAME=admin \
NC_ADMIN_PASSWORD=admin \
NC_INTEGRATION_ENABLE_NAVIGATION=false \
NC_INTEGRATION_ENABLE_SEARCH=false \
NC_HOST=https://nextcloud.local \
+NC_INTEGRATION_OP_CLIENT_ID=XLJhes82qSW1m8hhCQieovMT0KfQJCoF \
+NC_INTEGRATION_OP_CLIENT_SECRET=31txcVTPnoYomI7S3lMo4xkbR0oomNEL \
OP_ADMIN_USERNAME=admin \
OP_ADMIN_PASSWORD=admin \
OP_STORAGE_NAME=nextcloud \ …
```

feat(script): add env to provide predefined OIDC client id and secret
