nextcloud/integration_openproject

- css/dashboard.css
- package.json
- stylelint.config.js
- ignore JS files for stylelint
- run stylelint also on css folder
- fix styles
> fix stylelint

- README.md
an other improvement of the docs to clarify how and why to setup the different ways of authenticate against the OpenProject instance
see https://github.com/eneiluj/integration_openproject/pull/13#issuecomment-1006364885
@lindenthal @phil-davis please review
> improve authentication documentation

- .github/workflows/ci.yml
- package.json
Runs the following in the CI:
- lint
- stylelint
- vue unit tests
- php unit tests
The workflow needs approval to be executed in the repository. See the run in my fork here https://github.com/kiranparajuli589/integration_openproject/pull/1
> [tests-only] implented github ci

- lib/Service/OpenProjectAPIService.php
- tests/lib/Service/OpenProjectAPIServiceTest.php
basic unit tests for `OpenProjectAPIService::getNotifications()`
for that I also moved getting time into seperate function to make it easier to fake the time
> unit tests for  OpenProjectAPIService::getNotifications() OP#40804

- src/components/PersonalSettings.vue
Reported by the translator at Transifex.
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
> l10n: Correct spelling

- src/components/settings/SettingsTitle.vue
just make `npm run watch` happy
> chage to single quote

- README.md
- docker-compose.yml
Setup developer environment for the integration app with `docker compose`
OP#40868
> [OP#40868] development environment with docker compose

- .github/workflows/ci.yml
With this PR:
- `push` on `master` branch should trigger the ci
- pr should trigger the ci
- merge commits should trigger the ci
- [tx-robot] commits like (657398162f46d514226afa3ba21347d9343237c7) should trigger the ci
OP#40946
> [OP#40946] Trigger CI for every push

- src/components/tab/EmptyContent.vue
- src/components/tab/SearchInput.vue
- tests/jest/components/tab/SearchInput.spec.js
Reported by the translator at Transifex.
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
> Separate words

- README.md
Providing the OpenProject address, the Client ID, and the Client Secret is performed: -> from Settings -> Administration ->  Connected accounts
-> not from Settings -> Personal ->  Connected accounts
> Fix authentication NC admin guide

- lib/Controller/ConfigController.php
- lib/Controller/OpenProjectAPIController.php
- tests/lib/Controller/OpenProjectAPIControllerTest.php
- tests/lib/Service/OpenProjectAPIServiceTest.php
https://community.openproject.org/projects/nextcloud-integration/work_packages/41257/activity
OP#41257
> use http status codes from `OCP/AppFramework/Http`

- README.md
added compose included container update information inside readme
> Added compose update information

- lib/Controller/ConfigController.php
- src/components/OAuthConnectButton.vue
- tests/jest/components/OAuthConnectButton.spec.js
- tests/lib/Controller/ConfigControllerTest.php
use PKCE to connect  via OAuth as described in 
https://www.oauth.com/oauth2-servers/pkce/authorization-request/
and
https://www.oauth.com/oauth2-servers/pkce/authorization-code-exchange/
> [OP#41128] use PKCE with oAuth

- package.json
- src/components/tab/SearchInput.vue
- tests/jest/components/tab/SearchInput.spec.js
- tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap
- try-catch around Axios calls
- component state saved in constants
- improve response checks
- fix loading indicator
- updated test cases
> Instead, we recommend writing tests that assert your component's public interface, and treat its internals as a black box.
Ref: https://v1.test-utils.vuejs.org/guides/#common-tips
https://community.openproject.org/projects/nextcloud-integration/work_packages/41295/activity
OP#41295
> code maintenance: search input vue

- appinfo/routes.php
- lib/Controller/OpenProjectAPIController.php
- src/components/tab/SearchInput.vue
- src/components/tab/WorkPackage.vue
- src/views/ProjectsTab.vue
- tests/jest/components/tab/SearchInput.spec.js
- tests/jest/components/tab/WorkPackage.spec.js
- tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap
- tests/jest/components/tab/__snapshots__/WorkPackage.spec.js.snap
- tests/jest/views/ProjectsTab.spec.js
- tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap
- tests/lib/Controller/OpenProjectAPIControllerTest.php
Part of: 
OP#41269
OP#41102
This PR redesigns the WorkPackage display in UI 
The new design looks like this:
Search Relation :
Existing relation:
> [OP#41102] UI of adding link to workpackage

- src/views/ProjectsTab.vue
the route is `work-packages` and not `work_packages`
> fix route when fetching work-packages

- src/components/tab/EmptyContent.vue
- tests/jest/components/tab/EmptyContent.spec.js
css alignment fixes
https://community.openproject.org/projects/nextcloud-integration/work_packages/41396
> [OP#41396] empty content css fixes

- src/components/tab/SearchInput.vue
- src/views/ProjectsTab.vue
- tests/jest/components/tab/SearchInput.spec.js
- tests/jest/fixtures/workPackageSearchReqResponse.json
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/41471
When searching for workpackages to link, don't show those that are already linked
> [OP#41471] filter out already linked files from search

- tests/lib/Service/OpenProjectAPIServiceTest.php
IClient constructor changed in NC 24 see https://github.com/nextcloud/server/commit/6be7aa112f6174c1406cfef5449836124a7f6f50#diff-cd64d65cb5d9cb2c60c6a050ac0739f4b94390011ef66ee81523885f60a4c64bL63
> fix CI because of changes in NC 24(master)

- .github/workflows/ci.yml
I cannot get anything >NC23 running correctly locally (blank page in the file view) and also our tests fail in CI.
Need to investigate more, but in the meantime only test with NC23
> only test with NC 23

- .github/workflows/ci.yml
> run tests also with NC 24

- src/components/tab/SearchInput.vue
- src/views/ProjectsTab.vue
- tests/jest/components/tab/SearchInput.spec.js
- tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap
OP#42100: https://community.openproject.org/projects/nextcloud-integration/work_packages/42100/activity
This PR adds the newly linked work packages at the top with a little animation and a dialog stating that the work package has been added. 
https://user-images.githubusercontent.com/41103328/168972791-0ed87ac5-c519-43c6-bbc8-eed90722f9a6.mp4
> [OP#42100]Add newly linked packages at the top with little animation

- src/views/ProjectsTab.vue
- tests/jest/views/ProjectsTab.spec.js
OP#42644 : https://community.openproject.org/projects/nextcloud-integration/work_packages/42644/activity
> [OP#42644] Handle error while unlinking work packages

- tests/jest/views/ProjectsTab.spec.js
OP#42745 : https://community.openproject.org/projects/nextcloud-integration/work_packages/42745/github
> [OP#42745] Fix unit tests to not display ugly log

- src/components/tab/SearchInput.vue
OP#42805 : https://community.openproject.org/projects/nextcloud-integration/work_packages/42805/activity
> [OP#42805] Fix problem with search list not clearing

- lib/Service/OauthService.php
@individual-it This does not change any other value of the OAuth client.
> New oauth service method to set the redirect uri

- src/components/tab/SearchInput.vue
- src/views/ProjectsTab.vue
- tests/jest/views/ProjectsTab.spec.js
- tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap
This PR makes changes to make the search input for searching work packages `sticky` while scrolling.
Fixes: https://community.openproject.org/projects/nextcloud-integration/work_packages/42136 (OP#42136)
> [OP#42136] Sticky search input

- lib/Controller/ConfigController.php
- lib/Service/OauthService.php
- src/components/AdminSettings.vue
- tests/lib/Controller/ConfigControllerTest.php
[OP- 42862] : https://community.openproject.org/projects/nextcloud-integration/work_packages/42862/activity
> [OP-42862] Change redirect uri only when op url changes

- src/components/AdminSettings.vue
- tests/jest/components/AdminSettings.spec.js
- tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
Update the confirm dialog text content (latest from the Figma)
Fixes: https://community.openproject.org/work_packages/42897
> [OP#42897] Update the confirm dialog text content used in the Admin Config form

- README.md
This PR updates the developer's documentation by removing all the unnecessary configurations and keeps the description up-to-date with the system's current functionality.
Also adds the following missing configurations: 
OP#41900: https://community.openproject.org/projects/nextcloud-integration/work_packages/41900/g
> [OP#41900] Improve developers documentation

- testplan.md
manual testplan for the OpenProject integration in NextCloud
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/42726
> OP#42726 manual testplan

- src/components/admin/TextInput.vue
- tests/jest/components/AdminSettings.spec.js
- tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
- tests/jest/components/admin/__snapshots__/TextInput.spec.js.snap
The copy button was not aligned with the related input field.
It is now aligned and the top-level wrapper has been removed.
> Group input field and copy button to align them vertically

- jest.config.js
- package-lock.json
- package.json
With this PR:
- use `vue2-jest` in place of `jest` https://github.com/vuejs/vue-jest
- use `v8` coverage provider https://jestjs.io/docs/configuration#coverageprovider-string
> [deps] Update jest

- package-lock.json
- package.json
- src/components/admin/TextInput.vue
this is currently not strictly needed because the hint text is compiled without any user-input. The only thing that is taken from outside is the URL.
Still I would like to sanitize it here because just ignoring the message might get us into trouble one day if the way how we generate the message is changed one day and it goes unnoticed.
> sanitize hint text

- src/views/Dashboard.vue
this code is not needed anymore because we use the notifications API of OpenProject to fetch the notifications and return them as an array. Because we don't use the workpackage API anymore there is no need to remember the last time it was fetched not to fetch newer changes. The notifications are just displayed as they are generated by OpenProject
see #111 for the major changes
> delete unneeded notification code from dashboard

- lib/Controller/OpenProjectAPIController.php
- src/components/AdminSettings.vue
- tests/jest/components/AdminSettings.spec.js
- tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
- tests/lib/Controller/OpenProjectAPIControllerTest.php
the error message for the case that the URL is invalid should be different
> [#43201] show different error message for invalid URL

- tests/jest/components/AdminSettings.spec.js
- tests/jest/components/OAuthConnectButton.spec.js
- tests/jest/components/PersonalSettings.spec.js
- tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
- tests/jest/components/__snapshots__/OAuthConnectButton.spec.js.snap
- tests/jest/components/admin/FieldValue.spec.js
- tests/jest/components/admin/FormHeading.spec.js
- tests/jest/components/admin/TextInput.spec.js
- tests/jest/components/admin/__snapshots__/FieldValue.spec.js.snap
- tests/jest/components/admin/__snapshots__/FormHeading.spec.js.snap
- tests/jest/components/admin/__snapshots__/TextInput.spec.js.snap
- tests/jest/components/tab/EmptyContent.spec.js
- tests/jest/components/tab/SearchInput.spec.js
- tests/jest/components/tab/WorkPackage.spec.js
- tests/jest/components/tab/__snapshots__/EmptyContent.spec.js.snap
- tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap
- tests/jest/components/tab/__snapshots__/WorkPackage.spec.js.snap
- tests/jest/views/ProjectsTab.spec.js
- tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap
make the higest level of the JS test-description look the same and fix the one that is wrong
> unify highest level of test description

- .gitignore
- README.md
- docker-compose.override.example.yml
- docker-compose.yml
- remove fix container names to enable multiple instances of this
compose file to be run
- remove fix port exposure for the same reason
- added docker-compose.override.example.yml
- amended README.md
- use compose v2 commands
- run markdown formatter
- added information about override for port exposure
should fix https://community.openproject.org/work_packages/43384
> Amend docker-compose.yml

- README.md
- Add occ maintainence command info. for server installation
- Add SQLite support info.
> Add CLI installation information for NC server

- .github/workflows/ci.yml
the app claims to have NC 22 as min version, so lets test it
> run tests with NC22

- README.md
document various general ways to configure and setup NC that are useful for testing
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/details/43529
> document different ways of setting up NC

- src/views/ProjectsTab.vue
- tests/jest/views/ProjectsTab.spec.js
- tests/jest/views/__snapshots__/ProjectsTab.spec.js.snap
the tooltip should be translated
fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/43758
> make unlink tooltip translatable

- appinfo/info.xml
While creating the tag v2.0.1 I forgot to change the version in xml and that resulted in the wrong version displayed in the app store. So need to do it all again
> bump version to 2.0.2

- css/dashboard.css
- lib/AppInfo/Application.php
- src/fileActions.js
- webpack.js
Added OpenProject button inside the file actions menu with opens the OpenProject Sidebar Tab.
https://community.openproject.org/work_packages/43670
> [#43670] add OpenProject to the files action menu in NC

- README.md
To make sure I don't forget it the next time
> document to update version in info.xml

- lib/Controller/ConfigController.php
- src/components/tab/EmptyContent.vue
- src/views/Dashboard.vue
- tests/lib/Controller/ConfigControllerTest.php
Description: Fix the redirect urls for the new dedicated personal settings section
Related: https://community.openproject.org/projects/nextcloud-integration/work_packages/43667
---
> [OP#43667] fix redirect urls for the new dedicated settings section

- appinfo/info.xml
https://community.openproject.org/projects/nextcloud-integration/work_packages/43715/activity
Updated the copy of the description to make it clearer, easier to read and more to-the-point
Signed-off-by: Parimal Satyal <88370597+psatyal@users.noreply.github.com> (OpenProject)
> Updated description for the OpenProject app

- appinfo/info.xml
> Updated description for the OpenProject app (backport to 2.0)

- appinfo/info.xml
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
> l10n: Delete "tab"

- appinfo/info.xml
> formatting of info.xml

- appinfo/info.xml
A follow up and further improvement on what was started in this work package:
https://community.openproject.org/projects/nextcloud-integration/work_packages/43715
> Update info.xml to contain a better title, summary and description

- README.md
Changelog:
- Updated introduction to use language closer to the app description 
- Updated titles of links to the documentation (so that they use the same titles as in the documentation)
Signed-off-by: Parimal Satyal <88370597+psatyal@users.noreply.github.com>
> Update intro text

- appinfo/info.xml
bump version to release latest translation improvements
> bump version to 2.0.3

- README.md
- distinguish between minor/major and patch releases
- more things that should not be forgotten
> improve release docs

- .github/workflows/release.yml
> Use auto-release branch for automatic releases, drop the 'release' one

- lib/Controller/FilesController.php
- tests/lib/Controller/FilesControllerTest.php
> Fix trashManager not found

- .github/workflows/ci.yml
> [2.0] run CI with stable25 branch of NC

- README.md
very minor improvements Inside Readme.md file
- Improve list items
- Improve typos and grammer
---
> improve readme list with some grammer fixes

- appinfo/info.xml
> bump version to 2.0.4

- lib/Controller/OpenProjectAPIController.php
- src/components/AdminSettings.vue
- src/components/admin/TextInput.vue
- tests/jest/components/AdminSettings.spec.js
- tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
- tests/jest/components/admin/TextInput.spec.js
- tests/jest/components/admin/__snapshots__/TextInput.spec.js.snap
- tests/lib/Controller/OpenProjectAPIControllerTest.php
Reverts nextcloud/integration_openproject#217
it has a conflict with #236 better revert this PR and fix the conflict here that during the merge of 2.0
> Revert "[OP#43824] show admin why connection to OpenProject cannot be established"

- .github/workflows/release.yml
Nextcloud 24 is the current stable, so I suggest to use that to build 2.0 of our integration
> build 2.0 using NC 24

- lib/Controller/OpenProjectAPIController.php
- src/components/AdminSettings.vue
- src/components/admin/TextInput.vue
- tests/jest/components/AdminSettings.spec.js
- tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
- tests/jest/components/admin/TextInput.spec.js
- tests/jest/components/admin/__snapshots__/TextInput.spec.js.snap
- tests/lib/Controller/OpenProjectAPIControllerTest.php
same as  #217 , but after merging release/2.0 into master and solving conflicts
>  [OP#43824] show admin why connection to OpenProject cannot be established

- .github/workflows/release.yml
- appinfo/info.xml
in case there will be an other 2.0 release, we descided to build again with NC master branch
for that its also required to increase the max-version on NC
> user master branch of NC for release

- .tx/backport
- appinfo/info.xml
prepare release by bumping the version number
> bump version to 2.1

- .tx/backport
transifex needs to be able to commit to the new branch
> allow transifex to commit to release/2.1 branch

- css/dashboard.css
Related work-package https://community.openproject.org/projects/nextcloud-integration/work_packages/44123/activity
Before: 
After:
> [#OP #44123] Fix the border colour of the avatar in dashboard

- css/dashboard.css
- src/components/settings/SettingsTitle.vue
Fixes: https://community.openproject.org/work_packages/44889
Screenshots:
> [#44889] OpenProject icon positioning & sizes made consistent over different places

- src/components/tab/SearchInput.vue
#44931 : https://community.openproject.org/projects/nextcloud-integration/work_packages/44931/activity?query_id=3513
> [ #44931]Fix the background colour for search bar

- lib/Controller/ConfigController.php
Remove leftovers of https://github.com/nextcloud/integration_openproject/pull/282
> [OP#45055]Remove leftover of notification code

- lib/Controller/ConfigController.php
- lib/Service/OpenProjectAPIService.php
- src/components/AdminSettings.vue
- tests/jest/components/AdminSettings.spec.js
- tests/lib/Controller/ConfigControllerTest.php
Part of https://community.openproject.org/projects/nextcloud-integration/work_packages/44747
> [feature/44747] revoke client tokens received from openproject

- README.md
- appinfo/info.xml
- appinfo/routes.php
- lib/AppInfo/Application.php
- lib/Controller/ConfigController.php
- lib/Controller/OpenProjectAPIController.php
- lib/Listener/LoadSidebarScript.php
- lib/Migration/Version2001Date20221213083550.php
- lib/Search/OpenProjectSearchProvider.php
- lib/Service/OauthService.php
- lib/Service/OpenProjectAPIService.php
- lib/Settings/Admin.php
- src/components/AdminSettings.vue
- tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
- tests/acceptance/features/api/getFilesinfoByFileIDsAPI.feature
- tests/acceptance/features/api/setup.feature
- tests/acceptance/features/bootstrap/FeatureContext.php
- tests/jest/components/AdminSettings.spec.js
- tests/lib/Controller/ConfigControllerTest.php
- tests/lib/Controller/OpenProjectAPIControllerTest.php
- tests/lib/Service/OpenProjectAPIServiceTest.php
- tests/lib/Settings/PersonalTest.php
This PR adds an endpoint for setting of whole integration configuration.
https://community.openproject.org/projects/nextcloud-integration/work_packages/44964/activity?query_id=3513
> [OP#44964]Single API endpoint for setting whole integration

- tests/acceptance/config/behat.yml
- tests/acceptance/features/bootstrap/FeatureContext.php
- tests/acceptance/features/bootstrap/SharingContext.php
to make it easier to implement new tests and keep the FeatureContext shorter move the sharing related step to own SharingContext
> move sharing related tests to new context

- makefile
- tests/acceptance/features/api/directUploadPrepare.feature
- tests/acceptance/features/bootstrap/FeatureContext.php
- tests/acceptance/features/bootstrap/SharingContext.php
This is a first set of API tests for https://community.openproject.org/projects/nextcloud-integration/work_packages/45465
They will not run in CI, as the API does not exist and also some test steps are not implemented yet, but those tests that can be already executed can be used for BDD to create the API
> [OP#45465] tests for prepare direct upload API

- src/views/Dashboard.vue
transifex did not pick up the new strings because they are not defined correctly, this PR should fix it
> [OP#45399] make reason strings translatable

- .tx/backport
> allow transifex to write to release/2.2

- tests/acceptance/config/behat.yml
- tests/acceptance/features/api/directUpload.feature
- tests/acceptance/features/bootstrap/DirectUploadContext.php
- tests/acceptance/features/bootstrap/FeatureContext.php
This is a first set of API tests for https://community.openproject.org/projects/nextcloud-integration/work_packages/45464
They will not run in CI, as the API does not exist and also some test steps are not implemented yet, but those parts of tests that can be already executed can be used for BDD to create the API.
I will keep on adding more tests
> [OP#45464] Tests for direct upload endpoint

- tests/acceptance/features/api/directUploadPrepare.feature
- tests/acceptance/features/bootstrap/DirectUploadContext.php
Check that every token for the direct upload is unique
> API test to check direct upload tokens are random

- tests/acceptance/features/api/directUpload.feature
- tests/acceptance/features/bootstrap/DirectUploadContext.php
- tests/acceptance/features/bootstrap/FeatureContext.php
The POST request with the data is not send by a particular user, but its only authenticated by the token. The whole point of this API is that the upload happend by an anonymous or not authenticated user.
> fix test expectations, request done by anonymous user

- tests/acceptance/features/api/directUpload.feature
More tests for https://community.openproject.org/projects/nextcloud-integration/work_packages/45464
> more API test cases for direct upload

- tests/acceptance/features/api/directUpload.feature
- tests/acceptance/features/bootstrap/DirectUploadContext.php
- tests/acceptance/features/bootstrap/FeatureContext.php
First test to see if CORS preflight requests work with direct upload API.
needs #300 to get merged first
> test CORS preflight with direct upload API

- tests/acceptance/features/bootstrap/DirectUploadContext.php
- tests/acceptance/features/bootstrap/FeatureContext.php
Move all replacements of inline codes of API tests to one function
> move all replacing of inline codes into one place

- README.md
- integration_setup.sh
This PR includes a bash script to set up the whole integration between `Open Project` and `NextCloud`
https://community.openproject.org/projects/nextcloud-integration/work_packages/45409/activity
> [OP#45409]Script for Integration

- tests/acceptance/features/api/directUpload.feature
- tests/acceptance/features/bootstrap/DirectUploadContext.php
- tests/acceptance/features/bootstrap/FeatureContext.php
1. The tables that uses overwrite were totally messed up
2. The "overwrite" switch was not send in the multipart data
> [OP#45464] correct direct upload overwrite tests

- tests/acceptance/features/api/directUpload.feature
Some more tests for cases where the "overwrite" values is invalid
> [OP#45464] API tests for invalid overwrite values

- README.md
I think the merging of the release branch into the master branch should not only happen on patch releases but also on minor releases.
> document merging release branch into master branch

- src/components/admin/TextInput.vue
Relate work package [OP#44486]: https://community.openproject.org/projects/nextcloud-integration/work_packages/44486/activity
> [OP#44486]Fix inconsistencies in dark theme

- src/components/admin/TextInput.vue
Relate work package [OP#44486]: https://community.openproject.org/projects/nextcloud-integration/work_packages/44486/activity
> [OP#44486]Fix inconsistencies in dark theme - release/2.2

- .github/workflows/ci.yml
the current master branch of NC, does not work with PHP 7 anymore, so don't try to test it with that PHP version
> NC master is not compatible with PHP 7

- .github/workflows/ci.yml
Coverage check and reporting got accidentally disabled by #330, re enable it
> enable coverage check with master&PHP8.1

- lib/Controller/DirectUploadController.php
- tests/acceptance/features/api/directUpload.feature
If a file is in the blacklisted_files list (https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html) then don't try to write it.
> [OP#45897] check if filename is in blacklisted_files list

- package-lock.json
- package.json
- src/components/AdminSettings.vue
- src/components/OAuthConnectButton.vue
- src/components/admin/TextInput.vue
- src/components/tab/SearchInput.vue
- src/views/ProjectsTab.vue
Related work packages [OP#45914]: https://community.openproject.org/projects/nextcloud-integration/work_packages/45914/activity?query_id=3513
This PR updates the dialog version to `3.2.0` and adds the necessary styling imports to fix the UI related inconsistentcies with dialogs
> [OP#45914] Update dialogs version to ^3.2.0

- package-lock.json
- package.json
- src/components/AdminSettings.vue
- src/components/OAuthConnectButton.vue
- src/components/admin/TextInput.vue
- src/components/tab/SearchInput.vue
- src/views/ProjectsTab.vue
Backporting pr: https://github.com/nextcloud/integration_openproject/pull/336
> [OP#45914] Update dialog version

- lib/Search/OpenProjectSearchProvider.php
Related work package: [OP#45841]  https://community.openproject.org/projects/nextcloud-integration/work_packages/45841/activity?query_id=3513
*light theme* 
*dark theme*
*light theme* 
*dark theme*
*light theme* 
*dark theme*
> [OP#45841] Fix search thumbnail

- .github/workflows/release.yml
NC master does not work with PHP7 anymore
> use php 8.1 for release

- lib/Controller/DirectUploadController.php
These lines are not needed anymore because we have declared the variables correctly now.
> remove @phpstan-ignore-line

- .github/workflows/release.yml
> [master] use php 8.1 for release

- docker-compose.yml
> [2.2] put apache config into a volume

- .github/workflows/ci.yml
- appinfo/info.xml
- lib/BackgroundJob/RemoveExpiredDirectUploadTokens.php
- lib/Service/DatabaseService.php
- tests/lib/Service/DatabaseServiceTest.php
This PR implements the background jobs to remove the expired direct upload tokens from the databases.
https://community.openproject.org/projects/817/work_packages/45466/activity
> [OP#45466]Remove expired direct upload tokens using background jobs

- .tx/backport
allow transifex to write on new release branch
> Allow transifex to write to release/2.3

- lib/Search/OpenProjectSearchProvider.php
This PR improves the `workpackage` search result presentation in global search of `nextcloud`
on master
onstable25
https://community.openproject.org/projects/nextcloud-integration/work_packages/45842/activity?query_id=3714
> [OP#45842]Improve Presentation of `workpackage` search result in global search

- lib/Search/OpenProjectSearchProvider.php
This PR makes the user avatar round in the global search of the `nextcloud` for the related `workpackage` of the Open Project
1. Before
2. After
https://community.openproject.org/projects/nextcloud-integration/work_packages/45842/activity
> [OP#45842]Make user avatar round

- lib/Controller/DirectUploadController.php
- tests/lib/Controller/DirectUploadControllerTest.php
This PR translates the error messages.
> Translate error messages in direct upload

- .github/workflows/ci.yml
- src/components/AdminSettings.vue
Backport https://github.com/nextcloud/integration_openproject/pull/371
> Make the translation string inline

- .github/workflows/ci.yml
- appinfo/info.xml
- lib/Service/OpenProjectAPIService.php
Related work package[OP#47099] : https://community.openproject.org/projects/nextcloud-integration/work_packages/47099/activity
> [OP#47099] Drop support for nextcloud version 22

- .github/workflows/ci.yml
- appinfo/info.xml
merge all from release/2.3 branch into master, including some conflict resolutions as part of release process of 2.3.3
> merge 2.3 into master

- appinfo/info.xml
This PR adds support for nc master which is now `27`
> Add support for NC master

- appinfo/info.xml
This PR updates the version of the app to `2.3.4`
> Update the version in info xml

- .github/workflows/ci.yml
- appinfo/info.xml
merge all from release/2.3 branch into master, including some conflict resolutions as part of release process of 2.3.4
> Merge release2.3 to master

- .github/workflows/ci.yml
- tests/lib/Service/OpenProjectAPIServiceTest.php
This PR backports https://github.com/nextcloud/integration_openproject/pull/393
Also runs tests in Ci with nextcloud master
> Backport Fix unit test failing on CI

- appinfo/info.xml
Thi Pr updates the version of app to `2.3.5` for patch release
> Update version of the app for patch release

- .github/workflows/ci.yml
- .github/workflows/release.yml
- appinfo/info.xml
- lib/Controller/DirectUploadController.php
- lib/Exception/OpenprojectUnauthorizedUserException.php
- lib/Service/DirectUploadService.php
- tests/lib/Controller/DirectUploadControllerTest.php
This PR merges the release/2.3 branch to master. There were some conflicts, which were resolved by this PR
> Merge release/2.3 to master

- src/views/ProjectsTab.vue
Related workpackage[OP#48155]: https://community.openproject.org/projects/nextcloud-integration/work_packages/48155/activity
> [OP#48155]Fix the position of the unlink button

- .github/workflows/ci.yml
- .github/workflows/release.yml
The master of nextcloud is now 28 so we'll have a error in CI saying that this app is not compatible for master, so change the master to `stable27`
> Replace `master` branch in ci with `stable27`

- appinfo/info.xml
Prepare for patch release `2.3.7` by updating the version of the app
> update the version of the app for patch release

- appinfo/info.xml
For the release of the patch version of `2.3` merge the release branch with master by resolving conflicts
> Merge release-2.3 into master

- lib/Service/OpenProjectAPIService.php
- src/components/AdminSettings.vue
- src/components/admin/ProjectFolderError.vue
- tests/jest/components/AdminSettings.spec.js
- tests/lib/Service/OpenProjectAPIServiceTest.php
This PR makes changes according to figma in the UI.
figma : https://www.figma.com/file/gtLQfPe09X7XugAH8L7dTy/Nextcloud-Integration?type=design&node-id=3663-101659
https://community.openproject.org/projects/817/work_packages/48444/activity
> [OP#48444] Make changes according to figma in UI

- integration_setup.sh
- lib/Controller/ConfigController.php
- lib/Controller/OpenProjectAPIController.php
This PR adjust the bash script for whole set up integration since now we have an option to set the integration.
1. with project folder setup
2. without project folder setup
This PR adds and extra environment `SETUP_PROJECT_FOLDER` where admin can set the with or without the project folder setup. 
https://community.openproject.org/projects/nextcloud-integration/work_packages/48445/activity?query_id=3787
> [OP#48445]Update integration script according to project folder setup

- README.md
This PR updates the readme file according to newly updated feature for `project folder` setup
https://community.openproject.org/projects/nextcloud-integration/work_packages/48750/activity?query_id=3787
> [OP#48750]Update readme according to the `project folder` setup

- src/components/AdminSettings.vue
- tests/jest/components/AdminSettings.spec.js
- tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
Related work package [OP#49217] : https://community.openproject.org/projects/nextcloud-integration/work_packages/49217
There were some text changes made in the Projects folder setup, so this PR updates those
> [OP#49217] Update texts for project folders setup

- .tx/backport
Allow transifex to push on release-2.4 branch
> Allow transifex to write on release 2.4 branch

- .tx/backport
Backport : https://github.com/nextcloud/integration_openproject/pull/450
> Backport allow transifex to write on release 2.4 branch

- appinfo/info.xml
Update the version of the app to `2.4.2` for the release
> update the version of the app to 2.4.2

- src/components/AdminSettings.vue
[OP#49766] : https://community.openproject.org/projects/nextcloud-integration/work_packages/49766
> [OP#49766] translate an untranslated string 

- lib/Controller/ConfigController.php
- lib/Service/OpenProjectAPIService.php
- tests/acceptance/features/api/setup.feature
fixes: [OP#45456]  https://community.openproject.org/work_packages/45456
> [OP#45456] Make the setup API not return 500 errors

- src/components/tab/SearchInput.vue
Forward port of this PR: https://github.com/nextcloud/integration_openproject/pull/474 to `master` branch
> [WP#49787]Remove the function for emptying search input

- appinfo/info.xml
https://community.openproject.org/projects/nextcloud-integration/work_packages/49785/
> Update app description to contain latest changes

- src/components/AdminSettings.vue
[OP#49766] : https://community.openproject.org/projects/nextcloud-integration/work_packages/49766
backport:
https://github.com/nextcloud/integration_openproject/pull/467
> [OP#49766][backport-467] translate an untranslated string

- lib/AppInfo/Application.php
- lib/Capabilities.php
- tests/acceptance/features/api/capabilities.feature
- tests/acceptance/features/bootstrap/FeatureContext.php
backport: https://github.com/nextcloud/integration_openproject/pull/472
> [Backport/472] Add capabilities

- appinfo/info.xml
Update the version of the app to `2.4.3` for patch release
> Update the version of the app to 2.4.3

- appinfo/info.xml
As the previous release didn't go through, update the version of the app to `2.4.4` for new patch level release
> Update the version of the app to 2.4.4

- .github/workflows/release.yml
- README.md
- appinfo/info.xml
- integration_setup.sh
- src/components/AdminSettings.vue
- src/components/tab/WorkPackage.vue
There were some conflicts while trying to merge `release/2.4` branch to master so this PR resolves those conflicts to merge the changes from release branch to master
> Merge release/2.4 to master

- tests/lib/Controller/OpenProjectAPIControllerTest.php
There were no test coverage for this function so add more test covergae
> add phpunit tests for linking the workpackage

- appinfo/info.xml
Update the version of the app to `2.4.5` to release a patch version
> Update the version of the app to 2.4.5

- .github/workflows/ci.yml
- appinfo/info.xml
- lib/Controller/FilesController.php
- tests/lib/Controller/FilesControllerTest.php
This PR merges the changes release branch to master. There were some conflicts while trying to make the PR from release/2.4 to master so this PR is to merge the recently made changes from release branch to master
> Merge the changes release/2.4 to master

- lib/Listener/BeforeNodeInsideOpenProjectGroupfilderChangedListener.php
Fixes : https://community.openproject.org/projects/openproject/work_packages/50135/activity
> [WP#50135]Fix the delete files in shared link

- appinfo/info.xml
Patch release for the app from `2.4.5` to `2.4.6`
> Increase version of app for patch release

- appinfo/info.xml
- lib/Controller/FilesController.php
- lib/Listener/BeforeNodeInsideOpenProjectGroupfilderChangedListener.php
- lib/Service/OpenProjectAPIService.php
- tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
- tests/acceptance/features/api/getFilesinfoByFileIDsAPI.feature
- tests/lib/Controller/FilesControllerTest.php
Merge changes related to 2.4 to master
> Merge changes in 2.4 to master

- .github/workflows/ci.yml
For `release/2.4` branch the CI is also freezes out so this PR change the NC image.
> Change image for the NC

- .github/workflows/ci.yml
Backport of PR: https://github.com/nextcloud/integration_openproject/pull/532
> Downgrade nextcloud image in CI

- .github/scripts/notify-to-element.sh
This PR adds the extra checks for the nightly incase of skipped or cancelled.
> Check for cancelled, skipped in the nightly report script

- css/dashboard.css
- css/tab.css
Fixes Work Package: https://community.openproject.org/projects/nextcloud-integration/work_packages/51409
After UI change:
https://community.openproject.org/projects/nextcloud-integration/work_packages/51409
> [WP#51409]Fix the layout for the label in the actions

- integration_setup.sh
Same as this PR https://github.com/nextcloud/integration_openproject/pull/519 with some changes in response check in the script since it broke in setting up group folders.
> Improve debuggability/in script

- lib/Controller/ConfigController.php
- lib/Service/OpenProjectAPIService.php
- tests/lib/Controller/ConfigControllerTest.php
- tests/lib/Service/OpenProjectAPIServiceTest.php
Forward port of PR: https://github.com/nextcloud/integration_openproject/pull/530
> Make the min password length dynamic instead of hardcoded one

- src/views/CreateWorkPackageModal.vue
> fix(i18n): Changed spelling of product name "Nextcloud"

- appinfo/info.xml
Updated the app released version from `2.5` to `2.5.0` as standard.
> Change app version to 2.5.0

- .github/workflows/nighlty-ci-release-branch.yml
Run nightly CI workflow for branch `release/2.5`
> Run nightly CI on 2.5 branch

- .tx/backport
backport : https://github.com/nextcloud/integration_openproject/pull/545
> Allow transifex to write on release 2.5 branch

- appinfo/info.xml
change version from 2.5.0 to 2.5.1
> Change app version to 2.5.1

- README.md
- appinfo/info.xml
This PR adds some missed description of the feature of application in the `readme` as well as `appinfo`.
> Update missed feature description of app

- README.md
This PR updates `README.md` documentation for the `release preparation` and `publish release`
> Update readme for `release preparation` and `publish release`

- CHANGELOG.md
- appinfo/info.xml
The App details in the `nextcloud` app store seems to be according to the change log file. This PR adds just a change log for version `2.6.0`. It will be followed by a Publish nightly release to appstore to check if it works.
https://community.openproject.org/projects/nextcloud-integration/work_packages/52112
> Added change log details

- CHANGELOG.md
This PR just updates the tag in change log containing nighlty to check as proof in the app store details before stable release.
> Change the version having nightly in changelog

- .github/workflows/nighlty-ci-release-branch.yml
- .tx/backport
- CHANGELOG.md
This PR includes necessary updates required for the minor `release/2.6` of the application
> Prepare for minor release/2.6

- README.md
Forward Port: https://github.com/nextcloud/integration_openproject/pull/562
> [WP#52241]update doc for release preparation and also after release

- .github/pull_request_template.md
This PR adds a PR template whenever making a pull request for this repository.
https://community.openproject.org/projects/nextcloud-integration/work_packages/43830/activity
> [WP#43830]Add pull request template for integration app

- .github/pull_request_template.md
Forward port: https://github.com/nextcloud/integration_openproject/pull/563
> Add a good PR template for a pull request

- .github/workflows/shared_workflow.yml
- lib/Controller/ConfigController.php
- makefile
- tests/acceptance/config/behat.yml
- tests/acceptance/features/api/directUpload.feature
- tests/acceptance/features/api/setup.feature
- tests/acceptance/features/bootstrap/DirectUploadContext.php
- tests/acceptance/features/bootstrap/FeatureContext.php
- tests/acceptance/features/bootstrap/FilesVersionsContext.php
This PR adds the test for checking the file version in normal folder and group folder
In this PR following scenario are added:
- upload file and version is available inside normal folder
- upload a file twice with different content and versions are available inside normal folder
- upload file and no version is available inside group folder
- upload a file twice with different content and version are available inside group folder
> add tests for file version

- README.md
- makefile
In this PR , docs is added which is about running API test
> add docs for api-test

- .github/workflows/shared_workflow.yml
- lib/Controller/ConfigController.php
- makefile
- tests/acceptance/config/behat.yml
- tests/acceptance/features/api/directUpload.feature
- tests/acceptance/features/api/setup.feature
- tests/acceptance/features/bootstrap/DirectUploadContext.php
- tests/acceptance/features/bootstrap/FeatureContext.php
- tests/acceptance/features/bootstrap/FilesVersionsContext.php
This PR is backport of master PR https://github.com/nextcloud/integration_openproject/pull/553
> Backport add api test for file version

- README.md
In this PR the readme file is updated. The note for api-test is placed inside the api-test
> readme file note replace for api-test

- README.md
- makefile
This PR backport the master PR https://github.com/nextcloud/integration_openproject/pull/565  https://github.com/nextcloud/integration_openproject/pull/568
> Backport docs for api test

- src/components/AdminSettings.vue
- src/views/LinkMultipleFilesModal.vue
- src/views/ProjectsTab.vue
In this PR the loading icon of vue is replaced to loading icon of nextcloud
https://community.openproject.org/work_packages/51380/activity
> [ WP#51380] loading icon change to nexcloud loading icon

- src/components/AdminSettings.vue
- src/views/LinkMultipleFilesModal.vue
- src/views/ProjectsTab.vue
This PR is backport from master PR https://github.com/nextcloud/integration_openproject/pull/561
> Backport loading icon change to nexcloud loading icon

- src/components/AdminSettings.vue
> fix(i18n): host name -> hostname

- CHANGELOG.md
This PR updates the missing `CHANGELOG.md` for next release.
https://community.openproject.org/projects/nextcloud-integration/work_packages/52632
> [WP#52632]Update unreleased changes on CHANGELOG.md

- CHANGELOG.md
- appinfo/routes.php
- lib/AppInfo/Application.php
- lib/Controller/ConfigController.php
- lib/Listener/TermsOfServiceEventListener.php
- lib/Service/OpenProjectAPIService.php
- lib/Settings/Admin.php
- phpstan.neon
- src/components/AdminSettings.vue
- src/components/admin/TermsOfServiceUnsigned.vue
- tests/jest/components/AdminSettings.spec.js
- tests/jest/components/admin/TermsOfServices.spec.js
- tests/lib/Controller/ConfigControllerTest.php
- tests/lib/Service/OpenProjectAPIServiceTest.php
Backport of PR: https://github.com/nextcloud/integration_openproject/pull/552
> Added TOS app enabled and set TOS for OP user (#552)

- CHANGELOG.md
- appinfo/info.xml
This PR makes changes for the release preparation for patch release of the app with version `2.6.1`
> Release preparation for 2.6.1

- src/components/admin/TermsOfServiceUnsigned.vue
> fix(i18n): Fixed typo and wording

- src/components/admin/TermsOfServiceUnsigned.vue
Backport of PR: https://github.com/nextcloud/integration_openproject/pull/586
> Fixed typo and wording for terms of services description

- src/components/tab/EmptyContent.vue
- src/views/Dashboard.vue
In this PR, the `!` character is removed from the dashboard content
- [issue-link](https://community.openproject.org/projects/nextcloud-integration/work_packages/53430/activity?query_props=%7B%22c%22%3A%5B%22id%22%2C%22subject%22%2C%22type%22%2C%22status%22%2C%22assignee%22%5D%2C%22hi%22%3Atrue%2C%22g%22%3A%22%22%2C%22is%22%3Atrue%2C%22tv%22%3Afalse%2C%22hla%22%3A%5B%22status%22%2C%22priority%22%2C%22dueDate%22%5D%2C%22t%22%3A%22id%3Aasc%22%2C%22f%22%3A%5B%7B%22n%22%3A%22status%22%2C%22o%22%3A%22o%22%2C%22v%22%3A%5B%5D%7D%5D%2C%22ts%22%3A%22PT0S%22%2C%22pp%22%3A50%2C%22pa%22%3A2%7D)
> removed ! character from dashboard content

- CHANGELOG.md
- src/components/AdminSettings.vue
This PR is backport of master [PR](https://github.com/nextcloud/integration_openproject/pull/581)
> Backport - change url for groupfolder apps on admin tab (#581)

- CHANGELOG.md
- css/dashboard.css
- src/components/tab/EmptyContent.vue
- src/components/tab/WorkPackage.vue
- src/views/Dashboard.vue
Backports of PRs: https://github.com/nextcloud/integration_openproject/pull/585,  https://github.com/nextcloud/integration_openproject/pull/590, https://github.com/nextcloud/integration_openproject/pull/583
> Backport/ux UI prs

- src/components/AdminSettings.vue
- tests/jest/components/AdminSettings.spec.js
Backport PR: https://github.com/nextcloud/integration_openproject/pull/595
> [backport]Remove only from admin setting tests

- CHANGELOG.md
- src/components/tab/SearchInput.vue
- src/utils.js
- tests/jest/components/tab/SearchInput.spec.js
Backport of PR: https://github.com/nextcloud/integration_openproject/pull/582
> [backport]Backport/no option text

- src/components/tab/SearchInput.vue
Forward port of this PR: https://github.com/nextcloud/integration_openproject/pull/597
> [fowward-port]Used the NcButton for create Workpackage

- tests/jest/components/tab/SearchInput.spec.js
Foward port PR: https://github.com/nextcloud/integration_openproject/pull/601
> [forward-port]Remove only from tests

- CHANGELOG.md
- src/components/AdminSettings.vue
- src/components/PersonalSettings.vue
- src/components/settings/CheckBox.vue
- src/utils.js
- tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
- tests/jest/components/__snapshots__/PersonalSettings.spec.js.snap
This PR adds a user description for the user settings for each check box in the admin section and the personal section of the app.
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/52959
> [WP#52959]Added desciption for the checkbox in the usersettings

- CHANGELOG.md
Duplicate points on changelog.md is remove from changelog.md file
> remove duplicate points from changelog

- src/components/tab/SearchInput.vue
- tests/jest/components/tab/SearchInput.spec.js
Change description as per this comment: https://community.openproject.org/work_packages/52956/activity
- Fixes (https://community.openproject.org/work_packages/52956/activity)
> Change the workpackage not found description

- src/utils.js
- tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
- tests/jest/components/__snapshots__/PersonalSettings.spec.js.snap
Change the checkbox description text according to this comment https://community.openproject.org/work_packages/52959/activity 
- Fixes https://community.openproject.org/work_packages/52959/activity
> Change checkbox description text

- src/components/AdminSettings.vue
- src/components/PersonalSettings.vue
- src/components/settings/SettingsTitle.vue
- tests/jest/components/AdminSettings.spec.js
- tests/jest/components/PersonalSettings.spec.js
This PR adjust the documentation section changes according to the latest comment in https://community.openproject.org/projects/nextcloud-integration/work_packages/52955/activity?query_id=5136
- Fixes (https://community.openproject.org/projects/nextcloud-integration/work_packages/52955/activity?query_id=5136)
> [review-adjustment]Adjust the documentation link according to review

- appinfo/info.xml
Update version from `2.6.1` to `2.6.2` for patch release
> Update version from 2.6.1 to 2.6.2 for patch release

- CHANGELOG.md
- src/components/AdminSettings.vue
Forward port PR : https://github.com/nextcloud/integration_openproject/pull/606 and resolve conflict.
> Forwardport unported prs

- CHANGELOG.md
Update `CHANGELOG.MD` for release preparation release `2.6.2`
> Update `CHANGELOG.MD` for release preparation

- CHANGELOG.md
Forward port PR :  https://github.com/nextcloud/integration_openproject/pull/618
> Update changelog for release preparation

- .github/workflows/shared_workflow.yml
First Phase: 
This PR drops the support for NC-25 from our application in the CI.
https://community.openproject.org/projects/nextcloud-integration/work_packages/53958
> Drop support for NC-25 in CI

- .github/workflows/release.yml
- .github/workflows/shared_workflow.yml
- appinfo/info.xml
- tests/acceptance/features/api/capabilities.feature
This PR will add support for `nextcloud-stable29` in CI and also drops version for 25 of nextcloud
https://community.openproject.org/projects/nextcloud-integration/work_packages/53991
> [WP#53991]Support NC 29

- lib/Listener/TermsOfServiceEventListener.php
- lib/Reference/WorkPackageReferenceProvider.php
- phpstan.neon
- tests/lib/Reference/WorkPackageReferenceProviderTest.php
This PR clean up code related to `php7.4` support to run tests in CI.
https://community.openproject.org/projects/nextcloud-integration/work_packages/48598/activity
> [WP#48598]Drop support for php7.4 and clean up code

- .github/workflows/shared_workflow.yml
- CHANGELOG.md
- css/dashboard.css
- lib/Dashboard/OpenProjectWidget.php
- tests/lib/Service/OpenProjectAPIServiceTest.php
This PR backports: https://github.com/nextcloud/integration_openproject/pull/622 https://github.com/nextcloud/integration_openproject/pull/620
> Backport drop support nc 25 (from CI and Code)

- .github/workflows/release.yml
- .github/workflows/shared_workflow.yml
- appinfo/info.xml
- tests/acceptance/features/api/capabilities.feature
This PR backports : 
https://github.com/nextcloud/integration_openproject/pull/621
> Backport Support NC 29 in `release/2.6`

- CHANGELOG.md
- appinfo/info.xml
Release preparation for version `2.6.3`
> Release preparation for version `2.6.3`

- CHANGELOG.md
- appinfo/info.xml
This PR is the forward PR #629
> ForwardPort Release preparation for 2.6.3

- .github/workflows/release.yml
This PR updates the php version for the app release workflow from `8.1` to `8.2`.
We might need to release a nightly-release (Unstable) to check that 8.2 works fine for the release workflow.
> Update php version to `8.2` for release workflow for app release

- .github/workflows/shared_workflow.yml
- tests/acceptance/features/bootstrap/FeatureContext.php
CI is flaky at deleting user for API tests.
- https://community.openproject.org/work_packages/52406/activity
> refactor-on-user-creation-carol

- .github/workflows/shared_workflow.yml
- tests/acceptance/features/bootstrap/FeatureContext.php
backport of PR https://github.com/nextcloud/integration_openproject/pull/634
> Backport flaky ci PR

- .github/workflows/shared_workflow.yml
- lib/AppInfo/Application.php
- lib/Listener/LoadAdditionalScriptsListener.php
- lib/Service/OpenProjectAPIService.php
- psalm.xml
- tests/acceptance/features/bootstrap/FeatureContext.php
- tests/lib/Controller/ConfigControllerTest.php
- tests/lib/Reference/WorkPackageReferenceProviderTest.php
- tests/stub.phpstub
This PR Backport from the master PR
https://github.com/nextcloud/integration_openproject/pull/642
> [Backport] use psalm in all NC version and remove phpstan in CI

- .github/workflows/shared_workflow.yml
This PR make API test run in CI with version `8.3`
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/55365
> [WP#55365]Run PHP 8.3 in CI for API test

- composer.json
- composer.lock
- lib/AppInfo/Application.php
- lib/Controller/FilesController.php
- lib/Listener/BeforeNodeInsideOpenProjectGroupfilderChangedListener.php
- lib/Listener/LoadSidebarScript.php
- lib/Listener/OpenProjectReferenceListener.php
- lib/Listener/TermsOfServiceEventListener.php
- lib/Search/OpenProjectSearchProvider.php
- lib/Service/OpenProjectAPIService.php
- makefile
- phpstan.neon
- tests/acceptance/features/bootstrap/DirectUploadContext.php
- tests/acceptance/features/bootstrap/FeatureContext.php
- tests/acceptance/features/bootstrap/FilesVersionsContext.php
- tests/acceptance/features/bootstrap/GroupfoldersContext.php
- tests/acceptance/features/bootstrap/SharingContext.php
- tests/lib/Controller/OpenProjectAPIControllerTest.php
- tests/lib/Service/OpenProjectAPIServiceTest.php
In this PR, phpstan is completly removed from following file
```console
lib/AppInfo/Application.php
lib/Controller/FilesController.php
lib/Listener/BeforeNodeInsideOpenProjectGroupfilderChangedListener.php
lib/Listener/LoadSidebarScript.php
lib/Listener/OpenProjectReferenceListener.php
lib/Listener/TermsOfServiceEventListener.php
lib/Search/OpenProjectSearchProvider.php
lib/Service/OpenProjectAPIService.php
tests/acceptance/features/bootstrap/DirectUploadContext.php
tests/acceptance/features/bootstrap/FeatureContext.php
tests/acceptance/features/bootstrap/FilesVersionsContext.php
tests/acceptance/features/bootstrap/GroupfoldersContext.php
tests/acceptance/features/bootstrap/SharingContext.php
tests/lib/Controller/OpenProjectAPIControllerTest.php …
```
> phpstan removed from the code

- integration_setup.sh
This PR:
- Adds check for the file storage completion in `OpenProject` when we are rerunning the script again with the same storage name.
- Adds check for checking OpenProject version >= 14.2.0 in the script, from now the script will only run for OP version >= 14.2.0  
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/55363
> [WP#55363]Update script according to extended `OpenProject` API

- integration_setup.sh
This PR improves the wording or log messages that resides within the `integration_script.sh` file in order to make it more clear and concise for a user using it.
- Fixes (https://community.openproject.org/projects/nextcloud-integration/work_packages/55514)
> [WP#55514]Improve wording/log messsages

- .github/scripts/notify-to-element.sh
- .github/workflows/release.yml
- .github/workflows/shared_workflow.yml
This PR backports following master PRs
- https://github.com/nextcloud/integration_openproject/pull/631
- https://github.com/nextcloud/integration_openproject/pull/635
- https://github.com/nextcloud/integration_openproject/pull/636
> Backport the master PRs

- docs/release.md
- docs/testing/smoke_testing.md
This PR adds some of the somke testing to be done manually during the time of the major, minor and patch (as per requirement) release of the integration application. The need for this test plan is because our application lacks end to end integration testing where both `Nextcloud` and `OpenProject` instances are involved.
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/52631/activity
> Some test plan for integration feature

- CHANGELOG.md
- src/components/tab/SearchInput.vue
This PR:
- Make the text of the button more readable when we select dark theme along with NC's different background images  
- Fixes (https://community.openproject.org/projects/nextcloud-integration/work_packages/56067)
> Fix color for text when background is changed

- docs/testing/smoke_testing.md
Cherry picking the commit of this PR: https://github.com/nextcloud/integration_openproject/pull/668
> update smoke test docs

- CHANGELOG.md
- lib/Exception/OpenprojectAvatarErrorException.php
- lib/Service/OpenProjectAPIService.php
- tests/lib/Service/OpenProjectAPIServiceTest.php
- https://community.openproject.org/work_packages/56254
> [WP #56254] Bug fixed related to avatar not found

- .github/workflows/shared_workflow.yml
In this PR, the CI is made to run the API-test to run with php 8.0
> make api-test run in php8.0 on CI

- .github/workflows/shared_workflow.yml
In this PR, Image sources change to prevent the docker pull limit.
- https://community.openproject.org/projects/nextcloud-integration/work_packages/56511
> [WP #56511] CI/change the image source

- .github/workflows/release.yml
- .github/workflows/shared_workflow.yml
- phpunit.xml
There is 3 failure in CI in which 1 and 2 cames frequently but 3 cames repeatedly. So, this PR fixed the CI failure.
The errors are:
1. Error related to the mock server
```console
There was 1 error:
1) OCA\OpenProject\Service\OpenProjectAPIServiceTest::testGetAvailableAssigneesOfAProjectPact
PhpPact\Consumer\Exception\MockServerNotStartedException: The mock server could not be started
/home/runner/work/integration_openproject/integration_openproject/server/apps/integration_openproject/vendor/pact-foundation/pact-php/src/PhpPact/Consumer/Service/MockServer.php:35
/home/runner/work/integration_openproject/integration_openproject/server/apps/integration_openproject/vendor/pact-foundation/pact-php/src/PhpPact/Consumer/Driver/Interaction/InteractionDriver.php:50 …
```
> fixed CI failure

- phpunit.xml
Changing the port for the mock_server_host
```console
There was 1 error:
1) OCA\OpenProject\Service\OpenProjectAPIServiceTest::testGetOpenProjectAvatarWithNoContentType
PhpPact\Consumer\Exception\MockServerNotStartedException: The mock server could not be started
/home/runner/work/integration_openproject/integration_openproject/server/apps/integration_openproject/vendor/pact-foundation/pact-php/src/PhpPact/Consumer/Service/MockServer.php:35
/home/runner/work/integration_openproject/integration_openproject/server/apps/integration_openproject/vendor/pact-foundation/pact-php/src/PhpPact/Consumer/Driver/Interaction/InteractionDriver.php:50
/home/runner/work/integration_openproject/integration_openproject/server/apps/integration_openproject/vendor/pact-foundation/pact-php/src/PhpPact/Consumer/I …
```
> change the port number to 7300

- .github/workflows/release.yml
- .github/workflows/shared_workflow.yml
- phpunit.xml
This PR backport the following two PR:
1. https://github.com/nextcloud/integration_openproject/pull/677
2. https://github.com/nextcloud/integration_openproject/pull/676
> [Backport] Ci/fixed failure

- .github/workflows/shared_workflow.yml
Due to a problem with the docker limit rate for pulling the image, PGSQL was taken off of CI. Adding the SQL again to the CI after resolving the issue.
> add pgsql in the API-test for CI

- CHANGELOG.md
> edit in changelog

- .github/workflows/shared_workflow.yml
Forward port of PR: https://github.com/nextcloud/integration_openproject/pull/681
> Change branch from master to stable30 in CI

- .github/workflows/release.yml
- CHANGELOG.md
- appinfo/info.xml
forward port https://github.com/nextcloud/integration_openproject/pull/683
> [forward-port] add gd extension in release workflows

- integration_setup.sh
This PR includes changes of this PR : https://github.com/nextcloud/integration_openproject/pull/671
> Fix intendation for script `integration_setup.sh`

- .github/workflows/nighlty-ci-release-branch.yml
- .tx/backport
- CHANGELOG.md
- appinfo/info.xml
- package.json
Release Preparation for `integration_openproject` `2.7.0`
> Release preparation for `integration_openproject` `2.7.0`

- .github/workflows/nighlty-ci-release-branch.yml
- .tx/backport
- CHANGELOG.md
- appinfo/info.xml
- package.json
This PR forward ports release prep for `2.7.0` to `master` https://github.com/nextcloud/integration_openproject/pull/701
> [forward-port]Release preparation for 2.7.0

- src/components/AdminSettings.vue
Forward port of PR: https://github.com/nextcloud/integration_openproject/pull/708
> Fix retry icon color in dark mode

- CHANGELOG.md
- integration_setup.sh
This PR forward port the PR : https://github.com/nextcloud/integration_openproject/pull/707 and https://github.com/nextcloud/integration_openproject/pull/711 to `master` branch
> Update script according to storage API response of openproject (#707)

- .github/workflows/shared_workflow.yml
- composer.json
- composer.lock
Backport the master PR https://github.com/nextcloud/integration_openproject/pull/721
> [Backport] update username and add on composer file

- lib/Service/OauthService.php
- tests/lib/Service/OauthSeviceTest.php
Bacport of master PR
https://github.com/nextcloud/integration_openproject/pull/723
> [Backport] Fix version comparison (#723)

- CHANGELOG.md
- appinfo/info.xml
Release preparation for version `2.7.1`
> release preparation for 2.7.1

- lib/Controller/FilesController.php
Backport of PR: https://github.com/nextcloud/integration_openproject/pull/736
> Backport/change log info from `master` to `release/2.7`

- .github/workflows/shared_workflow.yml
- appinfo/routes.php
- composer.json
- composer.lock
- lib/AppInfo/Application.php
- lib/Controller/ConfigController.php
- lib/Controller/DirectDownloadController.php
- lib/Controller/FilesController.php
- lib/Controller/OpenProjectAPIController.php
- lib/Dashboard/OpenProjectWidget.php
- lib/Listener/OpenProjectReferenceListener.php
- lib/Service/DirectDownloadService.php
- lib/Service/OauthService.php
- lib/Service/OpenProjectAPIService.php
- tests/lib/Controller/DirectUploadControllerTest.php
- tests/lib/Controller/OpenProjectAPIControllerTest.php
- tests/lib/Service/DatabaseServiceTest.php
- tests/lib/Service/DirectDownloadServiceTest.php
- tests/lib/Service/DirectUploadServiceTest.php
- tests/lib/Service/OauthSeviceTest.php
- tests/lib/Service/OpenProjectAPIServiceTest.php
- tests/lib/Settings/PersonalTest.php
This PR backport the master PRs:
- https://github.com/nextcloud/integration_openproject/pull/741
- https://github.com/nextcloud/integration_openproject/pull/740
- https://github.com/nextcloud/integration_openproject/pull/693
> [Backport] update php-cs-fixer version #741

- src/views/CreateWorkPackageModal.vue
As shown in the above figure, some UI improvements are needed, such as:
- labels are shifted way above
- subject label's dropdown is larger compared to the other dropdowns.
- text area borders for the subject and description appear larger than those of other text areas.
So, this PR addresses and fixes all these issues. The following UI improvements have been made in this PR:
- subject text field size is adjusted to match the other text fields.
- labels are shifted slightly downward.
- text area border sizes for the subject and description are adjusted for consistency.
-  https://community.openproject.org/projects/nextcloud-integration/work_packages/59756
Before
After
> [UI] fixed the subject input filed

- src/components/tab/WorkPackage.vue
- src/views/CreateWorkPackageModal.vue
This PR backports the master PRs related to the UI/UX improvements
- #744 
- #743
> [Backport] UI/UX improvement

- CHANGELOG.md
- appinfo/info.xml
- Updated version to `2.7.2`
- Added the changelogs
> chore: prepare release 2.7.2

- .github/workflows/release.yml
Release nightlies as a pre-release not as an actual release.
> ci: mark nightly releases as pre-release

- .gitignore
- README.md
- dev/.env
- dev/compose.yaml
- dev/keycloak.yaml
- dev/nextcloud.sh
- dev/openproject.sh
- dev/ssl.sh
- dev/step.sh
- docs/setup_nc_op__full.md
Added nextcloud-openproject full setup with optional keycloak service.
- HTTPS enabled
- Script to add certs to the system and the browser
> build: full nextcloud-openproject docker compose deployment

- .github/workflows/release.yml
- .gitignore
- README.md
- dev/.env
- dev/compose.yaml
- dev/keycloak.yaml
- dev/nextcloud.sh
- dev/openproject.sh
- dev/ssl.sh
- dev/step.sh
- docs/setup_nc_op__full.md
- l10n/ko.js
- l10n/ko.json
Bring #748 and #749 to the master
> chore: merge back release/2.7 branch

- src/components/PersonalSettings.vue
- src/constants/appID.js
- src/constants/messages.js
- src/views/Dashboard.vue
Reword error message:
```diff
-This feature is not available for this user account :)
+This feature is not available for this user account
```
- Fixes [WP#60496](https://community.openproject.org/projects/nextcloud-integration/work_packages/60496)
> refactor: reword error message

- .github/workflows/nighlty-ci-release-branch.yml
- .github/workflows/shared_workflow.yml
Do not run CI for nextcloud master if stable branch.
> ci: skip nextcloud master branch in release branches

- CHANGELOG.md
- appinfo/info.xml
- package.json
> chore: prepare release 2.7.3

- tests/lib/Service/OpenProjectAPIServiceTest.php
- create a construct params helper to be able to modify any param easily
- renamed `getServiceMock` -> `getOpenProjectAPIServiceMock`
> test: refactor OpenProjectAPIService class unit tests

- CHANGELOG.md
Added changelog for https://github.com/nextcloud/integration_openproject/pull/756
> chore: add changelog entry

- tests/jest/views/Dashboard.spec.js
- tests/jest/views/__snapshots__/Dashboard.spec.js.snap
Extended unit tests for Dashboard component
- [WP#60395](https://community.openproject.org/wp/60395)
> test: extend unit tests for Dashboard component

- CHANGELOG.md
- src/utils/workpackageHelper.js
- src/views/Dashboard.vue
- tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap
- tests/jest/views/__snapshots__/Dashboard.spec.js.snap
properly encode dynamic avatar url params
- [WP#61174](https://community.openproject.org/wp/61174)
Before | Now
--|--
> fix: proper avatar url encoding

- docs/release.md
> docs: update release docs

- .github/workflows/shared_workflow.yml
In this PR, there is update of ubuntu runner image form `20.04` to `22.04`
- https://community.openproject.org/projects/nextcloud-integration/work_packages/61601
> CI: update ubuntu image from 20.04 to 22.04

- CHANGELOG.md
- appinfo/routes.php
- lib/Controller/OpenProjectAPIController.php
- lib/Controller/OpenProjectController.php
- lib/Service/OpenProjectAPIService.php
- src/components/AdminSettings.vue
- src/components/tab/SearchInput.vue
- src/utils/workpackageHelper.js
- src/views/CreateWorkPackageModal.vue
- src/views/Dashboard.vue
- src/views/LinkMultipleFilesModal.vue
- src/views/ProjectsTab.vue
- src/views/WorkPackagePickerElement.vue
- tests/jest/components/tab/SearchInput.spec.js
- tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap
- tests/jest/views/CreateWorkpackageModal.spec.js
- tests/jest/views/Dashboard.spec.js
- tests/jest/views/LinkMultipleFilesModal.spec.js
- tests/jest/views/ProjectsTab.spec.js
- tests/jest/views/__snapshots__/Dashboard.spec.js.snap
- tests/lib/Controller/OpenProjectAPIControllerTest.php
- tests/lib/Controller/OpenProjectControllerTest.php
- tests/lib/Service/OpenProjectAPIServiceTest.php
> chore: port PRs #769 and #767

- .github/workflows/nighlty-ci-release-branch.yml
- .tx/backport
- CHANGELOG.md
- appinfo/info.xml
- package.json
- Updated version to `2.8` on `nightly-CI`, `appinfo/info.xml` and `package.json`
- Added the changelogs
- Added the `release/2.8` on `.tx`
> chore: bump version to 2.8

- lib/Settings/Admin.php
> fix: add missing admin-settings-config state change 

- .github/workflows/nighlty-ci-release-branch.yml
- .tx/backport
- CHANGELOG.md
- appinfo/info.xml
- package.json
Merge back necessary changes from release/2.8 branch
> chore: merge back release/2.8

- .github/workflows/shared_workflow.yml
- CHANGELOG.md
- appinfo/info.xml
- lib/Service/OauthService.php
- tests/lib/Service/OauthSeviceTest.php
This PR will drop NC27 support
- https://community.openproject.org/projects/nextcloud-integration/work_packages/61826
> drop Nextcloud 27 support

- .github/scripts/generate-matrix.sh
- .github/workflows/nighlty-ci-release-branch.yml
- .github/workflows/shared_workflow.yml
Generating CI jobs matrix dynamically using the provided NC and PHP versions. The generated matrixes are the same as the previous ones. The only difference is how the matrix is generated. With this, matrixes will generated by a script file.
With this implementation, we can independently specify different lists of supported NC versions for master and release branches. This means changes in the versions list of the master branch don't affect the release branch's nightly build.
Available settings:
```yml
with:
branch: release/2.8
nextcloud_versions: "27 28 29 30 31"
php_versions: "8.1 8.2"
with:
branch: master
nextcloud_versions: "28 29 30 31 master"
php_versions: "8.2 8.3"
```
Also, enables NC27 pipeline for release/2.8 branch
NOTE:
The matrix generator script is configurable using the env …
> ci: dynamic job matrix creation

- appinfo/info.xml
- package.json
- tests/acceptance/features/api/capabilities.feature
Bump version to next alpha on development branch
> chore: bump develop branch version

- .github/workflows/shared_workflow.yml
user_oidc app doesn't support NC27
> ci: do no try to install user_oidc app with NC27

- CHANGELOG.md
- lib/Service/OpenProjectAPIService.php
- tests/lib/Service/OpenProjectAPIServiceTest.php
Port https://github.com/nextcloud/integration_openproject/pull/780
> Fix: base url protocol

- CHANGELOG.md
- appinfo/info.xml
- package.json
- Updated version to `2.8.1` appinfo/info.xml` and `package.json`
- Added the changelogs
> chore: bump version to 2.8.1

- dev/.env
- dev/compose.yaml
- dev/nextcloud.sh
- dev/nextcloud/config.php
- dev/nextcloud/hooks/after-install.sh
- dev/nextcloud/hooks/before-install.sh
Port of https://github.com/nextcloud/integration_openproject/pull/776
> build: add NC compose setup to use specific server branch

- tests/lib/Service/OpenProjectAPIServiceTest.php
`withConsecutive` is not good at scaling. I have replaced it with the `willReturnMap` method. `willReturnMap` allows us to define a specific value per the parameters passed.
I have changed only `OpenProjectAPIServiceTest.php` file (desperately needed for #778). We can drop all occurances of `withConsecutive` in the future.
> test: drop withConsecutive and use willReturnMap

- .github/workflows/shared_workflow.yml
In this PR, there is separated js-lint and vue unit tests into a separate single job (Do not run them in all jobs)
- https://community.openproject.org/projects/nextcloud-integration/work_packages/61904/
> CI: add separate job for jest on ci

- .github/workflows/shared_workflow.yml
This PR corrects the job names by replacing the incorrect ones with the correct names.
> CI: adjust the wrong name of jobs on ci

- CHANGELOG.md
- lib/Controller/ConfigController.php
- lib/Service/OpenProjectAPIService.php
- lib/Settings/Admin.php
- src/components/AdminSettings.vue
- src/constants/links.js
- src/constants/messages.js
- src/utils.js
- tests/jest/components/AdminSettings.spec.js
- tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
- tests/lib/Service/OpenProjectAPIServiceTest.php
Support OIDC auth method for Nextcloud Hub setup
Depends on https://github.com/nextcloud/user_oidc/pull/1040
>[!Important]
>Required app versions:
>`oidc`: `1.4`
> `user_oidc`: `7.0`
>
> config.php:
>```php
>'user_oidc' => 
>  array (
>    'oidc_provider_token_generation' => true,
>    'oidc_provider_bearer_validation' => true,
>  ),
>```
- [WP#61319](https://community.openproject.org/wp/61319)
--|--
> feat: add option to configure with Nextcloud Hub

- .github/workflows/shared_workflow.yml
This PR backport the master PRs related to CI 
- https://github.com/nextcloud/integration_openproject/pull/792
- https://github.com/nextcloud/integration_openproject/pull/795
> [Backport] CI: add separate job for jest on ci

- integration_setup.sh
The setup script mostly consisted of space-indentation, but some tabs sneaked in as well. I replaced the tabs by spaces and fixed indentation to make sense. Indentation width seems to consistently be 2 spaces.
> Replace tabs by spaces

- .github/workflows/shared_workflow.yml
Since `PHP unit tes`t jobs and `API unit tests` jobs have some common steps, this PR merges them for simplicity and efficiency.
- [WP link](https://community.openproject.org/projects/nextcloud-integration/work_packages/61904/)
| Before (No. of jobs = 19)  | After (no. of jobs = 11)|
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/184e2863-3b9d-4dfa-8da2-df016b4a160b)  | ![image](https://github.com/user-attachments/assets/f9cc9605-b7f4-4d70-97fa-12c9bd9dd1fb)    |
> CI: merge API tests and PHP unit tests into a single job

- dev/compose.yaml
Enable basic auth for OpenProject APIV3
> build: enable basic auth in OP service

- .github/CODEOWNERS
- .github/CODEOWNERS.license
Currently everybody in the organization has the ability to review and merge PRs, this is quite broad access.
This PR sets up codeowners, and later we will set `Require review from Code Owners`  in the branch rule, so that only those people will be able to review code and by that allow a merge.
- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/61926
> setup codeowners for master branch

- tests/acceptance/features/api/directUpload.feature
Similar to https://github.com/nextcloud/integration_openproject/pull/806
- [WP#62654](https://community.openproject.org/wp/62654)
> test: fix quota test steps order

- src/components/AdminSettings.vue
- src/constants/messages.js
- tests/jest/components/AdminSettings.spec.js
- tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
Add hint text indicating the required OpenProject version and plan
- [WP#62748](https://community.openproject.org/wp/62748)
> feat: add hint for required OpenProject version and plan 

- .github/workflows/nighlty-ci-release-branch.yml
- .github/workflows/shared_workflow.yml
- .tx/backport
- CHANGELOG.md
- appinfo/info.xml
- package.json
> chore: prepare release 2.9

- .github/workflows/ci-workflow.yml
- .github/workflows/shared_workflow.yml
CI updates in this PR:
- Skip CI if only non-code files change
- Use OIDC tag 1.6.0 in CI (min supported version)
- https://community.openproject.org/projects/nextcloud-integration/work_packages/63780/activity
> CI: Skip CI for changes in docs and use OIDC tag 1.6.0

- .github/workflows/ci-workflow.yml
- .github/workflows/shared_workflow.yml
This PR is backport of master PR https://github.com/nextcloud/integration_openproject/pull/816
> [Backport] CI: Skip ci for docs

- CHANGELOG.md
Add changelog entry for required apps version
> chore: add changelog entry for required apps version 

- CHANGELOG.md
- src/components/AdminSettings.vue
Updated `authentication methods` guide link with correct link
> fix: correct authentication methods guide link

- src/components/AdminSettings.vue
- src/components/admin/FormOpenProjectHost.vue
- src/utils.js
- tests/jest/components/admin/FormOpenProjectHost.spec.js
- tests/jest/components/admin/__snapshots__/FormOpenProjectHost.spec.js.snap
Pass down `current-setting` prop to show or hide the form
> refactor: use current-setting prop to display form

- integration_oidc_setup.sh
OpenProject 16.0 has been released. Update the OpenProject minimum required version to 16.0 in the setup script
NOTE: other changes are code format fixes
> chore: fix OpenProject minimum required version to 16.0

- .github/workflows/nighlty-ci-release-branch.yml
- .github/workflows/shared_workflow.yml
- .tx/backport
- CHANGELOG.md
- appinfo/info.xml
- integration_oidc_setup.sh
- package.json
- src/components/AdminSettings.vue
> chore: merge release2.9

- .github/workflows/nighlty-ci-release-branch.yml
- .github/workflows/shared_workflow.yml
> ci: drop nc 28 and 29 CI pipelines

- .github/workflows/shared_workflow.yml
- composer.json
- composer.lock
- makefile
- tests/acceptance/features/api/directUpload.feature
In this PR, `behat/gherkin` version is upgraded
-  `v4.9.0` ==> `v4.12.0`
Also, removed php version `8.0` from CI
- https://community.openproject.org/projects/nextcloud-integration/work_packages/58517/
> Chore: Upgrade the behat/gherkin version

- CHANGELOG.md
- appinfo/info.xml
- package.json
- Updated version to `2.9.1` on appinfo/info.xml and package.json
- Added the changelogs
- https://community.openproject.org/projects/nextcloud-integration/work_packages/64415
> Chore: Bump version to 2.9.1

- tests/acceptance/features/bootstrap/FeatureContext.php
This PR fixes an issue where the user data directory is sometimes left behind after using the user delete API, either during normal deletion(return 200) or when the API returns a 500 status code. In such cases, the user gets deleted, but their data remains. This PR ensures the user data directory is properly removed in both scenarios.
<details>
<summary>500 status code Error Details</summary>
```xml
Status Code: 500
Error:
<?xml version="1.0"?>
<ocs>
<meta>
<status>failure</status>
<statuscode>996</statuscode>
<message>Internal Server Error
An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_activity' doesn't exist</message>
</meta>
<data/>
</ocs>
```
</details>
- …
> CI: On api-tests fix user creation failure when files already exist for the user

- tests/acceptance/features/bootstrap/FeatureContext.php
This PR is backport of master PR, which fixes the flaky error on ci. 
- https://community.openproject.org/projects/nextcloud-integration/work_packages/62589
> Backport/tests: delete user data on status code 200 or 500

- integration_oidc_setup.sh
This PR backports the master [PR](https://github.com/nextcloud/integration_openproject/pull/843/commits)
> Backport: fixed OIDC setup script

- .github/CODEOWNERS
I'm no longer actively working on integration topics 😇👋🏾
> Remove @akabiru from CODEOWNERS

- .gitignore
- dev/compose.yaml
- dev/keycloak.yaml
- dev/nextcloud/hooks/after-install.sh
- dev/opnc-realm.json
Updated docker images of the services:
- `quay.io/keycloak/keycloak:21.1` -> `quay.io/keycloak/keycloak:26.2`
- `openproject/openproject:15` -> `openproject/openproject:16`
> build: upgrade docker images

- lib/Settings/Admin.php
- src/components/AdminSettings.vue
- src/components/admin/FormAuthMethod.vue
- tests/jest/components/AdminSettings.spec.js
- tests/jest/components/__snapshots__/AdminSettings.spec.js.snap
- tests/jest/components/admin/FormAuthMethod.spec.js
- tests/jest/components/admin/__snapshots__/FormAuthMethod.spec.js.snap
Separate the authentication method form into its own component
Setup:
|Old | This PR |
--|--
Setup error:
| Old | This PR |
--|--
- [WP#62137](https://community.openproject.org/wp/62137)
> refactor: split auth method form

- docs/testing/smoke_testing.md
This PR adds documentation for smoke testing the `Single-Sign-On through OpenID Connect Identity Provider`.
- https://community.openproject.org/projects/nextcloud-integration/work_packages/64469
> add docs for smoke testing of sso authentication

- CHANGELOG.md
- appinfo/info.xml
- package.json
> chore: prepare release 2.9.2

- CHANGELOG.md
- lib/Listener/LoadSidebarScript.php
- lib/Migration/Version2900Date20250718065820.php
- lib/Service/OpenProjectAPIService.php
- src/components/AdminSettings.vue
- tests/jest/components/AdminSettings.spec.js
- tests/lib/Controller/ConfigControllerTest.php
- tests/lib/Controller/OpenProjectControllerTest.php
- tests/lib/Listener/LoadSidebarScriptTest.php
- tests/lib/Service/OpenProjectAPIServiceTest.php
- tests/lib/Settings/AdminTest.php
- tests/lib/Settings/PersonalTest.php
Merge back release/2.9 branch to the master
> chore: merge back release2.9 branch

- CHANGELOG.md
Merge back release/2.9 branch to the master
> chore: merge release 2.9 branch

- dev/compose.yaml
- dev/nextcloud/hooks/after-install.sh
Port of https://github.com/nextcloud/integration_openproject/pull/878
> build: enable bearer token check for the requests (#878)

- .github/workflows/shared_workflow.yml
- CHANGELOG.md
- appinfo/info.xml
Add application support nextcloud master(33)
> Chore: add support for nextcloud master 33

- .github/workflows/shared_workflow.yml
> ci: remove workflow for nextcloud master branch

- CHANGELOG.md
- lib/AppInfo/Application.php
Rename the Nextcloud group name:
From: `OpenProjectSuspended`
To: `OpenProjectNoAutomaticProjectFolders`
- https://community.openproject.org/projects/nextcloud-integration/work_packages/67455
> [#WP 67455] [chore: rename nextcloud group name]

- CHANGELOG.md
Updated CHANGELOG after feature subject gor updated
> Update CHANGELOG with renamed feature

- CHANGELOG.md
> Change release date for 2.10.0

- .github/workflows/nighlty-ci-release-branch.yml
- .tx/backport
- appinfo/info.xml
> CI: Update release branch

- .github/workflows/nighlty-ci-release-branch.yml
> Add nc 32 in release CI

- integration_oidc_setup.sh
- integration_setup.sh
Remove unnecessary headers from GET requests.
Some NC requests fail with NC32
> fix: remove unnecessary headers from GET requests

- docs/testing/smoke_testing.md
This PR adds documentation for the `upgrade testing`.
-  https://community.openproject.org/projects/nextcloud-integration/work_packages/67691
> docs: add docs for upgrade testing
